### ISSUE TITLE
Initial home page view for anonymous users?

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#102]
@thinkcollege when an anonymous user visits the home page, what does they see initially? Do we display data for "all states" or a default state or something else?

-mike

**Comment by thinkcollege** [comment]
See the image I just sent you.  The images I sent are broken down by user type. See here too.
![escoach_wireframe_anon](https://github.com/communityinclusion/escoach/assets/1806420/eb3b8758-96fe-44e6-843d-d1e3348eba90)

**Comment by ultimike** [comment]
@thinkcollege Yes, but where does the data come from? Which state? All of them?

**Comment by thinkcollege** [comment]
"All" is from all states.  There will be a selector showing states with data.  I am not sure if a random state will show on first view or no state.  Probably the latter.  I am going to add a State field to the surveycampaign_results table, pulled from the user profile that will provide the filter for state data.  There is currently a "region" field in the surveycampaign_results table which indicates user state, but that is pulled from the Alchemer survey, from the user's ip, and is not reliable.  However, you can use that field for testing, and I will replace it and let you know when it is ready.

**Comment by thinkcollege** [comment]
I added a 'state' field to the surveycampaign_results table on the live site.  I manually populated past entries with users' state from their profiles.  As results come in every day the state field will get populated automatically.  You can use this to query results by state.

**Comment by thinkcollege** [comment]
Here is the current live site database.
[escoach_9_5_23.zip](https://github.com/communityinclusion/escoach/files/12527297/escoach_9_5_23.zip)

**Comment by ultimike** [comment]
@thinkcollege thanks for the database.

I just merged `rack` into `devel` and pushed the `devel` branch. @mgcobblestone and I will use `devel` as our working branch.

thanks,
-mike

**Comment by mgcobblestone** [comment]
@thinkcollege How is the average hours per day calculated?

Is the calculation different for the various use cases: Me, My Team, Provider, State, All ?

**Comment by thinkcollege** [comment]
@mgcobblestone I am not sure how to answer this question.  The queries you built for the existing dashboard should have this logic built in.  What is different about the new queries for this version of the dashboard?

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege , I wasn't sure if the calculation would be different or not given the restricted date range.

**Comment by ultimike** [comment]
@mgcobblestone Just capturing these issues we just discussed here since I have this issue open...

For anonymous users on the `/home/activities` page:

1. No chart (probably related to console error). 
2. Can't change states (also probably related to console error).

-mike

**Comment by mgcobblestone** [comment]
@ultimike I am not seeing this.  Can you post the console error you're seeing?

**Comment by ultimike** [comment]
@mgcobblestone It is now working on my local 👍 

@thinkcollege Assigning to you for review on the Dev site.

-mike
