### ISSUE TITLE
New "ICI staff" downloadable table in es-coach_wireframe_Paul_edits_9_7-23.pdf

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#103]
@thinkcollege,

On page 8 of es-coach_wireframe_Paul_edits_9_7-23.pdf, there is an annotation in the lower left that reads, 

```
ICI staff will be able to select “All” and thus download a spreadsheet that includes the following fields:
a) State
b) Provider’s name,
c) Manager’s name,
d) Manager’s email,
e) Respondent’s name
f) Respondent’s email,
g) 4 key activities and 5 best practices 
h) Response rate
i) #participants
```

This is a new request, correct? We have some questions about it:

1. This table seems completely different than the other .csv files we will generate for the homepage. Perhaps it should be a separate download link? 
2. Is there any reason why the user has to select "All" in the provider select prior to this being available for download? If the user selects "All", then isn't the expectation for the chart and displayed table to include 1 column for each provider associated with the TA user? If so, that could make the table quite wide, no? The way the request is worded, it seems like this "all" data is really more geared towards the new file download, correct? 
3. Where is the manager's name and email data coming from? We checked the `surveycampaign_results` table as well as the "Survey participation settings" profile type and do not see it.
4. We are not clear on how to generate the data for columns g, h, and i as listed above. Can you assist?

Ideally, a sample spreadsheet with some data in it along with how/where to generate/get each piece of data would be very helpful.

This seems like it is similar as the "added feature" bit in  #100, but only for a limited set of providers, correct?

thanks,
-mike

**Comment by thinkcollege** [comment]
1) I didn't catch this.  Alberto slipped this in here without clearing it with me.  This will be a download the same as available to the TA user, except listing all providers in the system, not just those available to the TA user.The link for Admins (ICI staff) should be in the back end, not in the dashboard. 
2) Yes, the "All" selection should not be a thing in this selector. 
3) Manager fields are a no-go. Skip that.  
4) The data for tables g, h, and i is the same data as shown in the tables on the dashboard.  What is the question here?
**Additional**: there should be an additional download from the back end for Admins (ICI staff) that pulls all individuals in the system in the same manner as the tables and downloads shown for the Employment Consultants.  The rows will show the individual data from the best practices and activities tables. The report should include individual name, email, provider, and state fields from the surveycampaign results table.
