### ISSUE TITLE
Updated to Bootstrap 5 theme and subtheme

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#104]
@ultimike I updated to a Bootstrap 5 theme and subtheme on the devel branch (deployed to rs-escoach.communityinclusion.org).  Here is the database for the devel site with the updated theme settings and block positions. Or, you could try downloading the config/sync from the devel site, but when I did the same from my loca it wiped out every single block position.

[escoach_9_19.zip](https://github.com/communityinclusion/escoach/files/12666423/escoach_9_19.zip)

**Comment by ultimike** [comment]
@thinkcollege Thank you - I've updated my code (`devel` branch) and database with what you provided in your previous comment with no issues. I did not run a `drush config-import` based on what you mentioned above.

At some point in the near future, you and I should get the config system all synced up...

cc @mgcobblestone

**Comment by ultimike** [comment]
@thinkcollege I think we can close this issue. If you agree, please do so.

thanks,
-mike
