### ISSUE TITLE
Development timeline

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#106]
Hi @ultimike Just checking in.  I should have mentioned that our grant timeline calls for us to wrap up development on or around November 15.  We are hoping to have a demo version of the dashboard in the next few weeks.  Let me know if you need any input from us to move things along.

**Comment by ultimike** [comment]
@thinkcollege Understood.

I just chatted with @mgcobblestone and so far, we are on-track, focusing on the Key Activities stuff. Best Practices aspects should be quicker.

Let us get through this week and I'll provide you a more detailed update/timeline next week. Does that work for you?

thanks,
-mike

**Comment by thinkcollege** [comment]
That's good.  Looking forward to seeing the product.

**Comment by ultimike** [comment]
@thinkcollege -

1. Is it safe for us to merge (or rebase) the `devel` branch into our `es_home` branch? Any reason why we shouldn't? See #105 
2. @mgcobblestone and I went through progress this morning, and the bulk of the new homepage is complete minus the download .csv stuff. Currently at about 50 hours (estimate for this task was 76 hours). We are aiming to have the download functionality ready later this week. 
3. If you want to test the `es_home` branch, you'll need to know is that the new home page(s) are currently at `/home/activities` and `/home/best_practices`. This is some configuration involved as well (related to the TA profile stuff) - would you like us to commit the config changes to the repository, or would you prefer step-by-step instructions to implement?  
4. In the big picture, assuming we can get downloads finished this week, we will then aim to have tasks 3 and 4 (login by URL and change from POST to GET) complete by November 3.  This should give us enough time to respond to any issues that are found prior to "on or around" November 15.

-mike

**Comment by thinkcollege** [comment]
Hi @ultimike   I removed the es_migrate module from the devel branch.  Go ahead and merge into your branch.  All the theme updates, with the main menu moved to the top are in place, as well as all the D10 updates, except Serialization and Admin can login anyuser.  I will take a look at your development branch.  Thanks for the updates.

**Comment by thinkcollege** [comment]
Oh, and yes you can commit the config file to the repository.  If you are confident it won't wipe out anything on the current devel site.

**Comment by mgcobblestone** [comment]
@thinkcollege I don't see any config in the repo.  Looks like it is configure to use ../config/sync, but this folder is empty in the repo on devel (and non-existent on master)

**Comment by thinkcollege** [comment]
Sorry, @ultimike  I though you were going to give me a config file.  I may not have used config on this site lately or ever.  There is a config/sync directory on both the devel and rack (live site) branches with proper permissions.  You can create a config of the existing setup from the devel and live sites using the web interface.  Does that clarify things?

**Comment by thinkcollege** [comment]
@ultimike I just created a config of the current devel branch from the devel site (rp-escoach.communityinclusion.org) and pushed it to the devel repo.

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege

**Comment by mgcobblestone** [comment]
@thinkcollege , Config updates are in place now in the es_home branch - New profile type and corresponding field to assign providers to TA users

cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I have pushed an update to the es_home branch that includes CSV downloads on the Key Activities and Best Practices pages.  If you are able to test this, please let me know if the format/structure of the download is correct.

I still need to work on the admin download.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone How can I see or try out the new ability to assign providers to TA admin users?  I don't see a new profile type or any new fields in user types?  I merged the es_home branch into devel and have it deployed to rs-escoach.communityinclusion.org

**Comment by mgcobblestone** [comment]
@thinkcollege  You'll need to import the config - there is a new profile type that includes the new field.

**Comment by thinkcollege** [comment]
Import how? Isn't it in the config/sync folder in the repo?

**Comment by mgcobblestone** [comment]
Yes, it is.  You can either use "drush cim" or in the UI, go to Config -> Development -> Config Synchronization and click on the Import All button

**Comment by thinkcollege** [comment]
@ultimike There is some definite progress here.  Keep it up.

**Comment by ultimike** [comment]
All credit to @mgcobblestone - he's been taking the lead on this stuff.

**Comment by ultimike** [comment]
@thinkcollege I think that we can close this issue, correct?

-mike
