### ISSUE TITLE
Change dashboard form from POST to GET

### ISSUE THREAD

**Issue by mgcobblestone** [communityinclusion/escoach#108]
Change the dashboard form from a POST to GET submission so that users can be taken to a preset form query using a URL. This functionality will work in tandem with task 3 (above), so that a single url can be provided to a user to allow them to login and view a predetermined dashboard configuration.

**Comment by ultimike** [comment]
@mgcobblestone created a new `dashboard-get` branch for this issue.

**Comment by ultimike** [comment]
@mgcobblestone Looks good - I tested `/dashboard` with a bunch of different values and confirmed that the URL looks as expected. I then loaded the URL in the browser and the Dashboard appears as I expect.

Merged into the `es_home` branch. 

@thinkcollege Please review.

thanks,
-mike
