### ISSUE TITLE
Legacy dashboard js broken on live site (rack branch)

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#109]
@ultimike @mgcobblestone The legacy dashboard (/dashboard) is broken on the live site since I upgraded to Drupal 10.  No charts, and some problems with select lists.  I see js errors.  I have seen this on other sites I upgraded.  The "once" library is gone so some of the functions have to be changed in survey_dashboard/js/survey_dashboard.js

**Comment by mgcobblestone** [comment]
@thinkcollege Those issues are fixed in the es_home branch.  You should be able to cherry-pick the commit into master:

https://github.com/communityinclusion/escoach/commit/06cd330fe8774ff4a0623d76412e1e979fa3547c

**Comment by thinkcollege** [comment]
Thanks @mgcobblestone
