### ISSUE TITLE
Data discrepancies between new  home page and existing dashboard

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#110]
From emails between Paul and myself.

### First issue

> The number of respondents is not correct. For example, for JCFS “# of respondents” = 86. We know they have only 6 or 7 participants. “All” = 1,346 but we know that there are only about 100 participants. These numbers are likely the number of completed surveys, not number of people who completed the surveys. This should be number of individuals submitting, not number of responses.

> I believe you have complete data but the discrepancies Alberto pointed out show up between the legacy dashboard and the new best practices view, so there is an issue no matter what data set you use.  **The discrepancies show up no matter what user role you log in with.**  That is why I suggested that it must be that the new dashboard is not using the correct variables in the best practices query.  Those variables were stated in the design documents and in the notes at the bottom of the best practices table.

### Second issue

> The “Best practices” data does not match the legacy dashboard data. See the cells highlighted in yellow below for the provider “Accord”.  Can you refer back to the original design and planning documents to make sure the right selectors from the legacy dashboard are being called in the Best Practices queries?  This is probably the isssue. --PF

"The cells highlighted in yellow" are the last 5 rows of the table - from "In the community" through "Natural supports".

Accord (October 2023) | Legacy Dashboard | Provider CSV | New Dashboard
-- | -- | -- | --
Leading to Hire | 2:03 | 2:03 | 2:03
AFTER Hire | 2:08 | 2:08 | 2:08
Administrative | 3:33 | 3:33 | 3:33
Non-Employment | 0:16 | 0:16 | 0:16
In the Community | 0:37 | 0:00 | 0:00
With Family | 0:16 | 3:26 | 3:26
Observing | 0:05 | 1:09 | 1:09
Networking | 0:05 | 1:09 | 1:09
Natural Supports | 0:11 | 2:17 | 2:17

**Comment by mgcobblestone** [comment]
Hi @thinkcollege I have made a few adjustments, please download the latest commits and take another look.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone A few of us looked over the data results on the dashboard, on rs-escoach.communityinclusion.org  There is still a discrepancy with one of the data rows, "In the Community" under Best practices.  The value on the new dashboard differes from November 2023 values in the legacy dashboard, using the same variable selections. Could you check if the new dashboard is making the right variable selections for In the Community?
cd: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I have updated the query parameters for In the Community.  Please take another look.  If there is still an issue, please provide some examples of where you are seeing incorrect results.  Thanks!

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone We are still seeing a discrepancy between the new Best practices dashboard for the data for My Team (provider) in the "In the Community" row with the data provided by the legacy dashboard. As it says in Definitions under the best practices dashboard, In the Community is produced by checking "Where = (At the residence of a person I support OR At a business OR In other community integrated settings) AND What = (Getting to know a job seeker OR Finding, securing jobs OR Other supports BEFORE hire)."  
When I log in as a user for provider Accord (username: hunter.schouviller@accord.org pwd: test9876) I see a value of 0:10 for my provider time in In the Community, but if I go to the legacy dashboard and check the values noted above, time frame: Monthly trends,  I get a provider value for Accord in Nov. 2023 of 1:07 for Accord.
Go ahead and try any user on rp-escoach.communityinclusion.org: you can edit passwords and log in as anyone. But DON'T run cron on this site, please).  I have updated the surveycampaign_results and surveycampaign_mailer tables to today.
Our staff tried this on a number of different providers and got the same problem, but found other data in the new dashboard to be working alright.  By the way, we wanted you to remove ONLY the superscript numbers in the definitions under Best practices, not the definitions they referred to.

**Comment by thinkcollege** [comment]
@mgcobblestone Here is the db from the development site if you want to try it out locally.
[escoach_12_6_23.tar.gz](https://github.com/communityinclusion/escoach/files/13588746/escoach_12_6_23.tar.gz)

**Comment by mgcobblestone** [comment]
Thanks for the DB dump @thinkcollege , I have imported it and I am not seeing the discrepancy. I see 1:07 in both screens:

![image](https://github.com/communityinclusion/escoach/assets/29606495/f1935d8e-ff2b-4486-b213-6819fa47e6f4)

![image](https://github.com/communityinclusion/escoach/assets/29606495/2300f568-f60e-4c81-92f4-c9e4c7247172)

**Comment by thinkcollege** [comment]
@mgcobblestone Yes, that looks right.  When I was testing yesterday it was not.  I pulled your changes from yesterday to bestPracticesQuery.php this morning and now I am getting the correct data for "In the Community."  I will give our data people another chance to look things over, but this may be good now.
