### ISSUE TITLE
Home page dashboard tweaks

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#111]
Some requested tweaks based on feedback from Alberto:

### data tables

- [ ] “Better than last month” and “Better than “All”” should be included also for the “Response rate”. It’s missing
- [ ] Can all numbers be formatted with a comma separator when > 1,000?
- [ ] Can the response rate be rounded to the nearest unit e.g. 63% instead of 63.16%

### .csv downloads

- [ ] for User download: add email, regcode, and  state columns from surveycampaign_results table
- [ ] for Provider download: add state column from regcode table
- [ ] In user and provider download: we don't want "NO/YES" in "AFTER hire" column.  There is no better/worse evaluation for that activity on the dashboard, and we don't want it in the spreadsheet.

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed up a few updates that address the data tables issues as well as issues 1 and 3 for .csv downloads.

Please download and test and let me know if there are any issues.

For .csv downloads issue 2, I'm not sure how to go about this as the state field is not necessarily unique for each provider.  Also, I'm assuming he meant surveycampaign_results table as there is no regcode table.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone As far as adding the state field to the provider download, each provider belongs to only one state.  I see in the surveycampaign_results table there are a few providers where some early users didn't fill in the state field and there is a Null.  I see only one instance where an individual filled in the wrong state.  And there are a few providers--Observer, no provider--that have multiple states.  Those providers are for test accounts and aren't relevant.  I think it would be safe in the provider download to use the state field value that is MAX() for the provider.  Does that work for you?
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege That sounds good, thanks.

**Comment by mgcobblestone** [comment]
@thinkcollege New commit is up with state field in provider CSV.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone I see the additional field, that's good.  But the User CSV download now produces a 504 timeout on rp-escoach.communityinclusion.org.  That is after deploying all changes to the es_homepage module to that server.  I cranked max_execution_time and max_input_time way up on php.ini but it wasn't enough.  Both provider and user downloads take a long time.  Is there any way to speed up those queries?
