### ISSUE TITLE
New home page dashboard design tweaks based on feedback

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#112]
Via an email from Paul on November 30, 2023:

- [x] Can the rows of response rate and #participants be better separated? e.g. thicker line?
- [x] In the notes at the bottom of the dashboard, remove the extra “=” after “# of Respondents”.
- [x] Remove the superscript notes associated with the “Best Practices”? I know we asked for those. But it looks inconsistent that we do not have the same superscript numbers for “Key Activities”.
- [ ] Any chance that the chart on the phone interface can be more spread out across the screen? It looks pushed to the right side of the screen.
- [x] (Added Dec 15, 2023) Enable tooltips in tables
- [x] (Added Dec 15, 2023) Dashboard columns--Should be col-4/col-8 instead of col-5/col-7
- [x] (Added Dec 15, 2023) Move mobile menu button to top-right 
- [x] (Added Dec 15, 2023) Definitions box needs padding and bottom margin

Assigning to @thinkcollege to let us know when to proceed with these changes after discussion with his designer.

**Comment by ultimike** [comment]
@thinkcollege and I have discussed the Google Chart formatting issue (item 4 above) previously, and I don't think there's much we can do about it, as other than the parameters that Google Chart exposes to developers, there's not much we can do.

**Comment by thinkcollege** [comment]
@ultimike  About the chart alignment on phone being pushed to right: let's drop that.  Not worth pursuing.
Other issues: 

- a thicker line above the response rate and # of respondents rows, separating them from the rows above.  Go ahead with that.
- Removing the superscript notations in best practices table for consistency with Activities table.  go for it.
- remove the extra “=” after “# of Respondents”  Yes, that is a typo that needs to be fixed.

**Comment by ultimike** [comment]
@thinkcollege The 3 items mentioned in your previous comment have been fixed in the `es_home` branch.

Please review and mark this issue as closed if all is good here.

-mike

**Comment by thinkcollege** [comment]
@ultimike In response to the request above to remove the superscript numbers in the table on the Best practices dashboard, it looks like you commented out the definitions that the superscripts referred to.  We just wanted the superscript numbers removed not the definitions.

**Comment by ultimike** [comment]
Apologies - should be fixed now (pushed to `es_home` branch).

-mike

**Comment by thinkcollege** [comment]
@ultimike  I had our designer, Julie, look over the demo site, rp-escoach.communityinclusion, and she had a few comments:
    • Need tool tips for icon in tables (as in demo, https://jreposa.github.io/index.html)
    • Dashboard columns--Should be col-4/col-8 instead of col-5/col-7 ?
    • Mobile menu -float right (see image)
![mobile_menu](https://github.com/communityinclusion/escoach/assets/1806420/dbcad9ca-10f9-4d0e-9227-6ca46c59a6a3)

    • Definitions box needs padding and bottom margin

**Comment by ultimike** [comment]
@thinkcollege I've made the requested changes to the `es_home` branch. Please review and let me know.

-mike

cc @mgcobblestone

**Comment by thinkcollege** [comment]
@ultimike Here's another issue on the dashboard:  the Google chart resizes appropriately to the screen size on page load.  But it doesn't resize on browser window resize.  Could you add a little js so it will do that?  We've had a few people comment on that.
cc: @mgcobblestone

**Comment by thinkcollege** [comment]
@ultimike  BTW.  Style changes and tooltips from above looking good.

**Comment by ultimike** [comment]
@thinkcollege I have just pushed a commit to redraw the charts on both the home page and legacy dashboard when the browser window is resized. 

@mgcobblestone If you have a moment, please review [my changes](https://github.com/communityinclusion/escoach/commit/4621c5526f942a3ef18efe51a97b9c175a065ee4) - I'm pretty sure they're sound, but confirmation would be swell 😁

thanks,
-mike

**Comment by mgcobblestone** [comment]
@ultimike Looks good to me.

**Comment by thinkcollege** [comment]
Looks good to me.  Also, @ultimike I just watched your tutorial on using VS Code with DDEV.  I didn't know about Drupal Smart Snippets.  Pretty great.
