### ISSUE TITLE
User download still very slow

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#113]
@mgcobblestone This was in an issue a while back, but I wasn't able to find it.  The User download (for admins, Reports/User CSV Download) is still very slow.  I had to crank up timeout settings very high in php.ini on the dev site to get it to work.  It is very slow but functional on my local where I have fewer users.  I think this will become a problem as the system takes on more users.  
Would it be possible to speed up this query?
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I'll take a look and see what I can do.

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have converted the user download functionality to use batch processing.  Please try out the new commit and let me know if this works for you.
Thanks.
cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone The download works, but leaving the user on a blank white "click here" page is not going to be very user friendly.  The user has to back button twice to get through the download processing page. I have other sites where I set up batch downloads and it at least keeps me on the processing page with the site wrapper and menus intact, and gives me a popup for download when the processing is done.  
Cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I'll take a look and see what I can do.

**Comment by mgcobblestone** [comment]
@thinkcollege , I have an update in place, please take another look.
Note:  You'll need to clear caches

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone This is acceptable, good enough for admin users.  Thanks.
cc: @ultimike
