### ISSUE TITLE
Problems with response rates

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#114]
@mgcobblestone 
The following issues were detected using the development site rp-escoach.communityinclusion.org, which was updated today 1/5/24 with the complete db from the live site and the config from a site running the devel branch, and is running the devel branch, which is up to date with the code on the es_home branch.  See attached db and csv download files.

 1. Problems with response rates: Response rates are being calculated differently for "Provider" and "All."
 Using Accord, again, as an example, the response rate on the dashboard is  87% which I don't really understand (40/48 should give you 83). However, ALL’s response rate on the dashboard is 83.1%. That is not correct. It should be 71%
 This appears  to be because the Provider is querying a response rate for net responses, that is, not including "out of office" responses.  The All rate is pulling all responses including "out of office."  See below for the query I gave you a while back that distinguish between these different calculations of responses:
 
` select mailer.provider, count(*) 'total surveys sent including out of office' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values' , (count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total surveys sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2023-12-01 00:00:00' AND mailer.senddate <= '2023-12-31 23:00:00' group by mailer.provider`
 
 the query for All would be:
 
 `select count(*) 'total surveys sent including out of office',count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values' , (count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total surveys sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2023-12-01 00:00:00' AND mailer.senddate <= '2023-12-31 23:00:00' `
 
 The value queried above labeled 'net responses/total surveys sent' should be the response rate. This should be true for all calculations of response rates for state, provider and all.
 
 2. Again, using the dasboard on rp-escoach.communityinclusion.org, logged in as TA user, selecting provider Accord, Accord’s response rate on the dashboard is 87.0% whereas the downloaded provider-data.csv (downloaded as admin, see attached) shows 86.96%. Accord’s number of respondents is 40 on the dashboard and 46 in the downloaded provider-data.csv.
 3. I see the same discrepancy in the Survey participant download (see attached file).
 Also, in the download csv's we would like to round percentage values to one decimal place, as in the dashboard.

cc: @ultimike 

[escoach_live_1_5_24.zip](https://github.com/communityinclusion/escoach/files/13844135/escoach_live_1_5_24.zip)
[provider-data.csv](https://github.com/communityinclusion/escoach/files/13844136/provider-data.csv)
[user-data.csv](https://github.com/communityinclusion/escoach/files/13844137/user-data.csv)
[activity-download-Accord.csv](https://github.com/communityinclusion/escoach/files/13844349/activity-download-Accord.csv)

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed a new update.  The issue was that the queries were using the date_submitted field instead of senddate.  Included in this update is rounding of the response rates in the CSV downloads.

cc: @ultimike
