### ISSUE TITLE
Better than last month icon not showing up on dashboard in some cases

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#115]
@mgcobblestone 

1. Using the provider Accord as an example, while signed in as a TA user (or as a Survey participant assigned to Accord) to rp-escoach.communityinclusion.org, and looking at the dashboard, the better than last month icon doesn't show up in supports leading to hire metric (Nov = 2:34, Dec = 3:07) It only shows as being better than all. 
 2. Nothing is coming up as "better than last month" in the best practices tab. An example is Accord in natural supports. In November they spent 0:10 minutes on that practice and in December spent 0:12 minutes on that metric, so the dashboard should display the icon indicating better than last month and it does not. 
The above was detected on the rp-escoach.communityinclusion.org dev site running the devel branch using db attached to #114

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed a fix for this.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone Testing on rp-escoach.communityinclusion.org (up to date with latest es_home) shows some remaining issues. In Minnesota, their administrative activities for December should be better than all because it is less than 2:52 (from November), I see the same issue for Continuum of Colorado at the provider level. They have 2:40 dedicated to administrative activities so it should be marked as better than all (2:52 for November) as well. The better than all and better than last month seems to be working as intended in other areas, I think since "better than" actually means "less" for that metric something may have gotten off.
cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone @ultimike Any fixes for this?

**Comment by mgcobblestone** [comment]
@thinkcollege Please be sure to assign any issues to me that need my attention.  I'll look into this and 118 over the next day or so.

**Comment by mgcobblestone** [comment]
@thinkcollege  I have pushed a fix for this issue related to the "All" comparison.  I did not find any issues with "Better than last month".  If you are still seeing an issue with that, please provide the specifics.

cc: @ultimike
