### ISSUE TITLE
Mislabeled column in user-data.csv download

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#116]
@mgcobblestone 
In the user-data.csv file, downloaded as an admin user from the development site, the final column is labeled # of respondents.  This label needs to be changed to "# of responses" since there is only one respondent.

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed a fix for this.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone Looks good.

**Comment by thinkcollege** [comment]
@mgcobblestone 
The provider and user CSV downloads from the admin side are missing "better than all" and "better than last month" columns for the After Hire variable.
cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
Those columns were being explicitly excluded. I believe that was a previous request. I have added them back.

cc: @ultimike
