### ISSUE TITLE
Would like the state and provider selectors to retain values when switching dashboard view

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#117]
@mgcobblestone 
In the dashboard, when logged in as TA user, switching from Activities to Best Practices, or back, causes the select list to reset the provider and the user has to change it again.  This is confusing.  This also happens with the state selector for anonymous users.
cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
How/where is the navigation implemented for the menu that contains the links for Activities/Best Practices?

**Comment by thinkcollege** [comment]
@mgcobblestone  That is in the es_homepage module routing.  The menu for activites/best practices is in a menu your or Mike created and put in a block on the dashboard.

**Comment by thinkcollege** [comment]
@mgcobblestone  Looks like this is working.  The values in the select list are remaining constant when changing from state to state or provider to provider.
cc: @ultimike
