### ISSUE TITLE
Add legends to activities chart and to activities and best practices tables

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#119]
@mgcobblestone 
See the illustration.  We want to add legends to all charts and tables as shown.  The chart legend should read "Monthly percentage of time in activities"  The table legends should read "Average hours:minutes per day in activities"
The chart legend could be an h2; I don't know if there is a way to add an html legend to a Google chart.  The table legend should preferably be a legend element on the table. Note: the red border around the legends is just to point them out.  Don't add them to the web page.
![dasboard_legends](https://github.com/communityinclusion/escoach/assets/1806420/49c28948-77d7-4b10-a2ac-6bbd47e2b986)
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I have pushed an update for this.

cc: @ultimike

**Comment by thinkcollege** [comment]
Looks good.

**Comment by thinkcollege** [comment]
@mgcobblestone @ultimike  Reopening this: could you bold the table headers? Also, the table header is appearing on the Activities tab but not on the Best Practices tab.

**Comment by mgcobblestone** [comment]
@thinkcollege Fix is up
