### ISSUE TITLE
Build taxonomies for what/who/where/data-frame/time-frame

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#12]
Implement each of the "selection groups" as a vocabulary with additional "question_id" and "answer_id" integer fields on the term entity.

See data to migrate in [this Google Sheet](https://docs.google.com/spreadsheets/d/1uXQ1ZFLHUA_hm3mja89YIfaZ-D4WcAl1O8Sotro5OpE/edit#gid=0).

Notes:

- "What" is a hierarchy.
- "data frame" and "time frame" vocabularies will not need the "question_id" and "answer_id" fields.

**Comment by ultimike** [comment]
@thinkcollege Once I create these on my local, I'd like to export the site config and commit it to the repo.

Currently, on the `devel` branch, in the settings.php file, the config_sync_directory is set as:

`$settings['config_sync_directory'] = 'sites/default/files/config_Sz4-eTTIFcnZPcnPQKy5E0u5vCjQjpdhVsnrtos_4nmKY0U1HKkbg1zLAFdMk8nKR3kRcA_DEQ/sync';`

I'd like to modify this to `../config/sync/` and commit it to the repo. Is this okay with you?

-mike

P.S. While I'm at it, I'd also like to commit to settings.php a conditional include for the DDEV settings file - is this also okay with you?

```
// Automatically generated include for settings managed by ddev.
$ddev_settings = dirname(__FILE__) . '/settings.ddev.php';
if (is_readable($ddev_settings) && getenv('IS_DDEV_PROJECT') == 'true') {
  require $ddev_settings;
}
```

**Comment by thinkcollege** [comment]
All that looks good.  I haven't done anything at all with config on this site, so any file location changes are okay.  As far as you config changes harming anything in the existing db, are you doing a complete config import, or just some taxonomies or views? I will save the db right now in case anything gets changed.  I put the current db in the Teams project, files section, escoach_5_10_21.sql

**Comment by ultimike** [comment]
@thinkcollege If we decide to use the config system, then we all have to use it the same way or we risk losing config along the way.

So, here's what I'll do:

- I'll import the latest DB you just provided (`escoach_5_10_21.sql`) to my local.
- I'll change the location of the config sync directory to /config/sync/
- I'll export and commit the current config.

Once that is done, then each time any of us pull, we're going to want to run `drush config-import` as well. If any of us change config on our local or any remote environment, we're going to have to run `drush config-export` and commit the changes.

Keep in mind that the Drupal 8/9 configuration system is all-or-nothing - it's not like Drupal 7 Features where you pick and choose what gets imported/exported. When using it, we're always doing a complete config import/export.

Sound like a plan?

-mike

**Comment by thinkcollege** [comment]
That sounds great.  Thanks for setting that up and clarifying.  Though, I have done im/ex of Views and Taxonomies in D8, though you get a pretty bare bones structure.  Most full im/ex I have done have gotten into complex database conflicts with themes, modules, etc.  And forget it if you imported the site from D7.

**Comment by ultimike** [comment]
@thinkcollege I've performed the operations described above (imported latest DB, changed location of config/sync, and exported config) and committed it all to the `devel` branch.

When you pull, I recommend the following:

1. Backup your local DB.
2. Pull.
3. `drush config-import`
4. Check to make sure all is well with your local.

The commit also has the start of a new `escoach_migrate` module (not yet enabled) that I'm writing to import the What/Who/Where taxonomy terms.

-mike

**Comment by thinkcollege** [comment]
Any idea what this is about on config-import:
`The import failed due to the following reasons:                                                                                                                             
  Configuration <em class="placeholder">ahead_boot4.settings</em> depends on the <em class="placeholder">ahead_boot4</em> extension that will not be installed after import.  `

**Comment by ultimike** [comment]
I'm not sure - what is `ahead_boot4`? It doesn't look like a contrib or custom module (at least not one in the repository). If it is something from the past, then remove the `ahead_boot4.yml` file from the config directory and try the import again. If it works, then commit the file deletion.

I just committed and pushed stuff to migrate in the What/Who/Where terms to 3 new vocabularies. Included in the commit are:

- An update to drupal/csv_serialization module (required by the migrate_source_csv module).
- Migrate Source CSV module.
- Config Devel module.
- Config Split module.
- Updates to the custom es_migrate module.
- Config changes that include the three new what/who/where vocabularies and fields, newly enabled modules (all for the es_migrate module).

@mgcobblestone The what/who/where migration is ready for you when you get started on this stuff - just let me know and I'll walk you through it.

-mike

**Comment by ultimike** [comment]
Are you sure about that? In the codebase, all I see is a custom `escoach_boot4` theme...

**Comment by ultimike** [comment]
@thinkcollege Can this be closed? If so, please do.

-mike
