### ISSUE TITLE
Don't show a state if it has <= 3 providers

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#121]
In the anonymous dashboard view we don't want to see data for states that only received data from survey participants representing 3 or fewer providers.  The states with three or fewer providers should not appear in the dropdown select for the dashboard.  The site owners are concerned about making data public when the providers could too easily be identified.  The data from the surveys and participants from those states will still be counted in the All data, but the states with <= 3 providers will not appear in the dropdown.
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege New commit is up.

cc: @ultimike

**Comment by thinkcollege** [comment]
Looking good.

**Comment by thinkcollege** [comment]
Reopening. I made a mistake in the above criteria for this issue.  States should be hidden from the select list in the anonymous view if they have < 3 providers NOT <= 3 as I stated above.  We need that change.
cc @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege , I have pushed an update.

cc: @ultimike

**Comment by thinkcollege** [comment]
That's it.
