### ISSUE TITLE
Add a definition for anonymous users

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#123]
Add the following definition at the bottom of the “Definitions” section: “State = U.S. state with at least three employment programs participating”.
This would show up only for anonymous users (both Activities and Best Practices views).
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege , update is pushed.

cc: @ultimike

**Comment by thinkcollege** [comment]
Okay.
