### ISSUE TITLE
The Best Practices table is not showing the "better than last month" icon

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#124]
The Best Practice table is not showing the icon for improvement compared to the previous month. (Key Activities looks good). See for example:  
    1. Continuum of Colorado: “With families” = 0:08 in January vs 0:00 in December. Currently not showing the icon for improvement in Jan compared to Dec.
    2. Continuum of Colorado: “Natural Support” = 0:08 in January vs 0:00 in December. Currently not showing the icon for improvement compared to previous month.
The 'better than last month' icon is working for Activites, though. I tried several providers using the TA Admin and Survey participant roles and was never able to get a better than last month icon using the Rack (live) and Devel branches.  Both are up to date with es_home as far as your code.  The live site has current data and the devel site has data through January.
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege Please provide an updated db dump with January data.
Thanks.

**Comment by thinkcollege** [comment]
@mgcobblestone Here are the up-to-date surveycampaign tables from the live site.
[surveycampaign_tables.zip](https://github.com/communityinclusion/escoach/files/14425477/surveycampaign_tables.zip)
Also, here is the entire site db, if that helps:

[escoach.zip](https://github.com/communityinclusion/escoach/files/14425519/escoach.zip)

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege !

**Comment by mgcobblestone** [comment]
@thinkcollege Fix is up.

cc: @ultimike

**Comment by thinkcollege** [comment]
Working okay now.
