### ISSUE TITLE
Add an empty default provider (none) at the top of the select list for TA Admin users of the dashboard

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#125]
When a TA Admin user goes to the dashboard the first provider assigned to them shows up by default in the provider select list, and the dashboard displays the data for that provider.  Our TA Admins want to be able to go to this screen and show no data on page load, just the All column in chart and table (or no data in the Provider column).  They would then be able to select and load data from a provider on their list.  Rationale: The TA Admins do a lot of screen sharing of the dashboard and they don't want to be showing a given provider's data to another provider.
cc: @umtimike

**Comment by mgcobblestone** [comment]
@thinkcollege Update is pushed.

cc: @ultimike

**Comment by thinkcollege** [comment]
Looks good.
