### ISSUE TITLE
If a user ("Me") or provider ("My Team") has no responses in a month, show a dash "--" instead of zero

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#126]
In the dashboard, for Activities, or Best Practices, if Me or My Team has no survey responses in a month (Response Rate: 0) they should show dashes "--" for activities in the tables instead of zeros. "Response Rate," and "# of Respondents" should show 0 but the activities should show the double dash and there should be no "better than all" or "better than last month" icons.
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege  I have pushed up an update.  There are multiple places in the templates where changes needed to be made.  I think I got them all but let me know if I missed any.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone  So far so good, but I am seeing "better than" symbols next to the dashes, where there shouldn't be any.  See screenshots.  This is on rp-escoach.communityinclusion.org using the devel branch with merged es_homepage module from the es_home branch and data current.
![Screenshot from 2024-03-12 13-49-14](https://github.com/communityinclusion/escoach/assets/1806420/da20427b-0442-4ec8-9e89-f2484c99d90b)
![Screenshot from 2024-03-12 13-47-04](https://github.com/communityinclusion/escoach/assets/1806420/e9ddc670-adcf-4184-9a5d-3a9b0ef00dcd)
Am I missing something?

**Comment by mgcobblestone** [comment]
@thinkcollege I have pushed an update.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone  This looks to be working as requested.  Closing.
@ultimike
