### ISSUE TITLE
Autologin URL form is truncating URLs

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#127]
The form at /admin/reports/es_home/auto_login_urls has a "Redirect URL" field to enter a URL for autologins.  But the field can only handle about 120 characters and it truncates longer URLs--such as those for the 'legacy' dashboard when there is a long string of variables.  Can this field be set to allow more characters?  And will the Autologin feature work with a longer URL string?
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege  I have pushed up a fix for this to allow longer URLs.  Yes, longer URLs should work - the database field allows for up to 1000 characters.  I updated the maxlength of the field to match this.

cc: @ultimike

**Comment by thinkcollege** [comment]
Looks good after some testing.
