### ISSUE TITLE
Individual response rate is off

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#128]
Our data team found discrepancies in the individual response rate both in the admin user download and on the dashboard for individual users.  I tested this on the live site and on my local using the latest database, looking at data for February.
Here are some examples I was given which you can see if you download the individual report:

-  Zuri Trotter: 11 valid surveys, 16 Twilio texts, should be a 69% response rate for February but the report from the website shows a response rate of 79%
- Molly Marchese: 9 valid , 16 Twilio texts, should be 56% response rate, but the report shows 53%
- Deanna Davis: 12 valid surveys, 19 Twilio texts, should be 63% but the report shows 60%. 

I tested this myself (on live site and local, on rack branch, which is up to date with es_home) and looked at the dashboard from the user view on my local.  The discrepancy is on the user dashboard too. 
If I run a MySQL query on the live database I get correct response rate calculations.  Here is the query I gave you a while back to calculate response rates:
`select mailer.fullname, email,mailer.provider, count(*) 'total surveys sent to individual including out of office' , count(case when mailer.Complete =1 then 1 end) - count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values', (count(case when mailer.Complete =1 then 1 end) - count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id  where mailer.surveyid = 5420562 AND mailer.senddate >= '2024-02-01 00:00:00' AND mailer.senddate <= '2024-02-29 23:00:00' group by mailer.fullname order by fullname`

I attached the user download from the live site.
[user-data.csv](https://github.com/communityinclusion/escoach/files/14668903/user-data.csv)
cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
Please provide a database dump from the live site.
Thanks.

**Comment by thinkcollege** [comment]
Attached is a db dump from the live site.  Our team identified the following response rate issues as well:

1. The dashboard shows 175 respondents in February. However, the “User CSV download” file includes only 160 valid users + 6 short code users (provider code less than 9000). 
2. There are discrepancies in the number of respondents in three states:
    MO: dashboard=19 respondents; CSV=18 respondents.  
    NY: dashboard=6 respondents; CSV=5 respondents.
    WA: dashboard=21 respondents; CSV=19 respondents.
3.  According to the CSV, NY should not be displayed on the dashboard because it has only 2 providers.
[escoach_3_22_24.zip](https://github.com/communityinclusion/escoach/files/14722931/escoach_3_22_24.zip)
cc: @ultimike

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege .  I believe this is a data issue.  When performing a join on the surveycampaign_mailer and surveycampaign_results tables and filtering on fullname vs. email, I am seeing different results.  In particular, there are records in mailer that do not have a corresponding record in results, so in the case of Zuri Trotter, this query returns 16 results (2 of which have null values for email and id):

SELECT fullname, email, results.id  FROM `surveycampaign_mailer` mailer
LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id 
WHERE **fullname = 'Zuri Trotter'** AND `senddate` >= '2024-02-01 00:00:00' AND senddate <= '2024-02-29 23:59:59' AND  mailer.surveyid = 5420562;

while this one only returns 14 results:

SELECT fullname, email, results.id  FROM `surveycampaign_mailer` mailer
LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id 
WHERE **email = 'ztrotter@goodwill-ni.org'** AND `senddate` >= '2024-02-01 00:00:00' AND senddate <= '2024-02-29 23:59:59' AND  mailer.surveyid = 5420562;

The user dashboard page filters by email address, so it is finding fewer total surveys sent resulting in a higher response rate.

I can dig deeper on all of the issues reported, but I want to get your thoughts on this first.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone I am not fully understanding this.  There is no email column in the suveycampaign_mailer table.  The number of records in the mailer table is the same as the number of results in the surveycampaign_results table, 14, when you filter out Complete=0, which my query does.  If I take your first query which returns 16 results, and add a WHERE "Complete=1" I get 14 
```
SELECT fullname, email, results.id FROM surveycampaign_mailer mailer
LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id
WHERE fullname = 'Zuri Trotter' AND senddate >= '2024-02-01 00:00:00' AND senddate <= '2024-02-29 23:59:59' AND mailer.surveyid = 5420562 AND mailer.Complete = 1
```
I WISH I had set this system up using Drupal user ids across the board, and I plan to do that some day, but this project started about 5 years ago as a tiny unfunded project, not even using Drupal.  Right now I have to keep an eye on name, email and phone # changes.

**Comment by mgcobblestone** [comment]
@thinkcollege , the email field is in the results table.  This is the field that I am filtering on for the Me column.

I see that adding the Complete = 1 condition eliminates the records with the missing joins, but this also shows that the numbers for this user are correct in the console as 11 / 14 = 79%.  

Where is the 16 coming from?  I don't see it in the spreadsheet you provided.

**Comment by thinkcollege** [comment]
The 16 is total surveys sent, including those with Complete= 0.  The response rate is calculated on (total surveys completed - out of office = 11)/ total surveys sent (16): as in my example query way up at the top of this issue, the last column, 'net responses/total surveys sent' using Zuri Trotter as an example.

**Comment by mgcobblestone** [comment]
ok, thanks.  That number is currently coming back as 14 because of the email filter.  I'll have to look into how to modify the query so that filter is not applied to the total count.

**Comment by mgcobblestone** [comment]
@thinkcollege , I have pushed an update that uses the mailer.fullname field instead of results.email to filter the results for the Me column.  It performs a lookup to get the name value from the results table for the given email.  This was necessary because we need the count from the mailer table including records where the join to results is not satisfied.

Note that if there is any inconsistency in the spelling of the name across different records in either table it will throw off the results.  Additionally, if there are more than one person with the same name (exact spelling), this will also lead to incorrect/inconsistent results.

cc: @ultimike

**Comment by thinkcollege** [comment]
Thanks @mgcobblestone  The response rates now look correct in the dashboard and in CSV downloads.  I would like to add drupal user ids to both the results and mailer tables.  That would make things a little more stable and we could join on those fields.  Originally the system was set up for very short term use but there have been just a few cases of people changing their names and we have dealt with them.  There are just a few people (masochists) who want to get this survey every day long term and that may become an issue.
And just a reminder about the three additional problems I raised above, 5 days ago.
cc: @ultimike
One more thought: in the sample query I gave you above to calculate , I join the mailer and response tables on the contactid field. That has proved to be reilable.  Why can't you do that?

**Comment by mgcobblestone** [comment]
@thinkcollege Let me know when you have added the new fields to those tables and I can update the code.

Also, just letting you know that I am still looking into the 3 issues from above.  On #2, I did count the correct number of users in the CSV for MO and NY, but WA was off by 1.  For #3, I see 3 providers for NY in the user CSV.  I will try to wrap up the other issues tomorrow.

cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed up a fix for the respondent count - it now displays 166 in the dashboard.  I looked into the other discrepancies using the sql dump that you provided and am not seeing the same results that you reported.  I mentioned a couple in my previous comment from yesterday.  The last one, WA is showing 20 in the dashboard for me and 20 corresponding records in the user CSV download.

Let me know if you are still seeing issues and provide an updated SQL dump if the data has changed on your end.
Thanks!

cc: @ultimike

**Comment by thinkcollege** [comment]
One more thing: point #2 above:
            There are discrepancies in the number of respondents in three states:
            MO: dashboard=19 respondents; CSV=18 respondents.
            NY: dashboard=6 respondents; CSV=5 respondents.
            WA: dashboard=21 respondents; CSV=19 respondents.
In the case of New York I see that one of the providers has a registration code less than 10000.  We are not including those lower number registration codes in the All data so they should be excluded from the dashboard as far as counting the number of providers per state shown in the anonymous dashboard to reach the cutoff of >=3

**Comment by mgcobblestone** [comment]
@thinkcollege Using the most recent DB you provided on 3/22, I am seeing 18 respondents for MO, 5 for NY, and 18 for WA on the dashboard.  These numbers match what is in the  user csv report.  If you are seeing different numbers, please provide an updated copy of the DB.

I have pushed an update that filters out providers w/reg. codes < 10000 in the response rate query.  I have also pushed an update that excludes providers w/reg codes > 10000 in the providers per state query. NY no longer appears in the list.

**Comment by thinkcollege** [comment]
Looks good.

**Comment by thinkcollege** [comment]
Sorry to say, I am reopening this issue.  I received the following message from one of the site owners:
________________________
I noticed that the developer fixed the “State” dashboard by filtering out the users with a code <10,000 (Users who are not part  of a legitimate team). As a result, NY state no longer shows up on the dashboard. That’s correct, thank you, I appreciate it.

However, it seems that now the users with the code <10,000 no longer see their individual and team data in the table, although they can still see their data in the chart and in the downloadable table.

See for example the screenshot below of my dashboard, account alberto.migliore@umb.edu, code=1344, team = Observer. The table is empty despite, based on Alchemer, in March I submitted 18 responses. Another person, Leslie, submitted 19 responses. Therefore, I should be able to see my data and my team data.

Here is the required action: the code needs adjustment to ensure that users with a score below 10,000 can always see their individual and team data. However, their data should never feed the aggregated 'All' or state-level data.

Rationale: users with a code <10,000 are not part of legitimate teams. Therefore, their data would contaminate the aggregated “All” or state level data, if used to generate these broader statistics.
![image002](https://github.com/communityinclusion/escoach/assets/1806420/d7892861-3d86-4a91-93b7-355ce1af3588)
______________________________
cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone, @ultimike  Any progress on the above?

**Comment by mgcobblestone** [comment]
Hi @thinkcollege , I have pushed up a fix.

cc: @ultimike

**Comment by thinkcollege** [comment]
Looks good.

**Comment by thinkcollege** [comment]
I am reopening this issue because I think this thread might help in dealing with the current problem.  Here is the report I got from one of our data analysts:
 " In checking the response rates, I found a discrepancy for All response rate. The dashboard currently shows an All response rate of 81% in April but when I calculated it manually (total net responses/total surveys sent including out of office) I got 65% which is more consistent with what we have seen in previous months. The other response rates (individual and provider level) appear to be correct as far as I can tell with my spotchecking."
Here is the query we use to calculate the All response rate:
`select count(*) 'total surveys sent including out of office' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values' , (count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total surveys sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2024-04-01 00:00:00' AND mailer.senddate <= '2024-04-30 23:00:00'`

Since the individual and provider level response rates are correct, maybe the changes you implemented in the thread above didn't get applied to All?
Attached is a current db for the live site.
cc: @ultimike 
[escoach_52.tar.gz](https://github.com/communityinclusion/escoach/files/15189005/escoach_52.tar.gz)

**Comment by mgcobblestone** [comment]
@thinkcollege , based on the previous request to filter out responses where regcode < 10000 I had added that condition to the WHERE clause, which is resulting in the numbers you are seeing.  It sounds like the filtering needs to be applied differently.  I moved the condition into the net responses/total surveys sent expression, so the query now looks like:

`select count(*) 'total surveys sent including out of office' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values' , (count(case when mailer.Complete =1 AND regcode >= 10000 then 1 end)- count(case when results.answer482 = 11760  AND regcode >= 10000 then 1 end))/count(*) 'net responses/total surveys sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2024-04-01 00:00:00' AND mailer.senddate <= '2024-04-30 23:00:00'`

Is this more in line with how it should work? I have pushed this update so you can test it.

cc: @ultimike

**Comment by thinkcollege** [comment]
This looks good @mgcobblestone  Thanks!
cc: @ultimike
