### ISSUE TITLE
Users with Job type "Both manager and employment consultant" not seeing Me and Team columns under Best Practices

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#129]
When a user with the role 'Survey participant' and Job type 'Both manager and employment consultant' (in the Survey participant profile') goes to the Best practices tab of the dashboard they don't see the Me and My Team columns.  They only see the All column.  I tested this on my local by switching a user between the job types Employment consultant and Both manager and consultant, and the problem occurred for the same user only when their job type was Both manager and consultant.
In the Activities tab the problem does not occur: the user sees all three columns.   The expected behavior is that a user with the Job type Both manager and employment consultant would see all three, Me My team, and All columns, since they fill out the survey and have individual results of their own

**Comment by mgcobblestone** [comment]
@thinkcollege  I have pushed an update to the best practices template that should address this.  You will need to flush caches in order to see the change.

cc: @ultimike

**Comment by thinkcollege** [comment]
Okay
