### ISSUE TITLE
State level response rates in the dashboard are high

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#130]
The state response rates in the es-coach.org dashboard look high compared to the provider, or team, rates.  One of our guys did some manual calculations and this is what he came up with:
 IL: 116/193 = 60% (dashboard shows 89.9%)
IN: 115/185 = 62% (dashboard shows 73.3%)
MD: 36/84 = 43% (dashboard shows 81.8%)
MN: 139/247 = 56% (dashboard shows 76%)
MO: 26/69 = 38% (dashboard shows 75%)
OH: 371/546 = 68% (dashboard shows 81.2%)
Could you look this over and see if you can detect any problems?
I attached the live site db to this issue.
[escoach_9_18.tar.gz](https://github.com/user-attachments/files/17045293/escoach_9_18.tar.gz)
cc: @ultimike

**Comment by ultimike** [comment]
@thinkcollege message received. I just chatted with Martin and he will be taking a look at this ASAP.

-mike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
Sorry for the delay, it's been a busy month!

I used this query for IL:  select count(*) from surveycampaign_mailer m  left join surveycampaign_results r ON (m.contactid = r.contact_id ) WHERE m.surveyid = 5420562 and m.senddate BETWEEN '2024-08-01 00:00:00' AND '2024-08-31 23:59:59' and r.state = 'IL';
and came up with total surveys of 129 which would support the 89% rate.  Where is the 193 number coming from?

Thanks.
cc: @ultimike

**Comment by thinkcollege** [comment]
I can look into that more, but the state response rates are significantly higher than team/provider rates.  A quick look shows that of the three providers in Illinois none has a response rate over 70%. (See attached download from the website, sorted by state.)  Can you compare how the provider response rate is calculated vs. the state-level rate?
[provider-data.csv](https://github.com/user-attachments/files/17138171/provider-data.csv)

**Comment by mgcobblestone** [comment]
@thinkcollege  The only difference in the queries is filtering on provider vs. state.  However, the provider filter is in the _mailer table while the state filter is on the _results table.  I think that probably accounts for the difference.  If I change the provider filter to use the results table also, the total records drops, which causes the response rate to increase.  I'm not sure what we can do about this since the state field does not exist in the _mailer table.  

I know we addressed a similar issue a while back but I'm having trouble remembering which ticket that was.  I'm thinking it was the regcode filtering but I'm not sure that is the same.  Does any of this point you in a direction as to what might need to be adjusted in the query? One option might be to create a providers table that maps providers to states and then join that with the _mailer table.

cc: @ultimike

**Comment by thinkcollege** [comment]
Could you try joining the two tables on the contactid (surveycampaign_mailer) and contact_id (surveycampaign_results)  fields, getting the state from the join, or eliminating the records that are not Complete in the mailer table?  Contactid is a unique id assigned by Alchemer to each survey sent. The contact_id will not appear in the results table if the survey is not Complete = 1 in the mailer table.  If that seems too much of a stretch we could creat the join table, as you suggested.

**Comment by mgcobblestone** [comment]
Hi @thinkcollege , the tables area already joined on contact ID.  I think you've pointed out the reason for the discrepancy - the  results table won't have a contact ID if Complete != 1.  

I'm thinking the provider to state mapping table might be our best option.

cc: @ultimike

**Comment by thinkcollege** [comment]
Interesting.  We currently pull the state from the user profile. Would it be useful to add the state as a field on the Provider taxonomy term? That wouldn't be too hard.  Would that solve the problem or would we still need to generate a separate table? 
cc: @ultimike

**Comment by mgcobblestone** [comment]
We could do that but it would be a little more complicated as we'd have to join the Drupal tables to locate the taxonomy record and then the corresponding field value from the new field.  We would also need to be sure that a taxonomy term exists for every provider - it looks like there are a handful where that is not currently the case.

**Comment by thinkcollege** [comment]
How do you want to proceed? We could create a table with two columns but how does it get updated?  A foreign key, but to what?  That is why I suggested attaching a state field to the Provider taxonomy.  If it would be simpler to have a stand-alone state/provider table it could be keyed to the Drupal tables.  Also, any provider that does not have a taxonomy entry we don't care about.  Anything that is current will have an entry.

**Comment by thinkcollege** [comment]
Could you just create a join table using a stored procedure?

**Comment by mgcobblestone** [comment]
A view will work:  create view provider_state_map AS select distinct provider, state FROM surveycampaign_results;

I have pushed an update that uses this view. You'll need to create the view on your end before using this.
I believe this will create the results you are expecting to see (it's now using September so I can't use the numbers you already provided).

**Comment by thinkcollege** [comment]
I created the view with your SQL query on my local and the rp-escoach.communityinclusion.org site (devel branch) and checked out the changes from the es_home branch to devel. I only saw one change in es_home, to the form--dashboard-form.html.twig file.  I also updated the surveycampaign_xxx tables from live on local and development site. But I don't see any changes in the state response rate. Attached is a dump of the surveycampaign tables.  It may be one or two users out of sync with the Drupal users on the live site, but it is giving me very close results to what is on live.
[surveycampaign_campaigns.zip](https://github.com/user-attachments/files/17211833/surveycampaign_campaigns.zip)

**Comment by mgcobblestone** [comment]
There should have been changes in ResponseRateQuery.php

**Comment by thinkcollege** [comment]
My bad, I didn't have the latest es_home.  Looking better now.

**Comment by thinkcollege** [comment]
Our data guys checked this out and it looks good.  Thanks
