### ISSUE TITLE
Questions about user/providers

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#14]
Paul,

@mgcobblestone and I were talking today about the "manager" role and its ability to limit the data displayed on the dashboard and it brought us to some interesting questions:

1. Will every authenticated user on the site with access to the Dashboard be either an admin or a user with the "manager" role? Based on the fact that there is a "My data" option, it seems like non-managers, non-admins will be able to access the Dashboard as well.
2. Will every user with or without the "manager" role belong to a provider?

Assuming that there are 3 kinds of users: 

- authenticated (non-manager, non-admin)
- manager
- admin

Does the role that each user has change the available options for "data frame"?

- My data (available to authenticated, manager, admin).
- My Team data (available to managers)
- All data (available to admins)

If this is correct, is there any point to showing admins the "My data" or "My team data" options? Do admins have their "own" data or belong to a team?

Similarly, do users with the "manager" role need to see the "My data" option?

thanks,  
-mike

**Comment by escoach** [comment]
I believe that my response to the Question #9 addressed this question? Or let me know.

**Comment by ultimike** [comment]
Closing in lieu of #9.
