### ISSUE TITLE
List of providers?

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#15]
Where does/will the list of providers come from? Is this something that we're going to populate on the fly based on data from the survey? 

Or, will providers be added manually by a site admin?

Once a provider is added, is there a plan to associate each site user with a provider? If not, is there any reason not to just add a user entity "provider" term reference field?

-mike

**Comment by thinkcollege** [comment]
The provider name is in the Provider taxonomy vocabulary.  When survey users register on the site they will have to choose a provider from the vocabulary.  That is a reference field in their user profile.  As you see that gets recorded in the provider field of the surveycampaign_results table.  There have been some changes to the site, including taxonomy and user roles.  I added a survey participant role.

**Comment by ultimike** [comment]
Ok, so a site administrator will manually add terms to the Provider role as necessary?

-mike

**Comment by thinkcollege** [comment]
For now, yes, the admins will add the Provider terms to maintain vocabulary control.  If this thing gets much bigger we may have to allow free entry of Provider terms, and figure out some way to avoid term creep.

**Comment by ultimike** [comment]
Understood - for the current project though, unless you tell us differently, we're going to assume that providers will be manually added by site admins.

thanks,  
-mike

**Comment by ultimike** [comment]
Paul - looking back at your comment from a couple of days ago:

> When survey users register on the site they will have to choose a provider from the vocabulary. 

Will new users need to be manually approved? If not, then won't anyone be able to register for the site and select a random provider and then be able to see data that they shouldn't have access to?

-mike

**Comment by thinkcollege** [comment]
I wanted self-registered users to be manually approved but Alberto doesn't want that and he and his team will keep an eye on that to weed out spam users.  They are starting out with a pilot with limited users.  We are not super concerned about people seeing the data, but they want to make sure no one is submitting bad data.  We will have to figure out something better down the road; I don't know what yet. I am pretty sure that Provider entity field was on the user profile entity on April 28.  It is being inserted in the surveycampaign_results table from that field.  Note: it is on the user profile called Survey participant.

**Comment by thinkcollege** [comment]
I just uploaded a current database, escoach_4_30_21.sql to our Teams project.  I am quite sure the provider field was there on the 28th in that other db download.  It is a profile field on the survey_participants profile.  If you look at the surveycampaign module, e.g., /modules/custom/surveycampaignsrc/SurveyUsersService.php you will see it being referenced to pull the field values for various purposes.

**Comment by ultimike** [comment]
Ah - on the profile entity - I wasn't looking there, I was looking directly on the user entity. I see it now on the DB from April 28.

-mike
