### ISSUE TITLE
How to query "surveycampaign_results" table for "My data"

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#16]
Paul,

This question might be for Alberto, but which field do we use to limit the `surveycampaign_results` table for a single user in order to generate the "My data" data?

Is it `contact_id`? If so, when a user is created on the Drupal site, will we need to somehow link their user account with the `contact_id` field? 

Or, (thinking out-loud here) maybe the `contact_id` field is the person who was contacted and not the person filling out the survey? 

Help! 

thanks,  
-mike

**Comment by thinkcollege** [comment]
You should be able to join the surveycampaign_results table to the surveycampaign_mailer table on contactid.  The contactid is unique to the person filling out the survey, and unique to the day's campaign.  That is a very solid identifier.  I uploaded the site database from today to our Teams project.  You and Martin are both admins on the live site too.

**Comment by thinkcollege** [comment]
The contact id is unique to an individual only for that day's survey and campaign (a campaign is the daily issuance of the survey).  The contact id for a given campaign is in both surveycampaign_results and surveycampaign_mailer.  The mailer table has phone number which is a unique identifier in each user's profile, so that could be used to hook into the user.

**Comment by thinkcollege** [comment]
Also, the surveycampaign_results table has the user email in it.  That is auto-inserted by my module from the user object into the survey as a hidden field.  I can't really think of a better way to identify a user.  Can you?

**Comment by ultimike** [comment]
@thinkcollege Cool - I was wondering if the `surveycampaign_results.email` field was going to work. Glad you were able to confirm.

So, when an authenticated user selects the "My data" option, we'll filter based on that user's email address. Therefore, we really don't need to use the `contact_id` for anything. 

Let me know if we're on the same page.

thanks,  
-mike

**Comment by thinkcollege** [comment]
Right, for your purposes the email address should do.  I am just being careful putting it in there. There will be a surprise request some day that requires it, I am quite sure.

**Comment by ultimike** [comment]
Roger that. 

thanks,  
-mike

**Comment by ultimike** [comment]
@mgcobblestone Summarizing this task: when we need to filter survey responses by user (for "My data"), the SQL `where` clause will use (pseudocode): `WHERE email = $user->getEmail()`

-mike

**Comment by thinkcollege** [comment]
That all looks good to me.
Paul

**Comment by ultimike** [comment]
I think we're done here - closing.
