### ISSUE TITLE
Design SQL queries to generate Example 2 from mockup ("Where summary")

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#17]
Building off of #8 and #11...

See the "Gitlab #17" tab of [the Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=2066763682).

![Screen Shot 2021-05-07 at 10 28 07 AM](https://user-images.githubusercontent.com/1727889/117464771-fc32cf00-af1e-11eb-8ea9-36f04437b260.png)

**Comment by escoach** [comment]
@ultimike I reviewed Gitlab#17. The math and data look correct to me.
I confirm that here we don't use the "Who else" stuff. 
As for your question about "...the mockup doesn't appear to reflect this..." I am not sure what you mean. The mockup Example #2 shows "my data" selected but then the mockup shows data for all three frames "All data", "My team data" and "My data". That is intended:

- users who enter data in the system can see all three data frames. 
- users who have not entered data in the system, but they are registered as part of a participating organization, will be able to see only "My team data" and "All data". They are managers.
- users who have not entered data in the system and are not members of a participating organization, wll be able to see only the "All" data frame.  They are the random visitor to the site.

Let me know if this is not what you were looking for.

**Comment by ultimike** [comment]
@escoach thanks.

Regarding the "mockup doesn't appear to reflect this", I was only referring to the fact that only one of the mockups show any data in the hrs/week "My team" or "My data" columns.

I understand completely the relationship between roles and visible data.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike Got it. You are right, a better mockup should have been completed with the data in all columns including the "My team" and "My data" columns. Thanks for noticing.

**Comment by ultimike** [comment]
@escoach I think we're done with this one, correct? Everything on the Google Sheet (Gitlab #17 tab) looks correct?

-mike

**Comment by escoach** [comment]
@ultimike yes, Gitlab#17 looks correct

**Comment by ultimike** [comment]
@escoach Circling back to this query, based on our discussion on #24. I've updated the sample query to include an optional "Who/else" (I'm using this abbreviation for "Who + Who Else") condition or a "Where" condition.

```
/* SQL queries for Gitlab #17 (Example 2 from mockups) */
/* answer483 is "What", answer482 is "Where" */
/* Outputs "Where summary" for one or more "What" selections, no "Who" selection, and "Where" = "Anyplace" */
SELECT count(*) AS TotalAll,
       sum(case when (answer482 = 11649) then 1 else 0 end) AS OfficeAll,
       sum(case when (answer482 = 11650) then 1 else 0 end) AS ResidenceAll,
       sum(case when (answer482 = 11651) then 1 else 0 end) AS BusinessAll,
       sum(case when (answer482 = 11652) then 1 else 0 end) AS CommunityAll,
       sum(case when (answer482 = 11653) then 1 else 0 end) AS VehicleAll,
       sum(case when (answer482 = 11753) then 1 else 0 end) AS OtherAll,
       sum(case when ((answer482 IS NOT NULL) AND provider = 'no provider') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer482 = 11649) AND provider = 'no provider') then 1 else 0 end) AS OfficeProvider,
       sum(case when ((answer482 = 11650) AND provider = 'no provider') then 1 else 0 end) AS ResidenceProvider,
       sum(case when ((answer482 = 11651) AND provider = 'no provider') then 1 else 0 end) AS BusinessProvider,
       sum(case when ((answer482 = 11652) AND provider = 'no provider') then 1 else 0 end) AS CommunityProvider,
       sum(case when ((answer482 = 11653) AND provider = 'no provider') then 1 else 0 end) AS VehicleProvider,
       sum(case when ((answer482 = 11753) AND provider = 'no provider') then 1 else 0 end) AS OtherProvider,
       sum(case when ((answer482 IS NOT NULL) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer482 = 11649) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS OfficeMe,
       sum(case when ((answer482 = 11650) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS RecidenceMe,
       sum(case when ((answer482 = 11641) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS BusinessMe,
       sum(case when ((answer482 = 11652) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS CommunityMe,
       sum(case when ((answer482 = 11653) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS VehicleMe,
       sum(case when ((answer482 = 11753) AND email = 'paul.foos@umb.edu') then 1 else 0 end) AS OtherMe
FROM surveycampaign_results
WHERE
/* What example - "Any supports AFTER hire" selected */
/* answer483 IN (11660); */
/* What example - "Any supports AFTER hire" selected" and "Any supports BEFORE hire" selected" selected */
answer483 IN (11660, 11661);
```

The modifications to this query are very similar (identical) to #11. Please review and let me know if you agree that all looks good.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike From what I understand, it looks good. Thanks.

**Comment by ultimike** [comment]
@mgcobblestone Working to validate the queries in the survey_dashboard module, I ran this case on my local as my personal username (so I have no "my data", and my provider is "Institute for Community Inclusion").

Options on the form I had selected are:

- Who: (nothing selected)
- Where: Any place
- What: Any supports AFTER hire
- Timeframe: Up-to-date (default value)

The /dashboard page returned null for all values, except for a TotalAll value of 0. 

On my local, using the SQL show above, the results are:

```
[
  {
    "TotalAll": 48,
    "OfficeAll": 17,
    "ResidenceAll": 3,
    "BusinessAll": 11,
    "CommunityAll": 8,
    "VehicleAll": 8,
    "OtherAll": 1,
    "TotalProvider": 4,
    "OfficeProvider": 2,
    "ResidenceProvider": 1,
    "BusinessProvider": 0,
    "CommunityProvider": 0,
    "VehicleProvider": 1,
    "OtherProvider": 0,
    "TotalMe": 0,
    "OfficeMe": 0,
    "RecidenceMe": 0,
    "BusinessMe": 0,
    "CommunityMe": 0,
    "VehicleMe": 0,
    "OtherMe": 0
  }
]```

**Comment by mgcobblestone** [comment]
@ultimike Fix is up in Devel.

**Comment by ultimike** [comment]
@mgcobblestone Looks good, but like #8, the results are also missing the `TotalMe` value.

**Comment by ultimike** [comment]
Winner winner chicken dinner - this one looks good-to-go now that we have the `TotalMe` value 😄 

-mike

**Comment by ultimike** [comment]
All done here. Closing.
