### ISSUE TITLE
June 9 steps to test Dashboard in devel environment

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#30]
Use the following steps to test the Dashboard in the devel environment:

- Pull code.
- Run `drush cr`
- Run `drush config-import` - this will override any configuration that exists in the devel environment that hasn't been exported. 
- Run `drush en -y survey_dashboard`. 
- Migrate term data using `drush mim escoach_dashboard_terms` (Mike). 
- Visit the Dashboard at `/dashboard`

**Comment by ultimike** [comment]
@thinkcollege Let me know which server I should do this on - I'm pretty sure not the live server...

thanks,  
-mike

**Comment by ultimike** [comment]
From Paul, via email: 

> The devel branch is running at http://sp-escoach.communityinclusion.org/  I updated the db and merged code from the rack branch.  Though now that I think about it, if you have been doing any work on devel you should force overwrite when you push to origin devel.  I have not been using this branch for development testing, for a few reasons, so go ahead and do what you like with it.

**Comment by ultimike** [comment]
Can I get ssh access to sp-escoach.communityinclusion.org?

**Comment by ultimike** [comment]
Also - can I run `drush config-import` on sp-escoach?

**Comment by thinkcollege** [comment]
I can let you in there if you give me your public key.  Drush is problematic.  I have several linux users on that server and not all of them can use Drush.  Tried installing it with Composer but a lot of conflicts.  The server is really just a deployment not a build.  Can you do the config update through the Drupal interface?

**Comment by ultimike** [comment]
I can try. I'll also have to run the migration through the UI.

For some reason, I can't Rebuild Caches on the site via the UI - any ideas?

-mike

**Comment by thinkcollege** [comment]
It's working now.  There is a permissions issue with the Google Tag module which necessitates a manual setting of permissions on it's files directory to the apache owner.

**Comment by ultimike** [comment]
@thinkcollege I fear that we have some configuration issues...

I am unable to import configuration on the dev site - the error is:

`The configuration cannot be imported because it failed validation for the following reasons:
Configuration ahead_boot4.settings depends on the ahead_boot4 extension that will not be installed after import.`

I'm guessing that someone enabled the "ahead_boot4" extension at some point but didn't export the config and commit it to Git after they did?

Any idea?

-mike

**Comment by thinkcollege** [comment]
I had problems with that myself.  It is an artifact from a previous build.  I removed that ahead_boot4 file from the config/sync   Try again.

**Comment by ultimike** [comment]
I lied - I was able to get it working through the UI with a few minor changes :)

**Comment by ultimike** [comment]
@thinkcollege Does the sp-escoach environment automatically pull in commits from the `devel` branch or is that a manual process?

If it is manual, I've attached my public key  below...

-mike

ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3Buacw3VGlKSUh8lD0d4mK1tuubUjBU0hJvxhC23LYbDgIln0aGuTjs0VhPJcHe3nP4PKRfqorE2pbFtlN5EzfRkm3H0us83+GvYABokGl0tKxbhlGJmSLf6MiVswa1UPpHMOHTSoVmACsryi8dDAajkeBlFbXPnM14/a/WNXiTkbxouSJ9U4Ve8SQ8YkwRy/dWsMVxQ0kC4+zGTU2QKmJiqccZSweS1rjGL/o8Qp4/fnXglVei/5dMrnMTHWc28n4PNYvYLMyfLieAUJ1ATy7HrcujqPEKkBbTKrnOJd6APH/NDm0BATLU+CB2ggjntcfsKDV1gnL9TIXME5tYvEw== michael@anelloconsulting.com

**Comment by thinkcollege** [comment]
I just did a push to devel and it successfully deployed.  Hope I didn't mess anything up.  Maybe you should push again.

**Comment by thinkcollege** [comment]
And force if you have to.  This site hasn't been used in a while

**Comment by ultimike** [comment]
I just tried to pull the `devel` branch - it threw a code conflict in TwilioCoachService.php

I'm hoping that the custom modules that @mgcobblestone and I have been working on lost some stuff (I have them backed up just in case), but it looks like at least my most recent commit is gone.

Before I do anything else, can you send me the latest version of TwilioCoachService.php? 

Should we continue using the `devel` branch? Is it going to be possible to merge it into `master` cleanly?

-mike

**Comment by thinkcollege** [comment]
As I said, I may have overridden your last push.  I forgot that anyone 
else was working on this branch.  Go ahead and force push to devel and 
overwrite anything there.  The latest version of TwilioCoachService.php 
is on the rack branch.

On 6/10/21 12:34 PM, Michael Anello wrote:
> EXTERNAL SENDER
>
> I just tried to pull the |devel| branch - it threw a code conflict in 
> TwilioCoachService.php
>
> I'm hoping that the custom modules that @mgcobblestone 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmgcobblestone&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702128814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1ZpXOAgv%2F5rOugenESZAgNswBAtDSfRuAHCGqE2Wij4%3D&reserved=0> 
> and I have been working on lost some stuff (I have them backed up just 
> in case), but it looks like at least my most recent commit is gone.
>
> Before I do anything else, can you send me the latest version of 
> TwilioCoachService.php?
>
> Should we continue using the |devel| branch? Is it going to be 
> possible to merge it into |master| cleanly?
>
> -mike
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F30%23issuecomment-858771279&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702138809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=07sO2l5gLhewmOTmjeTSZEJbA9zr3ylKCxl2yFANSkQ%3D&reserved=0>, 
> or unsubscribe 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANZAVEIUYGZ7SIYQIYP5TLTSDSRBANCNFSM46MRQSEQ&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702138809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bv17aXakKeORHHFlGWQhADzUJnZZ73pqlNtj9vS2uyI%3D&reserved=0>.
>
-- 
Paul Foos
Web Developer
Institute for Community Inclusion
University of Massachusetts Boston
100 Morrissey Boulevard
Boston, Massachusetts  02125
Office: (617) 287-4359
Cell phone: (508) 521-0719

**Comment by thinkcollege** [comment]
Please consider the devel branch and the demo site your own.  I just 
wanted to make sure things were working there.  I am pushing latest 
working development to the rack branch, and don't pay much attention to 
master

On 6/10/21 12:34 PM, Michael Anello wrote:
> EXTERNAL SENDER
>
> I just tried to pull the |devel| branch - it threw a code conflict in 
> TwilioCoachService.php
>
> I'm hoping that the custom modules that @mgcobblestone 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmgcobblestone&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702128814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1ZpXOAgv%2F5rOugenESZAgNswBAtDSfRuAHCGqE2Wij4%3D&reserved=0> 
> and I have been working on lost some stuff (I have them backed up just 
> in case), but it looks like at least my most recent commit is gone.
>
> Before I do anything else, can you send me the latest version of 
> TwilioCoachService.php?
>
> Should we continue using the |devel| branch? Is it going to be 
> possible to merge it into |master| cleanly?
>
> -mike
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F30%23issuecomment-858771279&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702138809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=07sO2l5gLhewmOTmjeTSZEJbA9zr3ylKCxl2yFANSkQ%3D&reserved=0>, 
> or unsubscribe 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANZAVEIUYGZ7SIYQIYP5TLTSDSRBANCNFSM46MRQSEQ&data=04%7C01%7Cpaul.foos%40umb.edu%7C51a8ed7d993d4d9da86c08d92c2d9ca7%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637589396702138809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bv17aXakKeORHHFlGWQhADzUJnZZ73pqlNtj9vS2uyI%3D&reserved=0>.
>
-- 
Paul Foos
Web Developer
Institute for Community Inclusion
University of Massachusetts Boston
100 Morrissey Boulevard
Boston, Massachusetts  02125
Office: (617) 287-4359
Cell phone: (508) 521-0719

**Comment by ultimike** [comment]
Understood - but as some point we're going to have to merge `devel` into `master`, correct? Seems like that may be problematic at this point...

-mike

**Comment by thinkcollege** [comment]
master is just a not very up-to-date version of rack.  Yes, we will have to merge into rack.  I don't think it will be hard to resolve conflicts.  I don't think we are working on many of the same files.  The files on rack have the latest working version of my changes.

**Comment by ultimike** [comment]
Ok - so we should work to keep `devel` up-to-date with`rack`, then correct?

I just pushed our changes to `devel` - I'm still not clear if it will automatically deploy to the sp-escoach environment...

-mike

**Comment by thinkcollege** [comment]
@ultimike Yes I see your deployment went through without errors. Thanks for your patience.  I have been working alone on this one for a while, and forgot to play nice with others.

**Comment by ultimike** [comment]
@thinkcollege Good morning - we've made some pushes to the `devel` branch over the past week but haven't been doing anything with http://sp-escoach.communityinclusion.org (yet). I just went there and am unable to do much anything (rebuild caches, view the /admin/modules page) due to a `The website encountered an unexpected error. Please try again later.` error.

Help?

thanks,  
-mike

**Comment by thinkcollege** [comment]
There was a security update to the VBO module that needed a drush updb.  I did that and it is working now.  The problem on this creaky development server is because there are several linux users drush never got properly set up for the owner of this directory.  You can run drush as root on this directory.  If you want me to send you the root pwd by secure means I am fine doing that.

**Comment by ultimike** [comment]
I'm michael@anelloconsulting.com on the Signal app - feel free to share the credentials with me there.

If you'd like, you can check out the initial [Dashboard](http://sp-escoach.communityinclusion.org/dashboard) results. At this point in time, we are only outputting the data table (not the graphs), and not all use cases are working yet. We believe that the data similar to #8, #11, and #17 is working, but the "Selected activities" (#19) is still buggy. We haven't worked on the output for the monthly nor quarterly trends yet (although we do have the queries figured out). I'm sure there are other bugs we haven't discovered yet.

Martin is on vacation this week, so I'm planning on cleaning up the UI a bit (we've done **very** little of that so far). 

-mike

**Comment by thinkcollege** [comment]
@ultimike I sent it via our Teams channel

**Comment by thinkcollege** [comment]
@ultimike   Have you had any luck getting into the devel server? I have not found any issues, other than what I sent you in Teams about setting up an ssh config file.

**Comment by ultimike** [comment]
Still no luck.

`$ ssh ici@162.243.15.189 -p64656
ici@162.243.15.189: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).`

I'm not terribly concerned about it, as I don't need it all that often.

-mike

**Comment by thinkcollege** [comment]
You could try one more time.  I re-entered your public key.  There may have been a problem with the way it was entered in the authorized_keys file

**Comment by thinkcollege** [comment]
Sounds like you got in.  when I copied your public key there was no space between the key and your email address.  That was the problem if it works now.  Here is the path to the web root:
/home/ici/escoach.communityinclusion.org/escoach/web

**Comment by ultimike** [comment]
Roger that. 

So I should be able to ssh in, go to the directory you listed above, and do a `sudo drush whatever` and have it work, correct?

Unfortunately, that's not working - it doesn't like the password...

-mike

**Comment by thinkcollege** [comment]
You mean you did "su" and the root password didn't work?

**Comment by thinkcollege** [comment]
No not sudo, just su to root and execute drush

**Comment by ultimike** [comment]
Heh - my bad. I was doing `sudo drush whatever`, but I need to do `su`, enter the password, then `drush whatever` - I'm all set now (finally).

thanks,
-mike

**Comment by thinkcollege** [comment]
Easy peasy
