### ISSUE TITLE
Provider profile - "is_default"?

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#33]
@thinkcollege I noticed that a single user can have multiple `survey_participants` profiles, but it appears that only one can have the `is_default` property set to TRUE (`1`). 

I'm thinking that when we are looking up a user's provider, we need to filter by `is_default = 1` - do you agree?

thanks,  
-mike

**Comment by ultimike** [comment]
@mgcobblestone If @thinkcollege agrees with me above, then the change we'll need to make is in `QueryBuilder::process`:

```
    $profiles = $this->entityTypeManager->getStorage('profile')
      ->loadByProperties([
        'uid' => $this->currentUser->id(),
        'type' => 'survey_participants',
      ]);
```

to

```
    $profiles = $this->entityTypeManager->getStorage('profile')
      ->loadByProperties([
        'uid' => $this->currentUser->id(),
        'type' => 'survey_participants',
        'is_default' => 1,
      ]);
```

-mike

**Comment by thinkcollege** [comment]
That is good with me.  I am not sure how you would even create a second profile on a user, but I see that one of my test users did have two profiles.  Weird.

**Comment by ultimike** [comment]
@mgcobblestone Do you mind making this small change next time you're in the code?

thanks,  
-mike

**Comment by ultimike** [comment]
@mgcobblestone Looks like this is done - if you agree, please close.

thanks,  
-mike
