### ISSUE TITLE
Minor hh:mm display issue in Dashboard table

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#35]
In some cases, values like `23:60` are being output (instead of `24:00`).  I suspect a rounding error.

Steps to reproduce:

- Go to /dashboard
- Enter the following:
  - Who: Any
  - Where: -
  - What: "Addressing a workplace challenge"
- Click "Submit"

![Screen Shot 2021-06-18 at 12 02 39 PM](https://user-images.githubusercontent.com/1727889/122588478-26eb6980-d02d-11eb-9baf-345f6d72c639.png)

-mike

**Comment by mgcobblestone** [comment]
@ultimike I've pushed a fix for this.

**Comment by ultimike** [comment]
Looks fixed to me 😄 

Closing.

-mike
