### ISSUE TITLE
"who summary" when outputting quarterly or monthly trend

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#38]
@escoach We're trying to figure out exactly what data to display on the table when the following options are selected ("who summary"):

- Who: Any interactions
- Where: (nothing selected)
- What: "Any supports AFTER hire" selected.
- Timeframe: Quarterly trends

When we're looking at up-to-date data, the query returns a single row with values for each of the possible "Who" options as well as the total.

When we run the query for the quarterly trends, we end up with 4 rows of data (one row per quarter) and all the same fields.

How should this data be output in a table? The screenshot provided (see #20) is a very simple example and isn't providing us much guidance here. Can you provide us some additional screenshots using real data that we can go on?

Based on where we land on this, we'll do something similar for the other scenarios.  

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike thank you for the opportunity to explain these details. 

It's only in the "Up to date" visual that we go granular to show how that figure is spread across the "Who", when users select a "what" &"any interactions". The same is true for the combination of a "what" & "Any place".
In your example, the table should show the total of "Any supports AFTER hire" organized in four rows (one per quarter) and six columns as usual (All, My team, me per day, and then per week).

Another example: A user selects "Any supports AFTER hire" & ["A person I support"]. Then the table would visualize the number of instances (well, average hours) when the occurrence of these two events is true each quarter (four rows) and six columns (All, My team, me per day, and then per week). 

If your team moved forward with adding a multi-select for the "who" and "where", here is another example (I am using this example just for the sake of illustrating the reasoning. We are fine with single-selection + new combined items for "who" and "where"):
A user selects "Any supports AFTER hire" & ["A person I support" & "A disability professional" & "A family member"]. Then the table would visualize the number of instances (well, hours) when the occurrence of these 3 events is true. The table would still show only four rows (one per quarter) and six columns as described above.

Does this make sense? I have no idea how much this approach makes things more or less complicated on your end. If it complicates things, let's talk. We would like to find the right balance between developing a useful dashboard but that is realistic in terms of development efforts.

**Comment by escoach** [comment]
@ultimike just a heads up that tomorrow (Tuesday 06/29) and 06/30 I am out of town. I will keep an eye on emails, but my responses might be delayed a little.

**Comment by ultimike** [comment]
@escoach I think you're saying that all quarterly and monthly trends data tables will look the same:

- 7 columns: 
  - Month name or quarter number
  - All hours/day
  - My team hours/day
  - Me hours/day
  - All hours/week
  - My team hours/week
  - Me hours/week
- 4 rows (Quarterly)
  - 1
  - 2
  - 3
  - 4
12 rows (Monthly)
 - Jan
 - Feb
 - Mar
 - Apr
 - May
 - Jun
 - Jul
 - Aug
 - Sep
 - Oct
 - Nov
 - Dec

@mgcobblestone If/when @escoach confirms this, I'll go ahead and post a bunch of sample queries I've developed for various combinations of what/who/where and monthly/quarterly.

-mike

**Comment by escoach** [comment]
Correct.
Down the road it would be useful to know how practices changed over 2-3 years. Would it  make sense to create 12 rows for the Quarterly data so it can accommodate three years? This way the monthly and quarterly tables and charts have the same size. The difference will be that the quarterly table and chart will be filled only after three years of data collection.
Not a big deal if this complicates things. For now your description works.
Thanks

**Comment by ultimike** [comment]
@escoach Based on the logic we're discussing, does it make any sense to allow a trends query if no "what" option is selected?

-mike

**Comment by ultimike** [comment]
For @mgcobblestone 

```
/* SQL queries for Gitlab #20 */
/* answer483 = 11659 is "What = Finding, securing jobs" */
/* answer481 = 11641 is "Who = Family, friends...", answer590 = 12119 is "Who else = Family, friends..." */
/* answer482 = 11651 is "Where = At a business... " */
/* THIS ONE ISN'T NECESSARY AS WE'RE CURRENTLY NOT ALLOWING A WHO AND A WHERE TO BE SELECTED AT THE SAME TIME. */
SELECT MONTH(date_submitted),
       count(*) AS TotalAll,
       sum(case when (answer483 = 11659) then 1 else 0 end) AS SelectedAll,
       sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer483 = 11659) AND (provider = 'Institute for Community Inclusion')) then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'michael@anellconsulting.com') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer483 = 11659) AND (email = 'michael@anellconsulting.com')) then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL
  AND ((answer481 IN (11641)) AND (answer590 IN (12119))) /* Who = Family, friends, ... */
  AND (answer482 IN (11651)) /* Where = At a business... */
  AND date_submitted >= DATE_SUB(NOW(), INTERVAL 1 YEAR)
GROUP BY MONTH(date_submitted);

/* Example: Monthly trends, "What" is "Getting to know a job seeker", "Where" is "At the residence of a person I support", "Who" is not selected. */
SELECT MONTH(date_submitted),
       count(*) AS TotalAll,
       sum(case when (answer483 IN (11658)) then 1 else 0 end) AS SelectedAll,
       sum(case when (provider = 'no provider') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer483 IN (11658)) AND (provider = 'no provider')) then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'paul.foos@umb.edu') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer483 IN (11658)) AND (email = 'paul.foos@umb.edu')) then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL
  AND answer482 IN (11650) /* Where = At the residence of a person I support. */
  AND date_submitted >= DATE_SUB(NOW(), INTERVAL 1 YEAR)
GROUP BY MONTH(date_submitted);
/* 56 - all monthly, 55 - last year monthly, 56 - all, 55 - last year */

/* Example: Quarterly trends, "What" is "Getting to know a job seeker", "Where" is "At the residence of a person I support", "Who" is not selected. */
SELECT QUARTER(date_submitted),
       count(*) AS TotalAll,
       sum(case when (answer483 IN (11658)) then 1 else 0 end) AS SelectedAll,
       sum(case when (provider = 'no provider') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer483 IN (11658)) AND (provider = 'no provider')) then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'paul.foos@umb.edu') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer483 IN (11658)) AND (email = 'paul.foos@umb.edu')) then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL
  AND answer482 IN (11650) /* Where = At the residence of a person I support. */
  AND date_submitted >= DATE_SUB(NOW(), INTERVAL 1 YEAR)
GROUP BY QUARTER(date_submitted);
/* 56 - all monthly, 55 - last year monthly, 56 - all, 55 - last year */

/* Example: Quarterly trends, "Who" is "Any interactions", "What" is "Any supports AFTER hire", "Where" is not selected */
SELECT QUARTER(date_submitted),
       count(*) AS TotalAll,
       sum(case when (answer483 IN (11660)) then 1 else 0 end) AS SelectedAll,
       sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer483 IN (11660)) AND (provider = 'Institute for Community Inclusion')) then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'michael@anelloconsulting.com') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer483 IN (11660)) AND (email = 'michael@anelloconsulting.com')) then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL
  AND ((answer481 IS NOT NULL) AND (answer590 IS NOT NULL)) /* Who = Any interactions */
  AND date_submitted >= DATE_SUB(NOW(), INTERVAL 1 YEAR)
GROUP BY QUARTER(date_submitted);
```

**Comment by ultimike** [comment]
@mgcobblestone Ok - I think this is working. 

I tested both monthly and quarterly for both my account and Paul’s and compared the results against my manual queries and the [Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit?ts=60dc9396#gid=1562837701). 

-mike

**Comment by escoach** [comment]
I agree that if no “what” is selected, then there is no meaning in a query based on either “who” or “where”. In other words, from a user perspective, it does not add value to know “who” the interaction was with or “where” the activity took place without knowing “what” was the activity performed.

________________________________

**Comment by ultimike** [comment]
@escoach Understood.

@mgcobblestone Sounds like we need to have some validation to ensure a "what" is selected when either "Monthly" or "Quarterly" trends are selected, know what I mean?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike I have added JS validation for the Trends timeframe options.

**Comment by ultimike** [comment]
@mgcobblestone Looks to be working for me 🎈 

@mgcobblestone I think we're ready for testing for this one, correct?

-mike

**Comment by mgcobblestone** [comment]
@ultimike correctomundo
