### ISSUE TITLE
Who=null, Where=null, What is not null - show "selected activities" summary

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#41]
@mgcobblestone As we just discussed on Slack, if (("Who" = null) AND ("Where" = null) AND ("What" IS NOT null)), then display "Selected activities" (similar to #19).

Currently, the "What" summary is displayed when Who/Where are both null, regardless of the "What" selected.

Let me know if there's any oddness with the query.

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Update is up.

**Comment by ultimike** [comment]
Roger that - thanks. So far, so good. 

-mike
