### ISSUE TITLE
Bug in "selected activities" query

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#42]
@mgcobblestone I found a bug related to the who/who-else stuff.

From the dashboard, select:

- Who = A person I support
- What = Any supports after hire

Take a look at the query - it is missing the "Who else" stuff. Something like: `answer590 in (12118)` in the `sum` SQL expressions.

-mike

**Comment by mgcobblestone** [comment]
@ultimike This is fixed.

**Comment by ultimike** [comment]
Looks good. Closing 😄
