### ISSUE TITLE
Updated "selected activities" query and data table validation

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#43]
@escoach As we discussed on Zoom, I've modified the "selected activities" query and created some data tables in the [Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=760518312) for your review.

Please take a look at the "Selected activities (1 query)" tab on the Google Sheet. Here you'll find samples of the only three scenarios where the "selected activities" summary should be displayed:

1. Who has a single selection (not "Any interaction"), What has one or more selections.
2. Where has a single selection (not "Anyplace"), What has one or more selections.
3. Neither Who nor Where have a selection, What has one or more selections.

Please review both the query results for each case as well as the calculations for the data table and let me know if we're on the right track.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike I did not see the raw data in your google sheet. Can you share the raw data you are using? Or I can ask @thinkcollege?
I am using filename "surveycampaign_results.xlsx" in Teams, but it has only 361 total rows whereas your raw data has 391 total rows.

**Comment by ultimike** [comment]
I've attached a .csv export of the table from my database, but it doesn't have a header row - hopefully this isn't an issue...

thanks,  
-mike

[db_surveycampaign_results.csv](https://github.com/communityinclusion/escoach/files/7009374/db_surveycampaign_results.csv)

**Comment by escoach** [comment]
@ultimike I did all the calculations for those three scenarios and my results coincide with your results. The "Total N" (Denominator) and the small n (numerators) match. The formula you used is correct. This looks good to go.

**Comment by ultimike** [comment]
Can you think of any other potential scenarios where we would be generating
the "selected activities" summary? I really want to make sure we don't have
any holes in our logic.

**Comment by escoach** [comment]
I can run a few scenarios and share what I get for you to double-check. I can do that tomorrow late morning or early afternoon. Would that work?

**Comment by ultimike** [comment]
Sounds like a plan.

Mike

**Comment by escoach** [comment]
@ultimike take a look at these 4 scenarios. They are the 4 Examples that we shared at the onset of the project (Filename: Es_coach_dashboard_mockup.docx"): https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit?usp=sharing

**Comment by ultimike** [comment]
@escoach - I went ahead and manually generated the same tables as you did in your Google Sheet. Summarizing my comparisons:

- Example 1 - some differences I believe due to Who/Who-Else and a typo on your sheet 😄 - full info in #45 
- Example 2 - no differences 🎉 
- Example 3 -  no differences 🎉 
- Example 4 - no differences 🎉 

If you agree, let's close this task and focus on #45 

thanks,  
-mike

**Comment by ultimike** [comment]
Closing this task.
