### ISSUE TITLE
Updated "where summary" query and data table validation

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#44]
@escoach As we discussed on Zoom, I've modified the "where summary" query and created a data table in the [Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1457665355) for your review.

Please take a look at the "Where summary (1 query)" tab on the Google Sheet. Here you'll find samples of one possible scenario .

Please review both the query result as well as the calculations for the data table and let me know if we're on the right track.

thanks,
-mike

**Comment by escoach** [comment]
@ultimike This looks good too pending the "235" (row 6) and "245" (row 9) labels in the table. I am not sure what they are and I ignored them. But I did all the calculations for the other standard labels for the "Where" summary and got the same results that you showed in your table. 
The n (numerator) at the bottom of the table is correct.

**Comment by ultimike** [comment]
@escoach Heh - the `235` and `245` are our compound fields ("answer 2 + 3 + 5" and "answer 2 + 4 + 5")...

-mike
