### ISSUE TITLE
Refactoring of "Selected activities" summary

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#46]
@mgcobblestone While Alberto and I work out the final details of #45, I think we have enough solid results for you to get going on the refactoring of the "Who summary", "Where summary", and "Selected activities" summaries. The three changes below need to be applied to all three of these summary queries and data tables.

The short version of the biggest change is this: we need to move most of the `WHERE` condition into the various `sum()` expressions. 

We also need to change the way we calculate the "Total respondents" values displayed in the data table (as will the label as Alberto, Paul, and I agree that the name isn't accurate). For now, let's change the label to just "n", please.

In addition, there are some small tweaks to the 3 "Total" expressions, but all minor.

Details on the three changes follow.

## Moving `WHERE` conditions

We are currently doing this:

```
SELECT
       count(*) AS TotalAll,
       sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) then 1 else 0 end) AS SelectedAll,
       sum(case when (((answer481 IS NOT NULL) OR (answer590 IS NOT NULL)) AND provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
       sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) AND provider = 'Institute for Community Inclusion' then 1 else 0 end) AS SelectedProvider,
       sum(case when (((answer481 IS NOT NULL) OR (answer590 IS NOT NULL)) AND email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe,
       sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) AND email = 'alberto.migliore@umb.edu' then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer540 IN (11859);
```

Note the `answer540 IN (11859)` bit in the `WHERE`. We need to change it to this:

```
SELECT
    count(*) AS TotalAll,
    sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) AND (answer540 IN (11859)) then 1 else 0 end) AS SelectedAll,
    sum(case when (((answer481 IS NOT NULL) OR (answer590 IS NOT NULL)) AND provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
    sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) AND (answer540 IN (11859)) AND provider = 'Institute for Community Inclusion' then 1 else 0 end) AS SelectedProvider,
    sum(case when (((answer481 IS NOT NULL) OR (answer590 IS NOT NULL)) AND email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe,
    sum(case when ((answer481 in (11640)) OR (answer590 in (12118))) AND (answer540 IN (11859)) AND email = 'alberto.migliore@umb.edu' then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL;
```

Note that the `answer540 in (11859)` stuff is now in the relevant `sum()` expressions. Also, the `WHERE` can simply always be `answer483 IS NOT NULL`.

## "Total Respondents" ("n") calculation 

While we are still going to get the `TotalAll`, `TotalProvider`, and `TotalMe` values from the query, we are not going to display these. Those values are to be used for the hrs/day calculation only. For the "n" row, we need to sum the individual values returned for each expression. Rather than me trying to explain it, I think it is easiest to understand by looking at the [Google Sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=760518312) on any of the "* (1 query)" tabs. 

Obviously, do not include the compound fields in the sums.

**Update - August 22** - we can either add up the columns, or we can use the new expressions I proposed in #48. The new expressions are required for the "Who summary", but can be applied to all the queries if it is easier for you.

## "Total*" query expressions

For each of the TotalAll, TotalProvider, and TotalMe expressions, we can simplify things 🎉 with the following:

```
    count(*) AS TotalAll,
    sum(case when (email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe,
    sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
```

I'm attaching a document with a bunch of example (and tested) queries that may help you as you proceed with this task.

[escoach-sql-aug-19.sql.zip](https://github.com/communityinclusion/escoach/files/7018155/escoach-sql-aug-19.sql.zip)

## "Who summary" issues

Alberto and I are still trying to figure out some discrepancies with the "Who summary" having to do with Who/Who-else stuff. I hope to have resolution on that (and necessary changes) by the end of the day tomorrow.

**Comment by mgcobblestone** [comment]
@ultimike The basic changes here are in place for Selected Activities.  Would you like to take a look before I move on to Who/Where?

**Comment by ultimike** [comment]
@mgcobblestone Looks like the "What" arguments are missing.

Running the case of the following on my local /dashboard page:

- Who = A person I support
- Where = null
- What = Addressing a workplace challenge

The "debug" output query is (with arguments manually replaced by me):

```
SELECT
       count(*) AS TotalAll,
       sum(case when ((answer481 in (11640) ) OR (answer590 in (12118) )) AND (answer540 IN ()) then 1 else 0 end) AS SelectedAll,
       sum(case when ((answer481 in (11640) ) OR (answer590 in (12118) )) AND email = 'alberto.migliore@umb.edu' AND (answer540 IN ()) then 1 else 0 end) AS SelectedMe,
       sum(case when ((answer481 in (11640) ) OR (answer590 in (12118) )) AND provider = 'Institute for Community Inclusion' AND (answer540 IN ()) then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe, sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider
FROM surveycampaign_results
WHERE answer483 IS NOT NULL;
```

Note that the `answer540` arguments (`:WhatAll0`, `:WhatMe0`, `:WhatProvider0`) are all blank 😢 (it should be `answer540 IN (11859)`)

That being said, the query changes look correct other than the missing argument values.

But, please replace the "Total" values in the "N" row with the "Selected" values from the query, know what I mean?

thanks,  
-mike

-mike

**Comment by mgcobblestone** [comment]
@ultimike Fix is in place for missing ":what" placeholders

**Comment by ultimike** [comment]
Looks better - some of my tests are returning exactly what they should (with the "selected activities" summary).  Here's some that aren't:

- Who=null
- Where=null AND 
- What=(Getting to know a job seeker)Observing a job seeker, Participating, Informational interviews

On my local, this is returning all zeros in the "Selected activities" row of the table. Here's what it should be returning:

![Screen Shot 2021-08-24 at 3 36 33 PM](https://user-images.githubusercontent.com/1727889/130626622-3142270a-9ad9-4f95-a55e-26fe7de2eec1.png)

Looking at the query, it appears that `answer537` appears twice in each expression.

Similarly, the following case returns all zeros in the same row:

- Who=null
- Where=null
- What=“Getting to know a job seeker” OR “Finding, securing jobs” OR “Other supports BEFORE hire” 

I didn't have a chance to look into this one further. 

Here's one more that involves multiple "what"s that is returning incorrect results:

- Who = Families, Friends... OR with Someone from a business
- Where = null
- What = "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation" 

Results should be:  
![Screen Shot 2021-08-24 at 3 44 54 PM](https://user-images.githubusercontent.com/1727889/130627752-bc827d62-619d-457e-8b4b-890ba24c139b.png)

Digging into this last one a bit, it looks like the query is correct, so I think maybe the calculation in the table is incorrect? 

-mike

**Comment by mgcobblestone** [comment]
@ultimike I have eliminated the multiple "whats", but haven't looked at the calculation yet.

**Comment by ultimike** [comment]
@mgcobblestone Looking again at this case:

- Who=null
- Where=null AND
- What=(Getting to know a job seeker)Observing a job seeker, Participating, Informational interviews

The query should look like: 

```
SELECT
    count(*) AS TotalAll,
    sum(case when (answer537 IN (11838,11899,12115)) then 1 else 0 end) AS SelectedAll,
    sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider,
    sum(case when ((answer537 IN (11838,11899,12115)) AND provider = 'Institute for Community Inclusion') then 1 else 0 end) AS SelectedProvider,
    sum(case when (email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe,
    sum(case when ((answer537 IN (11838,11899,12115))  AND email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS SelectedMe
FROM surveycampaign_results
WHERE answer483 IS NOT NULL;
```

But, on the dashboard, we're missing 2 of the 3 "what" values in the query:

```
SELECT
       count(*) AS TotalAll,
       sum(case when ((answer537 in (11899) )) then 1 else 0 end) AS SelectedAll,
       sum(case when ((answer537 in (11899) )) AND email = 'alberto.migliore@umb.edu' then 1 else 0 end) AS SelectedMe,
       sum(case when ((answer537 in (11899) )) AND provider = 'Institute for Community Inclusion' then 1 else 0 end) AS SelectedProvider,
       sum(case when (email = 'alberto.migliore@umb.edu') then 1 else 0 end) AS TotalMe,
       sum(case when (provider = 'Institute for Community Inclusion') then 1 else 0 end) AS TotalProvider
FROM surveycampaign_results
WHERE answer483 IS NOT NULL;
```

I find this odd because the third example from yesterday also has multiple "what" values and that query is still returning correctly on the dashboard.

- Who = Families, Friends... OR with Someone from a business
- Where = null
- What = "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation"

Taking a look at the second example from yesterday (the one I didn't have a chance to dig into):

- Who=null
- Where=null
- What=“Getting to know a job seeker” OR “Finding, securing jobs” OR “Other supports BEFORE hire”

This one is like the first example in this comment - we're missing 2 of the 3 "what" values from the /dashboard query.

Also - let's keep this task focused on the "selected activities" table/query. I'll open new tasks for updating the "who summary" and "where summary" when we're done here.

-mike

**Comment by mgcobblestone** [comment]
@ultimike Fix in place for missing "what" values

**Comment by ultimike** [comment]
@mgcobblestone I had some time this morning, so I dug into the code 😱 

But, I think I fixed this issue - see my commit `e4ccbe51eaf882c` and feel free to refactor if it doesn't match your coding style (or have a better way of doing it).

Regardless, now all of my "selected activities" summary tests now match my manual queries and data tables in my Google Sheet! 

@escoach Please take a look and let me know what you think.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike I am not sure what was exactly the question. But if it is whether the dashboard matches your Google sheet and my Google sheet, unfortunately, it does not yet. Let me know if you meant something else.
I am looking at Example 2:

**Example 2**
Who = Families, Friends... OR with Someone from a business
Where = null
What = "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation"

Your [Google sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=760518312) shows
All=0:19, n=16
Team=0:21, n=3
Me=0:21, n=6
These numbers match my [Google sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=34647741) (Tab Aug22, Table 8)

The Dashboard shows:
All=0:17, n=13
Team=0:00, n=0
Me=0:22, n=5
![image](https://user-images.githubusercontent.com/83360935/131251546-34b8f828-6068-4171-a29c-4c6e088c65f2.png)

**Comment by ultimike** [comment]
@escoach Something odd is going on with this as well as with #51, #52, and #54. I think it is a data issue - some difference between the data on the sp-escoach site and the data I have on my local (and that I shared with you a couple of weeks ago). Perhaps the database on sp-escoach was reverted to a previous version with older data (@thinkcollege?) If not, then I'd like to provide @thinkcollege with a copy of my local `surveycampaign_results` table (the same one you have) to import into the sp-escoach site so that we are sure to be using the same data for these tests everywhere. 

In order to compare apples-to-apples between my local and the sp-escoach site, I had to login to the sp-escoach site using your account. I changed your password to `alberto.migliore`.

I then used the "debug" functionality to compare the query for this case on sp-escoach with the query for this case on my local. **The queries are identical.** 

If the queries are the same, then the only other thing that can cause this issue is data. 

I'm hesitant to do anything else on this or  #51, #52, or #54 until we hear from @thinkcollege on this data front.

thanks,  
-mike

**Comment by thinkcollege** [comment]
Hi Mike,

Go ahead and send me the surveycampaign_results table and I will import 
it to the sp-escoach site.  Alternately, I messaged you the mysql root 
pwd on our Teams channel

Paul

On 8/30/21 3:58 AM, Michael Anello wrote:
> EXTERNAL SENDER
>
> @escoach 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fescoach&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161886992%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kmFHI1QgMKl8XOjB%2BLU%2BoRXqo2uA0PKVf19OmjFVCPg%3D&reserved=0> 
> Something odd is going on with this as well as with #51 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F51&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161896952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IwwV0qzkXR7jJQ8lFY9SYHrYHOYjwIUn34tFE92EpVU%3D&reserved=0>, 
> #52 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F52&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161896952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G4RLpWljBST9pRFJgsgodGuWWDQazsRRh6WYculALGI%3D&reserved=0>, 
> and #54 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F54&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161906901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L65YC0MxOMQJqTAMVA8bl5fG81UJKebG1c7kAYjyrbM%3D&reserved=0>. 
> I think it is a data issue - some difference between the data on the 
> sp-escoach site and the data I have on my local (and that I shared 
> with you a couple of weeks ago). Perhaps the database on sp-escoach 
> was reverted to a previous version with older data ***@***.*** 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthinkcollege&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161906901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nwD0SzAyuRTmpB8uexuQwiD7lZuG5TGHwnSEl81LfXE%3D&reserved=0>?) 
> If not, then I'd like to provide @thinkcollege 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthinkcollege&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161906901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nwD0SzAyuRTmpB8uexuQwiD7lZuG5TGHwnSEl81LfXE%3D&reserved=0> 
> with a copy of my local |surveycampaign_results| table (the same one 
> you have) to import into the sp-escoach site so that we are sure to be 
> using the same data for these tests everywhere.
>
> In order to compare apples-to-apples between my local and the 
> sp-escoach site, I had to login to the sp-escoach site using your 
> account. I changed your password to |alberto.migliore|.
>
> I then used the "debug" functionality to compare the query for this 
> case on sp-escoach with the query for this case on my local. *The 
> queries are identical.*
>
> If the queries are the same, then the only other thing that can cause 
> this issue is data.
>
> I'm hesitant to do anything else on this or #51 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F51&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161916858%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hW%2BTpvlRGmejq9wqJ48G%2FWbFpjH90AhtKuxrIYcjQgo%3D&reserved=0>, 
> #52 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F52&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161916858%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r%2FDYXW1I9rJ4cBqo3Q7dwGv2RgJhScLT%2BeZA%2FPbw83k%3D&reserved=0>, 
> or #54 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F54&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161926819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hwRf%2BdUWH3UvonZX1cUA%2B4QH%2BgdYotNRq9tlLiJcV3U%3D&reserved=0> 
> until we hear from @thinkcollege 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthinkcollege&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161926819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TVTlOF5zwfbUTFme7AmyUrUMGGTu73TMST6aLwPFc2g%3D&reserved=0> 
> on this data front.
>
> thanks,
> -mike
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F46%23issuecomment-908128541&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161926819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xHLL%2BdNBXPyZLY19PS7rqjGA6Ft8WpaCQTWalfpraZ0%3D&reserved=0>, 
> or unsubscribe 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANZAVEUVPCXPBZNGM7YRRTT7M22RANCNFSM5CPGR5GQ&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161936765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ENrW2RKImBX6sI8DdP3urL4wR8MdstP7bbwX%2FLtdDF0%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161936765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=81NqpYpAQWBA0unbvCZIjWSZ8MBw5acJeO4Ne%2FyvXNI%3D&reserved=0> 
> or Android 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpaul.foos%40umb.edu%7C2a5c96cdc84244d8618008d96b8bf73e%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637659071161946729%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lhylluzAs153xOdji00zCyjCiw0TmxepzusBCaLd2pM%3D&reserved=0>. 
>
>
-- 
Paul Foos
Web Developer
Institute for Community Inclusion
University of Massachusetts Boston
100 Morrissey Boulevard
Boston, Massachusetts  02125
Office: (617) 287-4359
Cell phone: (508) 521-0719

**Comment by ultimike** [comment]
@thinkcollege SQL dump attached.

[db_2021-08-30.sql.zip](https://github.com/communityinclusion/escoach/files/7076840/db_2021-08-30.sql.zip)

thanks,  
-mike

**Comment by thinkcollege** [comment]
Okay, I updated that table on sp-coach

Paul

On 8/30/21 9:03 AM, Michael Anello wrote:
> EXTERNAL SENDER
>
> @thinkcollege 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthinkcollege&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323073033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M3dsD8A7C69IGhUeHlcsHFD84i1m5nOO9Wlzqm4WY%2BM%3D&reserved=0> 
> SQL dump attached.
>
> db_2021-08-30.sql.zip 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Ffiles%2F7076840%2Fdb_2021-08-30.sql.zip&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323073033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IFoid%2B3alCg7iqej%2FxIu%2FEv%2BZfXDYo2W21cREjo6ZBk%3D&reserved=0>
>
> thanks,
> -mike
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommunityinclusion%2Fescoach%2Fissues%2F46%23issuecomment-908323713&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323082991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HO5ezUXwr5C8lELzoRWXdCnWqCPUfoXh%2Fduma%2FZRi%2Bc%3D&reserved=0>, 
> or unsubscribe 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANZAVBWNLF36PH5SKFBEQLT7N6THANCNFSM5CPGR5GQ&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323082991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1CIbjv92mpLkHc3cYvN2FnPsCuew40AftMI%2FYDY8hJk%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323082991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o6DsTgH0QiqNupoRblgo0fBbdTdWdMwOukVXbAg0g8s%3D&reserved=0> 
> or Android 
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpaul.foos%40umb.edu%7C35817e4f34d345f632e208d96bb69ccb%7Cb97188711ee94425953c1ace1373eb38%7C0%7C1%7C637659254323092947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tUnMGMaL6hTfJf07NwRGZrd2xWO8YCTxxCDe%2B%2FzWLKU%3D&reserved=0>. 
>
>
-- 
Paul Foos
Web Developer
Institute for Community Inclusion
University of Massachusetts Boston
100 Morrissey Boulevard
Boston, Massachusetts  02125
Office: (617) 287-4359
Cell phone: (508) 521-0719

**Comment by ultimike** [comment]
@escoach The sp-escoach site and my local now show the same results for "example 2":

- Who = Families, Friends... OR with Someone from a business
- Where = null
- What = "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation"

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike Much better for
- Who = Families, Friends... OR with Someone from a business
- Where = null
- What = "Networking" OR "Informational interview or business tour" OR "Engaging with businesses/job negotiation"
The "n" is correct. However, there are minor differences in the time reported. Is it due to rounding? 
For example:
 "All" in your [Google sheet](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=760518312) is 0:19 / day whereas in the [dashboard](http://sp-escoach.communityinclusion.org/dashboard) is 0:20 / day 

Also, "My Team" is 1:45 in your Google sheet and 1:46 in the Dashboard.
I am not worried. But wanted to mention in case it is a red flag for something else?

**Comment by ultimike** [comment]
@escoach Yes, I suspect it is just rounding errors due to the calculation we need to do to convert decimal time into hh:mm

Can we call this task closed? Are all instances of "selected activities" queries and data tables looking good?

-mike

**Comment by ultimike** [comment]
Closing this task.
