### ISSUE TITLE
Change Who/Where - "_none" option to "No selection"

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#49]
@escoach has requested that we change the `--` in the "Who" and "Where" dropdowns to "No selection" in #45.

@mgcobblestone I'm pretty sure this is just a matter of updating lines 50 and 60 of DashboardForm.php, but just in case there's more to it, I figured I'd run it by you.

-mike

**Comment by mgcobblestone** [comment]
@ultimike This is in place now.

**Comment by ultimike** [comment]
@mgcobblestone Looks good.

@escoach If you agree, please close this task.

-mike
