### ISSUE TITLE
Change order of columns to All, My team, Me

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#50]
In #45, Alberto requested that we change the order of the columns from:

All | Me | My team

to 

All | My team | Me

-mike

**Comment by mgcobblestone** [comment]
@ultimike This is in place now.

**Comment by ultimike** [comment]
@mgcobblestone Superduper - thanks.

@escoach Please review and if all looks for for this task (reordering the columns) because set this task to "Closed". Keep in mind that this task is limited to just the reordering of the columns, so if you spot other issues, please open new tasks for each.

thanks,  
-mike
