### ISSUE TITLE
Refactoring of "Who" summary

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#51]
This is an offshoot of #46 and #48.

**Comment by ultimike** [comment]
The "Who summary" is now matching all of my test cases 🕺 

@escoach Please review the case where "Who" = "Any interaction" along with any combination of "What" values. 

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike I am not sure what's happening. You wrote that the "Who summary" matches your test cases. But I still see discrepancies between the Dashboard and both your Google sheet and my Google sheet. Note that your Google sheet and my Google sheet match. See below.

What=Getting to know OR Finding jobs OR Other supports before hire.
Who=Any interaction

Your [Google sheet, Tab "Who summary (1 query)"](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1064923334), row 21 shows the following for "A person"

With "A person I support":
- All=1:01
- My team=1:24
- Me= 1:11

These figures match perfectly my [Google sheet, Tab Aug22, ](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=34647741)Table 1, row 2. 

However, the [Dashboard shows these figures](http://sp-escoach.communityinclusion.org/dashboard#):

With "A person I support":
- All=1:02
- My team=1:54
- Me= 1:19

![image](https://user-images.githubusercontent.com/83360935/131266351-87ed8ba3-a6a6-43c7-b5fb-39c8d0ffdd2e.png)

**Comment by ultimike** [comment]
@escoach Please re-review now that we have updated the data on sp-escoach. I have compared the results on sp-escoach and my local and they are identical.

thanks,
-mike

**Comment by escoach** [comment]
@ultimike The Google sheet and the Dashboard data match with a 1-minute discrepancy for some of the items. Probably due to rounding.

**Comment by ultimike** [comment]
Same answer about rounding and same question about closing as #46 and #54 :)

-mike

**Comment by ultimike** [comment]
Closing this task.
