### ISSUE TITLE
Refactoring of "Where" summary

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#52]
This is an offshoot of #46.

**Comment by ultimike** [comment]
This now matches all of my manual tests 🥳 

@escoach please review results when "Where" = "Anyplace" along with any combination of "What" values.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike Mhhh, I wonder if I am looking at the wrong stuff?
You wrote, "_This now matches all of my manual tests_". Yet, I am seeing discrepancies between the dashboard and your Google sheet?
I am looking at:

- What=Getting to know OR Finding jobs OR other supports before hire
- Where=Anyplace

Looking just at the "Office" data, your [Google sheet, tab "Where summary (1 query), row 41](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=1457665355)" matches my Google sheet (tab Aug22, Table 3, row 34) and shows:
Office: 

- All: 1:27
- Team: 2:00
- Me: 0:50

However, the dashboard for "Office" shows:

- All: 1:28
- Team: 2:32
- Me: 1:01

![image](https://user-images.githubusercontent.com/83360935/131252821-8c3177b3-811e-4099-a2dc-e5ac8b72d1d9.png)

Strange?
I need to run but hopefully this afternoon I will take a look at your other tasks.
Thanks

**Comment by ultimike** [comment]
@escoach Please re-review now that we have updated the data on sp-escoach. Data is matching my local.

thanks,
-mike

**Comment by escoach** [comment]
@ultimike Also in this case the Dashboard data match the Google sheet data with only negligible discrepancies for some of the items  (1-2 minutes).

**Comment by ultimike** [comment]
Same answer about rounding and same question about closing as #46 and #54 :)

-mike

**Comment by ultimike** [comment]
closing this task.
