### ISSUE TITLE
Sequence of items in the dashboard

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#53]
@ultimike Please organize the items in the dashboard as listed in [this Google file](https://docs.google.com/spreadsheets/d/1rrF7qGWqWmreDoNJihRGl8nxjvYWhOGiNtMwEhG71tY/edit#gid=1896282093).
Thank you.

PS: This task originated[ in Task51](https://github.com/communityinclusion/escoach/issues/51#issuecomment-907003990)

**Comment by ultimike** [comment]
@escoach Your Google Sheet doesn't include the compound fields, so I made my best guess as to where they should go.

Please review.

-mike

**Comment by escoach** [comment]
@ultimike Good catch. I updated the [Google sheet](https://docs.google.com/spreadsheets/d/1rrF7qGWqWmreDoNJihRGl8nxjvYWhOGiNtMwEhG71tY/edit#gid=1896282093), see rows 2-18. 
In essence, the combined items should be at the bottom of the table. Moreover, since the combined labels get very long and they are hard to fully display in the table, would it be possible to number the items in the drop-down menus for WHO and WHERE so that the combined items can be represented, for example, as "Either 2 or 3 or 4". See rows 9, 10, and 18.  
Let me know if this is confusing.
I appreciate your patience.

**Comment by ultimike** [comment]
@escoach This is done and has been pushed to the sp-escoach site.

-mike

**Comment by escoach** [comment]
@ultimike Thank you. Looks good.

**Comment by ultimike** [comment]
Superduper. Closing this task.

-mike
