### ISSUE TITLE
Confirmation of "What summary" data table

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#54]
@escoach Please confirm that the results for the "What summary" are correct - they match my manual query and calculations. 

Who = No selection
Where = No selection
What = No selection

This is the default data table that is displayed when the /dashboard page is loaded.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike no luck here too. My data does not match the Dashboard. However, I think that I know what's going on. The "n" at the bottom of the table in the [Dashboard is only 361](http://sp-escoach.communityinclusion.org/dashboard#) for "All". Yet the raw data includes 391 records. All our calculations so far were using 391 as the denominator for the "All" data. I am not sure why I am seeing 361 in the Dashboard as the "n" for "All"? This probably explains the discrepancies reported earlier today?

See my [Google sheet, Tab Aug22,](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=34647741) Table 9, row 98-108. 

![image](https://user-images.githubusercontent.com/83360935/131267958-7ba0d97d-24f0-4236-bfdd-27578f1e0b46.png)

**Comment by ultimike** [comment]
@escoach Please re-review now that we have updated the data on sp-escoach.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike The Dashboard now matches the Google sheet. Again there are differences of 1 minute for some of the items, which probably are due to rounding? Probably nothing to worry about, but wanted to bring it up just in case it is a red flag for something else.

**Comment by ultimike** [comment]
Same answer for rounding at I wrote in #46.

Are we good with all cases of the "what summary" data? Can we close this task?

-mike

**Comment by ultimike** [comment]
Closing.
