### ISSUE TITLE
"Observer" provider

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#59]
This is an offshoot of [task 56](https://github.com/communityinclusion/escoach/issues/56#issuecomment-911827703).

From task 56 (Paul):

> I created a Provider taxonomy term, "Observer" on the live site which we would like to assign to internal users and others whose survey data we don't want included in the dashboard. Could you put in some code to exclude this Provider?

From task 56 (Alberto):

> Specifically, rather than filtering out the "observer" data altogether, could you filter them out only in the "All" querries?
> 
> Rationale: "observers" may include potential future users who want to try es-coach by using it and see how it works. By filtering out their data only in the "All" column, the "observers" would be able to see both their individual data and their team data and compare with everybody else data ("All" data) without actually compromising the "All" data (We are not sure that their data are completely clean and usable during their trial period). Please let me know if this is confusing.

**Comment by ultimike** [comment]
Let us not repeat the mistakes of the past 😄 

I'm not entirely clear what this means from a query standpoint, as it will involved modifications to all of the 4 main queries we just spent a few weeks refactoring and validating.

Perhaps the best path forward is doing what we didn't initially do previously - setting up some manual test cases so that we have a clear goal.

@escoach How would you feel about setting up a small `surveycampaign_results` table with some "Observer" data, then generating a sample results data table for each of our 4 queries (selected activities, where summary, what summary, who summary) so that we have a clear goal. 

Thoughts?

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike You beat me. I meant to ask you to hold off on the "observer" thing until after @thinkcollege and I talk more about it later this morning (Friday). We need to further discuss. Yes, let's not repeat our mistakes.

**Comment by thinkcollege** [comment]
@ultimike @escoach  Yes to using a small sample set, maybe the one we have already been using, just tag some of the sample users with the "Observer" provider.  Best would be to just change all the ICI users to Observer.  That is realistic in terms of who these observers would mostly be.

**Comment by escoach** [comment]
@ultimike @escoach I will have those tables ready tentatively by the end of the day

**Comment by escoach** [comment]
Hi @ultimike I created a new [tab "Sep 03" in my Google sheet ](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=2095369804)with 6 tables corresponding to 6 key scenario types: selected activities, where summary, what summary, who summary, who = none, and combined variable. 

The computation is pretty simple: Check out the formulas in column K to see how I computed the new "n" of "All" after excluding the "Observer = Institute for community inclusion" and that then I used to compute the hrs/day in column D in the table.

**Comment by ultimike** [comment]
@escoach @thinkcollege Which task has priority? This one or the Monthly Trends (#58)?

@thinkcollege Where was the new "Observer" Provider term created? I don't see it on http://sp-escoach.communityinclusion.org or https://www.es-coach.org

This is going to be tricky to test once we get the code updated, as we don't really have any data where Provider=Observer, know what I mean?

@mgcobblestone The short version of this task is as follows: If the current user's provider="Observer", then all the `*All` query values need to be modified by `*All - *Provider`. For example, in the default /dashboard display (What summary):

`JobSeekerAll = JobSeekerAll - JobSeekerProvider`

Or 

`JobSeekerAll = sum(case when answer483 IN (11658) then 1 else 0 end) - sum(case when (answer483 IN (11658) AND provider = 'Institute for Community Inclusion') then 1 else 0 end)`

My thinking is that we don't want to do this in the query - it would require quite a bit of refactoring of stuff that is currently working (and lead to even more gnarly queries)

What do you think about doing this as some post-processing of the query result in `QueryBuilder::processResultsSummary()`?

-mike

**Comment by thinkcollege** [comment]
I added "Observer" provider.  I may have called it something else when I added it earlier.  Can we just switch some of our internal users to Observer?  Or we could just change one of the other Provider taxonomy terms to that name and use a chunk of our current users as the test case for this.

**Comment by thinkcollege** [comment]
@ultimike  I would give the Observer task priority over the monthly trends task for now.

**Comment by mgcobblestone** [comment]
@ultimike Just to clarify - we only subtract "Observer" totals from the All column if the current user is assigned to the "Observer" provider?

If I'm logged in as a regular user "A" belonging to provider "X", should the ALL columns in my queries include values from user "B" who belongs to the "Observer" provider?

**Comment by ultimike** [comment]
@mgcobblestone That is my understanding. @escoach Can you confirm?

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike @mgcobblestone 
Thank you for asking and the opportunity to clarify. You wrote "._.If I'm logged in as a regular user "A" belonging to provider "X", should the ALL columns in my queries include values from user "B" who belongs to the "Observer" provider?._.."

Answer: No. 
To use your words, if I'm logged in as a regular user "A" belonging to provider "X", the ALL columns in my queries do NOT include values from user "B" who belongs to the "Observer" provider. In fact, **the "Observer" values are always EXCLUDED from the "ALL" columns** in all tables/queries. 

Here is the big picture: "Observers" are mostly staff at the Institute of Community Inclusion who enter random data into the system. Observers may also include external users who want to try es-coach without committing to entering accurate data (They may be managers who do not provide direct services). We do not want these "dirty" data to get into the "ALL" data. Of course, these folks will see their own "dirty" data and they will see "My team" dirty data. That's not a problem as these folks are not there to provide accurate data. Everyone else (legitimate users) will see CLEAN My data, My team data, and ALL data.

Let me know if you have questions or concerns

@thinkcollege feel free to add your comments if you have any.

**Comment by mgcobblestone** [comment]
Thanks @escoach

**Comment by mgcobblestone** [comment]
@ultimike I have pushed an update for this.  Please take a look and let me know if it looks correct.
Thanks.

**Comment by ultimike** [comment]
@escoach - thanks for the explanation, I believe it makes sense to me now.

@mgcobblestone - thanks for the quick turnaround on this.

Here's what I did for my initial testing:

## Test 1

- Who = no selection
- Where = no selection
- What = Other supports AFTER hire

This results in the "selected activities" query and table. I first ran it via the /dashboard with no changes to the `surveycampaign_results` table, meaning no one had an "Observer" provider.

I then manually changed one of the rows in the `surveycampaign_results` table by changing the provider to "Observer" (I made sure to modify one that was included in the results) and then compared the new /dashboard results with the unmodified case above. 

While the `n` row results were identical, there was a small change in the time values for both "selected activities" and "other activities". I thought that the `n` row should change as well (I was thinking that the `nAll` value should decrease by 1, but after digging into the code, it looks like we're calculating `nAll` for the selected activities table as `SelectedAll - SelectedObserver`. In this test case, `SelectedObserver` was 0, so there is no change to `nAll`.  @escoach, is this correct?

## Test 2

- Who = no selection
- Where = no selection
- What = no selection

This is the default /dashboard page settings - the "what summary". I did the same thing as in test 1 - I only changed a single record in the `surveycampaign_results` table and compared the results. In this case, the time values slightly changed (due to the "all" values ignoring 1 result from the table) and the `nAll` value decreased by one. 

Again, looking at the code, we are calculating `nAll` for the "what summary" using `nAll - nObserver`. @escoach, please confirm this is correct.

## Test 3

I updated my local `surveycampaign_results` table - I changed all records where provider = 'Institute for Community Inclusion' to provider = 'Observer' (104 total). I also updated my local user to have a provider of "Observer".

I then ran the following and compared with [Alberto's Google Sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=2095369804):

- Who = no selection
- Where = no selection
- What = no selection

While the `n` values match up just fine, the time values do not. 

Digging into the code a bit, it looks like we are not subtracting out observer data from the individual "what" values. For example, this query returns a value of `JobSeekerAll` = 58, we need to subtract the value of `JobSeekerObserver` (7) from 58, and use that in the calculation of the data table. I made a small addition to the code in QueryBuilder::calculateHrs() to fix this, I believe. @mgcobblestone please double-check my work.

After this change, we have good agreement with @escoach's Example 1 and Example 2.

The "OtherAll" values in Examples 3 was a bit off, though. I found and fixed an issue in QueryBuilder::processResultsSummary() and QueryBuilder::calculateOther() - again, @mgcobblestone please review.

At this point, I believe we have good agreement with @escoach's Google Sheet. Please review. I have pushed the changes to the Dev site - http://sp-escoach.communityinclusion.org/  - if they look good, then @thinkcollege can pull them into the live site.

thanks,  
-mike

P.S. @mgcobblestone I hit this PHP notice a few times, but I'm not entirely sure how best to get around it. Maybe we need to add a `if isset()` somewhere?

> Notice: Undefined index: nAll in Drupal\survey_dashboard\Service\QueryBuilder->processResultsSummary() (line 354 of modules/custom/survey_dashboard/src/Service/QueryBuilder.php).

**Comment by mgcobblestone** [comment]
Thanks @ultimike , changes look good.  I realized I missed some of that last night and was planning on getting it this morning - your changes pretty much cover it.

**Comment by escoach** [comment]
**Test 1**
You wrote: ".._.(I was thinking that the nAll value should decrease by 1, but after digging into the code, it looks like we're calculating nAll for the selected activities table as SelectedAll - SelectedObserver. In this test case, SelectedObserver was 0..._"
Me: My understanding is that "SelectedObserver should have been 1, not 0. So you were correct to expect nAll to decrease by 1. Am I missing something?

**Test 2**
The reasoning sounds correct. I would need to see the data before I can fully confirm. 

**Test 3**
I am not entirely sure that I understand. 
You wrote: "..._.I changed all records where provider = 'Institute for Community Inclusion' to provider = 'Observer' (104 total)._...After this change, we have good agreement with @escoach's Example 1 and Example 2..._." Note that my [Google sheet (Tab Sep03) ](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=2095369804)includes only 68 "Institute for Community Inclusion" and thus 68 "Observers" not 104. 

Also, you wrote: "...I have pushed the changes to the Dev site - http://sp-escoach.communityinclusion.org/ - if they look good, then @thinkcollege can pull them into the live site....". However, on my screen, I still see that the total N=391. Shouldn't it be 391-"Observers" (i.e. 323 in my Google sheet)?

![image](https://user-images.githubusercontent.com/83360935/132590038-669eaa91-e6e7-4d04-a59d-eb3f1bec7c7c.png)

I might be missing something, but based on what I see, I am not convinced that we are in full agreement on everything yet.

**Comment by ultimike** [comment]
@escoach:

## Test 1

Shouldn't `SelectedObserver` = 1 only if the observer actually selected the same "What" option ("Other supports AFTER hire" in this case)? If the observer doesn't report that same "What", then `SelectedObserver` should be 0. 

Maybe it is best if you add this test case to your Google Sheet so we can compare actual numbers?

## Test 2

In order for you to see the same results that I'm seeing on my local, I'd need to (manually, via a SQL query) change all the "provider = 'Institute for Community Inclusion'" records on the http://sp-escoach.communityinclusion.org/ site to "provider = 'Observer'" - is this okay with you and @thinkcollege?

Actually, it's probably easier for @thinkcollege to do it, as it's a bit tedious for me to get command line access. The query that needs to be run is:

`UPDATE surveycampaign_results SET provider = 'Observer' WHERE provider = 'Institute for Community Inclusion';`

## Test 3

@escoach You will not see the same results I'm seeing until we run the query above on the http://sp-escoach.communityinclusion.org/ site. I'm attaching a screenshot of the results from my local - you'll see that they match (outside of rounding errors) your Google Sheet.

![Screen Shot 2021-09-09 at 2 09 10 PM](https://user-images.githubusercontent.com/1727889/132683275-ab9054bf-02aa-458d-999b-46894704bc83.png)

@mgcobblestone I think you may have missed my "P.S." in my previous comment:

> P.S. @mgcobblestone I hit this PHP notice a few times, but I'm not entirely sure how best to get around it. Maybe we need to add a if isset() somewhere?
> 
> Notice: Undefined index: nAll in Drupal\survey_dashboard\Service\QueryBuilder->processResultsSummary() (line 354 of modules/custom/survey_dashboard/src/Service/QueryBuilder.php).

-mike

**Comment by thinkcollege** [comment]
@ultimike I ran your mysql query, UPDATE surveycampaign_results SET provider = 'Observer' WHERE provider = 'Institute for Community Inclusion'; on the sp-escoach.communityinclusion.org site

**Comment by ultimike** [comment]
@thinkcollege Great - thanks. I went ahead and added an "Observer" provider term to the same site.

@escoach I also updated your account on http://sp-escoach.communityinclusion.org so that you're part of the "Observer" provider. The data on this site now matches my local. Let me know what you think.

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike I did see the PS, just haven't fixed it yet.  My thought was that nAll should never be missing so I need to see which query was run to see if I am correct about that or if there are valid cases where it is not used.

**Comment by ultimike** [comment]
Understood - thanks!

I believe I see it most with the default settings (nothing selected) on the /dashboard page. If you don't see it right away, try rebuilding caches, then reloading.

-mike

**Comment by mgcobblestone** [comment]
@ultimike Should we be using nAll in that query?

**Comment by mgcobblestone** [comment]
For now, I have added the nSums stuff to the what-summary.  No more warnings/notices.

**Comment by escoach** [comment]
@ultimike

**Test 1**
As you suggested, I created the Test1 scenario in the [Google sheet,](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=2095369804) Tab Sep03, see Table 7 toward the bottom of the sheet. Columns G-I show the data before whereas columns D-F show the data after excluding 1 "Observer" that reported 483=11660 (Support after hire). 
The orange cells show all the data points that are expected to change.
Table 8 is the same case of 1 "Observer" reporting 483=11660 applied to the default table.

**Comment by escoach** [comment]
The modified dashboard with "Observers" data works. The dashboard now matches all the tables in my [Google sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=2095369804) with only rounding discrepancies in the time values. Nice

**Comment by ultimike** [comment]
@escoach Great news!

@mgcobblestone I'm still getting the PHP Notice on the default /dashboard page after clearing caches. Same as before:

> Notice: Undefined index: nAll in Drupal\survey_dashboard\Service\QueryBuilder->processResultsSummary() (line 356 of modules/custom/survey_dashboard/src/Service/QueryBuilder.php).

I noticed that you had to resolve a code conflict in Git - could the fix for this have been left behind by accident?

@mgcobblestone as for your other questions about nAll and nSums - I think we're good as-is 😄 

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Sorry, I was working in a feature branch and hadn't merged it yet.  Take another look.

**Comment by ultimike** [comment]
@mgcobblestone Looks good - I can't reproduce the issue.

@escoach @thinkcollege are we done here? If so, when pulling this into the live site, we may also want to run the same query as before to change all ICI data records to "Observer". 

-mike

**Comment by thinkcollege** [comment]
@ultimike I can do that now or whenever you are ready.

**Comment by ultimike** [comment]
I'm away from my computer, but feel free to deploy. I don't think there's
anything I need to do on my end.

Mike

**Comment by ultimike** [comment]
Assigning to Paul for deployment to live.

-mike
