### ISSUE TITLE
"Either 2 or 4" discrepancy

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#63]
@ultimike I noticed the following discrepancy in both the live and the local dashboards:
 
I selected: 
What= Getting to know + Finding jobs + Other support before hire (But it does not matter what you select under "What")
Who= **“Either 2 or 4”** (i.e. interacting with families OR someone from a business)

The live dashboard table shows that “Either 2 or 4” = 1:49.
However, Families (1:07) + Someone from a business (0:53)= 2:00
The same issue happens with the local dashboard.
PS: At some point, we will need to fix the numbering of labels of each row. For example, the first row should be “1. A person….” Instead of “1.1. A Person…”.

**Comment by ultimike** [comment]
@escoach I'm not 100% sure what you mean by the "live and local dashboards". Do you mean this:

Live: https://www.es-coach.org/dashboard 
Local: http://sp-escoach.communityinclusion.org/ 

If so, the latter is not "Local". When I say "Local", I mean the copy of the site I have up-and-running on my laptop that I used for development. Moving forward, probably best to refer to http://sp-escoach.communityinclusion.org/ as the "Dev" site (or by it's URL to remove any ambiguity).

Regarding the results, I suspect this has to do with something related to "who" and "who else". I reviewed each query from the 3 cases (where Who is "2+4", "only 2", and "only 4") and their form and arguments match our test cases. For example, your "Table 8" from the "Aug 22" tab of your [Google Sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=34647741) matches the results. 

-mike

**Comment by escoach** [comment]
@ultimike Thanks for the clarifications. 

- I will use "Dev" to refer to http://sp-escoach.communityinclusion.org/  and Live for https://www.es-coach.org/ or the url to minimize confusion.
- I agree with your explanations about the "who" and "who else". 
I a going to close this.
