### ISSUE TITLE
Any interactions bug

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#64]
@ultimike I noticed a bug in the live dashboard when selecting either "Any interactions" or "Anyplace". 

- If after a default screen I select "Anyplace" the table shows the 6 "What" activities as if "Where" = "No selection".
- Similarly, if I select "Any interaction", I see the 6 "What" activities as if "WHO=No selection". 
- Moreover, if I select "What= something" AND "Where= Anyplace", and then I clear "What" and select "Any interaction", the table keeps showing the distribution of the "Where" items as if no new selection was made.

Note that the **local dashboard works correctly**

![image](https://user-images.githubusercontent.com/83360935/132949706-7a2f5ef0-220f-448f-8000-436c20cb9f38.png)

**Comment by escoach** [comment]
@ultimike contrary to what I wrote above, similar issues happen also in the local dashboard.
For example, I am in the **local dashboard** and I select:
"What=Getting to know" AND "Who = A person I support". I get the table below:
![image](https://user-images.githubusercontent.com/83360935/132953666-1f5637f7-4aa1-454a-ba77-7e170039f9ad.png)
 
However, if then I clear the "What" to "no selection" AND I keep "Who = A person I support", the table does not change see below: 

![image](https://user-images.githubusercontent.com/83360935/132953567-d87c37cb-4a64-4b86-a4f2-be8e6b763f28.png)

**Comment by ultimike** [comment]
@escoach Again, I'm going to assume that you're referring to:

- Live as https://www.es-coach.org/dashboard
- Local as http://sp-escoach.communityinclusion.org/dashboard (let's call this "Dev").

I compared the queries on the Dev and Live sites and I think this might be because the live site doesn't have the latest code pushes? @thinkcollege Could this be the case? Is the live site code up-to-date with the Dev site?

On another note, I did find the table row issue with the extra `1.1 In my home...` that was mentioned in #63 - I believe I have found and fixed the issue. @mgcobblestone please confirm my fix in commit `557708ccc` is correct. I have pushed this fix to the Dev site, it is up to @thinkcollege to pull it into the Live site at his convenience.

thanks,  
-mike

**Comment by ultimike** [comment]
Assigning this to Paul so he can pull into the live site so Alberto can do further testing.

-mike

**Comment by thinkcollege** [comment]
@ultimike I merged the devel branch into the rack branch (live site)

**Comment by ultimike** [comment]
Thanks Paul!

Assigning to @escoach for testing.

-mike

**Comment by escoach** [comment]
@ultimike I tested the dashboard. Most issues have been resolved, thank you.
However, one issue remains on both the Dev and the Live sites:
For example, if I select "What=Getting to know" AND "Who = A person I support". I get the table below (Dev site):

![image](https://user-images.githubusercontent.com/83360935/133515525-abbf98dc-ab8d-4033-8b68-0ced83656470.png)

However, if then I clear the "What" to "no selection" AND I keep "Who = A person I support", the table does not change see below:

![image](https://user-images.githubusercontent.com/83360935/133515662-3f525a7d-fae8-4476-94f4-fb8023452759.png)

The same issue happens with the "Where" selection.

If it helps, I would be ok to add a warning like there is in the monthly trends:

![image](https://user-images.githubusercontent.com/83360935/133516032-391e9f20-d8ef-4885-94b5-f6eac6c7785d.png)

**Comment by ultimike** [comment]
@mgcobblestone Can you look into this?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike @escoach I have added JS validation to address this scenario.  This has been pushed to devel.

**Comment by escoach** [comment]
@ultimike Strange. Nothing changed when I repeated the testing described above on the Dev site http://sp-escoach.communityinclusion.org/dashboard#

**Comment by ultimike** [comment]
That is strange, as it is working fine on my local. I wonder if it was a deployment issue.

While I was poking around, I noticed (and fixed) a minor display issue with the table. I'm deploying now in hopes that it fixes the missing popup warning...

I'll report back in a few minutes.

-mike

**Comment by ultimike** [comment]
@escoach Be sure to clear your browser cache, but I believe it is now working on the sp-escoach site.

-mike

**Comment by escoach** [comment]
@ultimike confirming that it is now working on the Dev site. 
I assume that when it will be pushed to the Live site es-coach.org, it will work there too (not working right now). Thank you!

**Comment by thinkcollege** [comment]
@ultimike @escoach I pushed those changes to the live site and cleared cache.

**Comment by escoach** [comment]
@thinkcollege @ultimike perfect, that works. This can be closed as far as I can tell.
