### ISSUE TITLE
Last row of the tables

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#65]
@ultimike 
I noticed that the last row of the tables shows three different types of labels in different tables. I am not sure if that is intentional or we overlooked it as we were addressing more important things. But as we get closer to share the dashboard with real users at the end of September, when you have a chance, could you edit those labels for improved consistency? 
In general, unless you have other suggestions, make these edits:

- Use **"Total responses"** for the summary tables including the default table, "Who" summary table, and "Where" summary table. Right now these tables show either "Total respondents" or just "N".
- Use  "**n selected activities**" for all other tables about specific activities (The 3-row tables). Right now they show either "N (323)" or just "N". Note: I like the idea of "N (323)" But it applies to the "All" column only, so it can be confusing for some users. 
Let me know if you have any suggestions. Thank you.

**Comment by ultimike** [comment]
@escoach I have made your requested changes and have pulled them into the Dev site for your review.

-mike

**Comment by escoach** [comment]
@ultimike 
Looks good, thank you. I guess that this change will show up in the Live site when @thinkcollege will push the https://github.com/communityinclusion/escoach/issues/64#issuecomment-917616599 change.

**Comment by ultimike** [comment]
Assigning to @thinkcollege for the pull into the live site.

-mike
