### ISSUE TITLE
Monthly Trends - total respondents column

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#68]
From #58:

> Question: "Determine which values go in the "Total respondents" row for this case (and update Google Sheets)."
> Answer: Instead of a "Total responses" row, could you do a "Total responses" column on the right side of the table? It should count the total number of responses available for the "Me" data, each month. [See column H in the Google sheet, Tab "Trends092121"](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461).

@escoach It looks like column H is just the sum of the "Me" values - is this correct?

-mike

**Comment by escoach** [comment]
@ultimike That is correct. Having said that, could you hold off to create that column until Thursday? 
I am pretty sure that showing the total respondents for "Me" makes the most sense. However, I would like to double-check with our team here at a meeting we have this Thursday.

**Comment by ultimike** [comment]
@escoach Sounds good - let me know.

-mike
