### ISSUE TITLE
Monthly trends new test data

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#71]
@mgcobblestone Roger that - looks good.

@escoach Please review on sp-escoach - the data table now matches our Google Sheets.

Next, I think we need to:

1. Determine which values go in the "Total respondents" row for this case (and update Google Sheets).  
2. Generate a new test data table with different inputs to further validate the code (perhaps with a single who or what option selected).  
3. Are "Who=Any interaction" or "Where=Any place" valid selections for Monthly Trends? If so, we'll need new test data tables in Google Sheets to validate with.  

@escoach How would you like to proceed?

thanks,  
-mike

_Originally posted by @ultimike in https://github.com/communityinclusion/escoach/issues/58#issuecomment-929135911_

**Comment by escoach** [comment]
@ultimike Following up on your earlier request, I created Tables 2, 3 and 4 to further validate the code. See my [Google sheet (Tab "Trends092121") ](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461) rows 32-83

**Comment by ultimike** [comment]
@escoach Examples 2 and 3 match up 😄 

I can't compare example 4, because the "where" condition on your sample table (`"Where = In other community integrated settings" (482=11652) or At a business (482=11651)`) doesn't match up with an available "where" option that we offer in the select list.

You'll need to modify your sample table to either be a single "where" or use one of the pre-set combinations: "2, 3, or 4" or "1, 2, or 4".

-mike

**Comment by escoach** [comment]
@ultimike Good catch. I picked the pre-set combination 1, 2, or 4  and added Table 4 BIS (row 87) in the [Google sheet Tab "Trends092121"](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461).

What = “Community mapping/Researching business” (538=11841) OR “Networking” (538=11845) OR “Informational interview or business tour” (538=11844) AND "Where = In other community-integrated settings" (482=11652) or At a business (482=11651) or In my office or home office (482=11649)

**Comment by ultimike** [comment]
@escoach - I think you have a bug in Table 4 - it looks like you're using `482=11651` instead of `482=11650` for "Where" = "At a business (Not provider-owned)" which leads to your table data to be incorrect.

I confirmed this by using the wrong value in my local query and duplicated your results. 

-mike

**Comment by ultimike** [comment]
Ok - see what the issue is. It's **not** an issue with us using different keys (phew).

From your Google Sheet:

```
Table 4 BIS. What = “Community mapping/Researching busines” (538=11841) OR “Networking” (538=11845) OR “Informational interview or business tour” (538=11844) AND "Where = In other community integrated settings" (482=11652) or At a business (482=11651) or In my office or home office (482=11649)
```

The three "where" options that you're using are:

- 4 - In other community integrated settings.
- 3 - At a business (not provider-owned)
- 1 - In my office or home office

Unfortunately, we do not have a "1, 3, and 4" option - the only multi-options we have are:

- Either 1, 2, or 4
- Either 2, 3, or 4

So, your example table is using a scenario that the UI can't replicate - see what I mean?

-mike

**Comment by escoach** [comment]
@ultimike You are right, good catch! I am not sure what I was thinking.
I fixed [table 4 in the Google sheet](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461) now showing these data: 
Table 4. What = “Community mapping/Researching business” (538=11841) OR “Networking” (538=11845) OR “Informational interview or business tour” (538=11844) AND "Where = In other community-integrated settings" (482=11652) or **at a residence (482=11650)** or In my office or home office (482=11649)

Thank you for your patience with this bug.

**Comment by ultimike** [comment]
@escoach We have good matches between my query and your Google Sheet everywhere except:

- Me, April 2021
- Me, August, 2021

Considering our other three Monthly Trends test cases are still returning matching data between our test cases, can you check the counts on your end for those two time periods?

-mike

**Comment by escoach** [comment]
@ultimike please check if now April and August 2021 match. Or let me know if you have a google sheet where I can check what you got. I double-checked the data a few times and lost track if I actually had to make changes or if there were no issues that I could find. It looks correct to me now. Does it match your data?

**Comment by escoach** [comment]
@ultimike actually, I just saw that my Google sheet now matches the dev site https://rp-escoach.communityinclusion.org/dashboard
Looks like we are good. Should I run a few more tables or are you confident with what we got?

**Comment by ultimike** [comment]
@escoach Yes - I can confirm that your Google Sheet matches my Google Sheet, my local environment, and the rp-escoach environment results 🎉 

Good question about running more tables for result validation. Based on #69, are there any use cases for the Monthly Trends results that we haven't covered with data validation?

Maybe we should do a table where "Who" = "Any interaction" or "What" = "Any place"?

-mike

**Comment by escoach** [comment]
@ultimike Isn't Table 1 in the [Google sheet: Table 1. ](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461) what you describe as a table where "Who" = "Any interaction" or "What" = "Any place"? (WHAT = 483 = 11658 (Getting to know a job seeker) OR 11659 (Finding, securing jobs) OR 11661 (Other supports BEFORE hire) 

So I checked the https://rp-escoach.communityinclusion.org/dashboard by selecting the following options and comapred with Table 1 in the Google sheet:

- Who = no selection
- Who=Any interaction
- Where=No selection
- Where=Anyplace
Not surprisingly the time values in the dev dashboard did not change regardless of what of the above Who and Where selection I made. The data in the dev dashbaord matched the Google Table 1 data.

Next, I could ask a colleague of mine to spot-check a few more combinations. Or do you need to do more work on the https://rp-escoach.communityinclusion.org/dashboard , no rush. What do you think?

**Comment by ultimike** [comment]
@escoach Ah yes - good point. 

If you want to have someone check a few more results for Monthly Trends on the rp-escoach site, I don't think it would hurt.

I think the only other task that @mgcobblestone has on his plate is the charting.

Once your colleague confirms that our data tables are good, we'll have to decided (by opening a new task) what to tackle next - Quarterly Trends or investigating the level of effort to do the 3-month averaging.

-mike

**Comment by ultimike** [comment]
Very good. I'll set this task to closed then.

-mike
