### ISSUE TITLE
Monthly Trends - swap "Me" and "My Team" columns

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#72]
@mgcobblestone Please swap the columns in the Monthly Trends data table so that the order is:

- All
- My team
- Me

Currently, it is:

- All
- Me
- My team

This way, it matches all the other tables.

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike This is up on devel

**Comment by ultimike** [comment]
They looks swapped to me.

@escoach Please confirm on rp-escoach.communityinclusion.org and then close this task.

thanks,  
-mike
