### ISSUE TITLE
New development server

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#73]
Hi @ultimike  I have been working on setting up a new development server with updated software, more power and disk space.  I finally got my organization to part with an extra $10/month to do this.  I set up a clone of your development site, code and db.  Everything is up to date as of this morning at 11.  All I need to do is point the Github branch and Jenkins deployment at that site instead of the current sp-escoach.communityinclusion.org.  I added your public key to the new server.   You would just need the ip of the new server and the (slightly) different domain name.  If you are okay with this I can pull the trigger on the switch any time, or if you have questions or potential issues let me know.
New domain name: rp-escoach.communityinclusion.org
New ip address: 104.131.35.148, port 22

**Comment by ultimike** [comment]
I can't think of any potential issues with doing this.

Which branch will it use? `devel`, `rack`, or something else?

-mike

**Comment by thinkcollege** [comment]
It will use the same devel branch.  I will make the switch this afternoon.  If you want to do a test push later this afternoon or tomorrow you can check if it is working.  Just hold off on any db changes or code pushes to sp-communityinclusion.org/ devel branch

**Comment by ultimike** [comment]
Ok - we won't make any pushes until we get the all-clear.

cc @mgcobblestone 

-mike

**Comment by thinkcollege** [comment]
I switched to the new server.  You can push to the same devel branch on github and it will deploy to rp-escoach.communityinclusion.org  If you forget and go to sp-escoach.communityinclusion.org you will be automatically redirected to the new address.  Deployment to rack still goes to the live server  See above for ip address of development server.  I put @ultimike 's public key on the new server, so ssh should work using ici@104.131.35.148, port 22.  I hope there won't be problems but let me know here if anything breaks.

**Comment by ultimike** [comment]
@thinkcollege Great - thanks.

I can confirm that I can access the site and SSH in.

@mgcobblestone Feel free to resume code pushes to `devel`.

thanks,  
-mike
