### ISSUE TITLE
n respondents in the public dashboard 

### ISSUE THREAD

**Issue by escoach** [communityinclusion/escoach#74]
@ultimike today I happened to check the dashboard as if I was a random visitor (So I was not logged into my account). The total responses in the "All" column are only 18 (Screenshot below). But if I log into my account I see 178 responses in the "All" column. I cleared the cache and tried again, but I still see only 18 if I am not logged in. My colleague Oliver also sees only 18 on his computer. Thoughts?

![image](https://user-images.githubusercontent.com/83360935/136431159-c7c07b91-a16d-42d3-9252-40b2fc72feb9.png)

**Comment by ultimike** [comment]
Anonymous visitors don’t see observers. But, when you’re logged in, you’re
an observer so you see your own observer data. Isn’t that the way it is
supposed to work?

Mike

**Comment by escoach** [comment]
@ultimike let me explain better. Anonymous visitors should see the aggregated data of all legitimate users in the column "All". Therefore, today they should see 178 Total responses at the bottom of the column "All". 

However, when today I visited the dashboard as an anonymous user (I was not logged into my account), I could see only 18 Total responses at the bottom of the column "All". Shouldn't I see 178?

**Comment by thinkcollege** [comment]
D'Oh!  I didn't update the latest code to the live site.  Working now: anonymous /dashboard shows 211 total users, as does logged in /dashboard
