### ISSUE TITLE
Design SQL queries to generate opening screen from mockup ("What summary")

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#8]
Mike will work with Alberto on designing the SQL query(s) necessary to generate the following data table.

- All data
- My data (is this limited to just the data for the logged in user?)
- My Team data (what exactly does this include? Is this just per-provider?)

![Screen Shot 2021-04-28 at 10 24 05 AM](https://user-images.githubusercontent.com/1727889/116420329-e2510800-a80b-11eb-8281-1db5c927a29b.png)

**Comment by ultimike** [comment]
Initial work on queries:

```
/* Getting to know a job seeker */
/* All data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11658;
/* My Team data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11658 AND provider = 'Provider name';
/* My data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11658 AND contact_id = {integer};

/* Finding, securing jobs */
/* All data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11659;
/* My Team data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11659 AND provider = 'Provider name';
/* My data */
SELECT count(*) FROM surveycampaign_results WHERE answer483 = 11659 AND contact_id = {integer};

/* Other supports BEFORE hire */
/* Same as above except answer483 = 11661 */

/* Any supports AFTER hire */
/* Same as above except answer483 = 11660 */

/* Staff meetings, professional development, billing, etc.. */
/* Same as above except answer483 = 11663 */

/* Day programs, residential, etc… */
/* Same as above except answer483 = 11662 */
```

**Comment by escoach** [comment]
@ultimike I checked the math and I confirm that it is correct. 
The summary table shows the same results as I got, using the output from your query.

**Comment by escoach** [comment]
@ultimike in your post on top of this page you had these 2 questions about the data. See my responses right after your questions:

My data (is this limited to just the data for the logged in user?)  _Yes, "My data" is the individual data entered by an individual user i.e. paul.foos@umb.edu in your query above_
My Team data (what exactly does this include? Is this just per-provider?). _Yes, the team data = the provider data._

**Comment by escoach** [comment]
@ultimike Our general rule is to keep things as simple as possible so as to not slow down your work. Therefore, please discard the following request if it complicates things. 

Here is the request: Would it be possible to display the 'n' in the table below the chart? For example, referring to your computations above, would it be possible to add a row at the bottom of the table that displays n=521 for "All" data, n=11 for "My data" and n=295 for "My Team" data?

![image](https://user-images.githubusercontent.com/83360935/116923527-bd520000-ac24-11eb-8263-65e6daa307a9.png)

**Comment by ultimike** [comment]
@escoach Yes, also displaying the total number of respondents shouldn't be a big deal, as that's the data that is returned by the query.

-mike

**Comment by ultimike** [comment]
@escoach This needs to include the "Who else" stuff as well, correct?

-mike

**Comment by escoach** [comment]
@ultimike the "Who else" must be included every time we deal with "Who"  items. In other words, the data focus on these three core constructs:
- What happened
- Who (Always includes Who else) was the interaction with
- Where it happened

Hope this helps

**Comment by ultimike** [comment]
@escoach So, in this opening screen, since we're not filtering by "Who" (answer481), there's no reason to do anything with "Who else", correct?

See the "Gitlab #8" tab of the [Google Sheet I've shared with you](https://docs.google.com/spreadsheets/d/13T2JrHmX-xpxbkB5wk5z9Br4V5hauoWlL4gy0pg7ZXA/edit#gid=659085311) for an example output from this query. Please confirm that all is correct.

thanks,
-mike

**Comment by escoach** [comment]
@ultimike 
A) To your first question, you are correct: for the opening screen, we do not filter for WHO. Therefore, no need to worry about WHO Else.

B) I reviewed the Google sheet and here are my comments:

- Tab Gitlab#8: The data in column B does not seem correct because the total of "All (hrs/day)" should be 8 hours. However, this total is only about 5 hours? Everything else looks correct.
- Tab Gitlab#11: It looks like the query yielded much lower figures than expected? For example, "APersonAll" shows 0:12 hrs/day (Cell B4), which is the result of dividing 14 (APersonAll) by 541 (Total). However, the total from the query for All is actually only 61 (Cell A19). This issue applies to all the cells of the table. As a result, the total hours of the three groups range between 1 and 3 whereas it should be 8 hours. 

Am I missing something?

PS: Just making sure that we are on the same page: The tables in the google spreadsheet show only one column for the "hours/week" data. This is consistent with the mockup dashboard that Paul shared. However, the final dashboard should include also the columns with the "My data" and "My team" data weekly hours.

**Comment by ultimike** [comment]
@escoach Regarding the data in column B of "Tab Gitlab #8", I think the issue is that there are 194 records in the `surveycampaign_results` table where `answer483` IS NULL.

If you look at the main query above, you'll see that the "All" column is not limited to non-null values of `answer483` - should it be?

Also - thanks for letting me know about the additional "My data" and "My team" hours/week stuff - since none of the mockups had it, I was leaving it off purposely. I just added it to the "Tab Gitlab #8".

I'll respond to the "Tab Gitlab #11" stuff in #11. 

-mike

**Comment by escoach** [comment]
@ultimike Good catch about the NULL records. Yes NULL should be eliminated. I believe that most of them are when users select "out of office" in the first question. So those records should be dropped. There might be a few cases when users abandon the survey before the end, but they are rarer. Regardless, if a question in the survey was not answered, then that record should not be included in the data analysis. I assume that you edit the query to drop NULL cases or let us know.

**Comment by ultimike** [comment]
@escoach I've updated the query (above) as well as the Google Sheet with the `IS NOT NULL` stuff. Please confirm all is correct.

thanks,  
-mike

**Comment by escoach** [comment]
Looks good, thank you!

**Comment by escoach** [comment]
@ultimike From what I understand, it looks good. Thanks.
You probably have addressed it, but what if a user selects both "Who/else" and "Where"? Will they get an error message? Or does the query prioritize either "Who/else" or "Where"? If that is the case, prioritizing "Who/else" is preferred vs prioritizing "Where". Or perhaps whatever is picked first is displayed? e.g. if a user selects "Where", then the user can't select "Who/else" and vice versa.

**Comment by ultimike** [comment]
We're going to not allow selections from both "Who" and "Where", as you requested previously.

-mike

**Comment by ultimike** [comment]
@mgcobblestone Working to validate the queries in the survey_dashboard module, I ran this case on my local as my personal username (so I have no "my data", and my provider is NULL). 

The results for "my data" and "my team data" are all 0, as is to be expected. 

The results for "all data" are correct with the exception of the "TotalAll" value. With the database I have, the value should be 343, but the /dashboard page shows a value of 545. The difference is that the /dashboard query is missing (as far as I can tell) the `WHERE answer483 IS NOT NULL` bit. This is important because we want to limit the query to responses where a "what" was provided.

-mike

**Comment by mgcobblestone** [comment]
@ultimike Fixes are up for missing NOT NULL and TotalProvider field.

**Comment by ultimike** [comment]
@mgcobblestone Looks good - the only thing that is missing is the `TotalMe` value - which in my user's case is 0, so I'm not sure that we actually need it. 

But, I also ran it using the `paul.foos@umb.edu` user and all of that user's data matched my manual queries, but again, the `TotalMe` value was missing, so I think that is definitely a bug.

**Comment by ultimike** [comment]
@mgcobblestone the table looks good! Data looks good!

As we discussed on Slack, all that is missing is the "Total respondents" row.

-mike

**Comment by ultimike** [comment]
@mgcobblestone Good news/bad news situation:

- Good news: the total rows values look good (sort of)
- Bad news: it appears that we lost the `WHERE answer483 IS NOT NULL` bit of the query. So, the values in the data table (including the total rows) are correct if we didn't want the `WHERE answer483 IS NOT NULL` - but we do want that bit, so all the values are wrong (but should be 100% correct once it is added back in. 

Make sense?

thanks,  
-mike

**Comment by ultimike** [comment]
@mgcobblestone Woot! This one now looks good-to-go! 😄 

-mike

**Comment by ultimike** [comment]
All done here. Closing.
