### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#80]
@ultimike I talked with @escoach today and we discussed what work remains on this job.  We have a few smallish tasks but first we would like to know where you are with what you are working on now.  We also wanted to make sure you are not going ahead with jobs that we cancelled, particularly the quarterly trends.  If you have an estimate of hours left when you wrap up these tasks we can discuss what might be done with your remaining time.  Thanks.

**Comment by ultimike** [comment]
We are not currently working on any tasks. The quarterly trends is/wasn't a
big deal, I think it is basically done. If you have something else in mind
for it, we are happy to disable it.

Mike

**Comment by thinkcollege** [comment]
Any estimate of remaining hours @ultimike?

**Comment by ultimike** [comment]
@thinkcollege I'll do some math and send you an email with details.

-mike

**Comment by escoach** [comment]
@ultimike thanks.  @thinkcollege asked me to confirm that we would like to pause the quarterly trends charts until we have a better sense of the hours left and how to best use the remaining hours.

**Comment by ultimike** [comment]
Would you like us to disable that option from the drop-down list?

-mike

**Comment by escoach** [comment]
@ultimike  After I cleared the cache now I see the quarterly charts. I guess that I underestimated how far ahead you were in the process. I thought that we were still at the early stage of the development of those charts. 

So to answer your question, I think it is fine to leave the option in the drop-down menu. I assume that there is no additional substantial work on them except perhaps some tweaks. 
Thanks for your patience with my misunderstanding.

**Comment by ultimike** [comment]
@escoach Any additional changes are up-to-you. There's nothing that we are currently working on. As @thinkcollege requested, we're paused until requested otherwise.

-mike

**Comment by thinkcollege** [comment]
HI @ultimike  There is one priority task that @escoach and I agreed on as we wrap up the project.  I will run it by you and if you think it can be accomplished with your remaining hours let's get going on it.
We want to alter the query you created to exclude survey responses from users with provider "Observer" from All results in the dashboard.  The provider, remember, comes from field_provider in the "Survey participants" user profile.  Instead, we want to exclude survey responses from the All results for users where the field_registration_code value in the Survey participants profile is < 10000.  This gives us the ability to  create more providers for trial users and not have their responses pollute the All data.  With the new query we can just give "Observer" a registration code vaule of 9999 and its data will not show up in All.  I realize that the value for the field_provider profile field is inserted in the surveycampaign_results table and the value for field_registration_code is not.  
I can think of two alternatives to help build the modified query: 1) I modify the surveycampaign_results table to include a column for registration code so you can pull it into your existing query 2) you build an entity query that pulls it from the user profile object. 
 I think option 2 would cost more of your time so I am willing to go ahead with 1 if you don't see problems with that.   There is a one-to-one relationship between each field_registration_code and field_provider in the Survey participants profile.   That relationship is set in a config at /admin/surveyconfig/regcodes 
Let me know if you have questions.

**Comment by ultimike** [comment]
@thinkcollege,

I'm teaching all day today, but I'll take a look at this tomorrow.

thanks,  
-mike

**Comment by ultimike** [comment]
@thinkcollege Yes - option 1 (including the registration code in the `surveycampaign_results` table) will be easier.

So, if I understand this correctly, once that field is in the table, if we (some hand-waving here) just swap out our "provider = 'Observer'" bits with "field_registration_code < 10000" will that accomplish the task? Is that what you envision?

thanks,  
-mike

**Comment by thinkcollege** [comment]
@ultimike  I am working on option 1, a new column in the surveycampaign_results table with the registration codes from the user profile.  Your understanding of the logic is correct.  I will let you know when I have this set up.

**Comment by thinkcollege** [comment]
@ultimike @escoach  After some delay I worked on what we discussed above.  There is now a 'regcode' integer field in the surveycampaign_results table.  I added the field on the live and development sites and added the codes that correspond to the providers where a code/provider relationship exists.  I did some programming in the surveycampaign module so that the code will get added to the table every time it grabs survey results from Surveygizmo and inserts them in the surveycampaign_results table.  As we discussed, codes <= 10000 will not get added to All results in the dashboard.  You could do a straightforward replacement in your queries (as you said above) of provider = 'Observer' with the regcode <= 10000 to withhold survey results from the All tablulation.

**Comment by ultimike** [comment]
@thinkcollege Good deal - can you send me a fresh copy of the `surveycampaign_results` table, please? Can I assume that it will have the same data as is on the https://rp-escoach.communityinclusion.org site (with the new field and data)?

thanks,  
-mike

**Comment by thinkcollege** [comment]
@ultimike Here is the surveycampaign_results table, the same one that is on rp-escoach.communityinclusion.org  Note that this is quite a bit out of date compared to the results table on the live site.  The registration codes haven't been set up on the development site--there is only one that corresponds to the data in the results table, the provider called "Observer."
[surveycampaign_results.zip](https://github.com/communityinclusion/escoach/files/7628540/surveycampaign_results.zip)

**Comment by ultimike** [comment]
@thinkcollege Thank you! Safe to assume that we're not going to be including data where `regcode < 10000` or `regcode IS NULL`?

**Comment by thinkcollege** [comment]
Yes, <=10000 or NULL not included in the All data

**Comment by ultimike** [comment]
@thinkcollege Working on my local, should I expect the results to be exactly the same when using `provider = Observer` or `regcode <= 10000`?

Or, in the dataset, will there be some records where a `regcode` isn't less than 10000, but the provider is equal to "Observer"? (or vice-versa)

For example, Survey ID 5420562 has a regcode of 9976, and a provider of "AccessPoint RI".

I'm trying to figure out the best way to test/validate the changes locally before I commit and push. Should we ask @escoach to update a few of the datasets in his "Dashboard examples 081921" Google Sheet?

thanks,  
-mike

**Comment by thinkcollege** [comment]
You can work that out with @escoach  The development site results data is old.  It was compiled before we had the registration codes in place.  You could assign some registration codes to providers already in the table, and populate the regcode column with those codes. Let me know how I can help.

**Comment by escoach** [comment]
@ultimike @thinkcollege I am happy to generate a few tables later today.

**Comment by ultimike** [comment]
@thinkcollege @escoach Well, as we saw previously, the only way this works is if we're all working off of the same data...

How about we all use the data @thinkcollege posted [above](https://github.com/communityinclusion/escoach/issues/80#issuecomment-982981177)?

@thinkcollege Can you import it to the rp-escoach site? 

@escoach: I've exported the data from above as a .csv for you to work from. 
[surveycampaign_results.csv.zip](https://github.com/communityinclusion/escoach/files/7636176/surveycampaign_results.csv.zip)
 
Does this work for everyone?

thanks,  
-mike

**Comment by thinkcollege** [comment]
@ultimike That data was pulled from the rp-escoach.communityinclusion.org site.  So no need to import it unless you have made changes to it.

**Comment by escoach** [comment]
@thinkcollege I am using the file that @ultimike posted above. Is it normal that I am getting only 97 rows with regcode NOT NULL out of 793 records? 
 

![image](https://user-images.githubusercontent.com/83360935/144323333-1f9f9fc7-0160-49e1-a363-1d302a7847f2.png)

**Comment by thinkcollege** [comment]
Yes, as I said a few times above, the survey data on the development site is old data from before the registration codes were being used and before we had many providers entered in the system.  I don't know what you want to do about that.  If you want to upload data from the live site I can do that, or if you have other data in your spreadsheets I can upload that.

**Comment by escoach** [comment]
I see. The issue is that, based on this spreadsheet, my tables will yield zero data in the "All" column because all records are either <10K or NULL. 
Would it work if I manually assign codes in the regcode column (some >10K some <10K) and we use that to generate tables? It's totaly fake data, but I guess we only need to test the math/logic.

To recreate a more realistic scenario, the other option is that you download a new spreadsheet with recent data. We will still need to fill in the regcode column with some codes <10K (e.g. Observer = 1344 and some random codes for the providers that are not part of the MN project). I could do that. 

Am I off track?

**Comment by escoach** [comment]
Hi @ultimike and @thinkcollege,
I manually assigned codes to the "regcode" field and run a table. All information about what I did and the specifications are in the [Google sheet, Tab "Code1202221".](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=545026318)

The new file is attached:
[surveycampaign_results 120221.xlsx](https://github.com/communityinclusion/escoach/files/7646113/surveycampaign_results.120221.xlsx)

Let me know if this is not what you need.

**Comment by ultimike** [comment]
Hmm - before I dig into this, I just want to confirm that we're going about this the right way...

Looking at the Google Sheet, it appears that @escoach made the following changes to the data:

- Deleted "not at work (482 = 11760): 303 records
- Deleted id482 = \"type\":\"HIDDEN\": 37 records
- Deleted 482=NULL: 18 records
- Assigned new fictional "regcode" values.

Does this mean that we need to modify the data in the live and rp-escoach sites in a similar manner?

Or, are these changes just for local testing (not on the live site or rp-escoach)? If they are just for local testing, then once I pull the changes into the rp-escoach site, we won't be able to validate the results against anything (as the source data will be different). 

I guess I'm not clear on why we're not using the canonical data as provided by @thinkcollege above for the validation (like we did last time). 

Please advise.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike I see. No problems, I will redo it using the file provided by @thinkcollege

**Comment by thinkcollege** [comment]
@ultimike @escoach I could send you the surveycampaign_mailer table from the live site if that helps.  Not being 100% sure how your dashboard application works I did not know if that would mess with anything on the dev site since that has a different user base and set of provider taxonomy terms.  At the very least you would not get good results when you logged in as a user because your provider and user might not align.  I have not been following the dashboard super closely but can work with you on this.

**Comment by thinkcollege** [comment]
Another thing we could do would be to just overwrite the dev site db with the live site db.  As long as we make sure cron is not running, it should be fine for testing the dashboard.  Think about whether that works for you.

**Comment by ultimike** [comment]
@thinkcollege is the new `regcode` stuff on the live site yet?

I think the safest and most reliable option is to use the same dataset everywhere - so, IMHO, that means copying the `surveycampaign_results` from live to dev, then also providing a copy of that to @escoach and I for local testing/validation.

This seems like it is becoming more complicated than it should be...

-mike

**Comment by thinkcollege** [comment]
Attached is the sql file for surveycampaign_results and a csv version of same.  Keep in mind that the live site is updated every day and as I said above the live site and dev site have different users and different provider taxonomies.  So you are working with the same data table but not the same "dataset." And what isn't more complicated than it should be?  I can't figure out my microwave.
[surveycampaign_results.zip](https://github.com/communityinclusion/escoach/files/7652077/surveycampaign_results.zip)
"
[surveycampaign_results.csv](https://github.com/communityinclusion/escoach/files/7652079/surveycampaign_results.csv)

**Comment by thinkcollege** [comment]
@escoach Oh, and yes, the regcodes are in effect on the live site.  The system for adding and using regcodes is on the dev site but the provider taxonomy data and the regcode fields have not been filled in.

**Comment by ultimike** [comment]
@thinkcollege It looks like the data you attached above doesn't have any `regcode > 10000`, please confirm this is correct.

There are 1,151 records in the `surveycampaign_results` table and there are 132 records with `provider = Observer`. On my local, I'm using the `alberto` user, whose `provider = Observer`. @escoach Does this all work for you for testing the new "regcode" stuff?

-mike

**Comment by escoach** [comment]
I am looking into it. However, I do see regcode > 10K. I will play with it
![image](https://user-images.githubusercontent.com/83360935/144669914-8fd48036-4726-4dba-95aa-ed04c99360ec.png)

**Comment by thinkcollege** [comment]
I see at least a handful of providers with regcode greater than 10000.  And I see them in the image above

**Comment by ultimike** [comment]
Ok - my bad - I failed to properly import the `surveycampaign_results` table on my local - oops!

I see 1,693 total records with 1.458 having `regcode > 10000`, 83 having `regcode = NULL` and 152 having `regcode < 10000`

**Comment by escoach** [comment]
@ultimike see if this Google sheet is better, [see tab "Code120321"](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=93699484). 
I used the file that Paul's just shared above. I run a default table (No What, Who, or Where selected) using both Alberto (Team = Observer regcode <10K) in Table 1 and using a random participant (regcode >10K) in Table 2.
Let me know if we are still not heading in the right direction.

**Comment by ultimike** [comment]
@escoach I'm still a little concerned about the manual data edits you're making as we're not doing anything like that in the code...

- Excluded "not at work (482 = 11760): 258 records
- Excluded id482 = \"type\":\"HIDDEN\": 44 records
- Excluded 482= empty cells: 2 records

-mike

**Comment by escoach** [comment]
@ultimike mhhh I think it's fine. I did the same when developing the past tables last summer. The only difference is that this time I shared those notes?

**Comment by thinkcollege** [comment]
I am so glad I contracted this job out.  Oops, did I say that out loud?

**Comment by escoach** [comment]
@ultimike for peace of mind I re-run my queries using the original spreadsheet that Paul sent, without editing anything. I got the same results. So it looks we are good.

**Comment by ultimike** [comment]
@escoach Hmm - I'm not seeing the same results as you on my local...

Looking at the first case on your Google Sheet (WHAT = No selection; WHO = No selection; WHERE = No selection), where your totals are:

- All = 1253
- Team = 33
- My data = 35

I'm getting:

- All = 1225
- Team = 37
- My data = 35

My query is using the following to count observer data that should be ignored: `(regcode <= 10000 OR regcode IS NULL)`

I am seeing 1376 records where `answer483 IS NOT NULL`, of those 151 have `(regcode <= 10000 OR regcode IS NULL)`. (1376 - 151 = 1225).

I am also using the "alberto.migliore@umb.edu" as the "My" and "Observer" as the "Provider".

Looking at data for each "what" activity in the table, my local "My data" matches yours (5, 1, 6, 10, 9, 4), but my local data doesn't match your "All" (83, 184, 149, 407, 492, 61) or "My team" (6, 1, 6, 11, 9, 4) data.

Any idea where the differences might be coming from?

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike thank you. Here are a few thoughts

 _You wrote: I am seeing 1376 records where answer483 IS NOT NULL, of those 151 have (regcode <= 10000 OR regcode IS NULL). (1376 - 151 = 1225)._

My comment: Shouldn't be just (regcode <= 10000)? If I read it correctly, your query seems to add the NULL records along with the <=10000? This might explain the "All" data discrepancy?

_You wrote: I am also using the "alberto.migliore@umb.edu" as the "My" and "Observer" as the "Provider"._

My comment: We no longer use "Observer" to identify the providers. Instead, we use regcode. For "My Team" I used regcode = 1344 in Table 1 (In table 2 I used regcode 39569). That might explain the discrepancy in the team data?

Also, all my queries exclude 482=11760 (I am not at work today / On a break or lunch). If you have not done so, I would recommend doing it. I noticed a handful of records that have sporadic data in 483 and other fields despite they reported being out of office. Those are not legitimate data.

Thanks

**Comment by ultimike** [comment]
### NULL stuff

@escoach, regarding the NULL values of regcode, I previously discussed this with @thinkcollege and he confirmed we should be ignoring `regcode IS NULL` - see [his comment above](https://github.com/communityinclusion/escoach/issues/80#issuecomment-983016196).

### Observer vs. regcode

For the "Observer" stuff, your "alberto.migliore@umb.edu" user has "Observer" set as their provider via the site UI (/user/19/survey_participants). How do I "convert" this to regcode 1344? We're going to need to have a lookup table or something to convert the Observer set in the user's profile to a regcode value, no? For example, how will we know that the regcode for "LIFE Inc." is 46294? 

I going to guess that you're going to say that we can just look it up in the `surveycampaign_results` table, but the problem with that is there are going to be multiple rows with the Observer name and regcode value, but how do we know which row to use (programmatically)? For example, most rows where provider="Observer" correspond with regcode=1344, but there are 3 rows where regcode=1000. The same goes for "LIFE Inc." - while most rows have regcode=46294, 15 of them have regcode=1000.

### Sample data

Also - looking at your data (still only looking at your first example), how is it possible that for "Other supports BEFORE hire" your "team" value is less than your "my" value? Shouldn't the "team" value always be greater than or equal to the "my" value as the "my" value is part of the "team" value?

![Screen Shot 2021-12-06 at 5 01 40 PM](https://user-images.githubusercontent.com/1727889/144879537-54e92223-3595-4153-8ed4-f9511c52a0c9.png)

### Exclude 482=11760

Regarding "all my queries exclude 482=11760", is this new? We've never had this as part of the queries and prior to the regcode stuff our results have been in agreement with your test results. 

-mike

**Comment by thinkcollege** [comment]
@ultimike I forgot to add the Registration code field to the user profile on the dev site.  I just added it now.  It is in the code but it wasn't in the db.  Which is why I offered to update the dev site with the live site code.  Also, you indicated that you wanted to work from the surveycampaign_results table, not to have to make a query against the user profile object.  Going forward, there shouldn't ever be an entry in the surveycampaign_results table that doesn't have a registration code.  Users signing up are now forced to enter a registration code.  The provider field is more or less redundant now, but we can leave it there to handle queries that were built before we added the registration code.  If there are any "Observer" users with null regcode fields we need to just manually fill them in with 1344.  If I can help with that let me know.  I ran

**Comment by ultimike** [comment]
@thinkcollege Ok - understood, thanks for the info. We've been querying the user profile all along, in order to get the "Provider" value. I'll check out the dev site and make the necessary changes on my local for the new regcode field.

I think it is best if we update our queries to use regcode and not provider - that shouldn't be a big deal.

I'm not clear if we should still be ignoring regcode NULL values or not. It sounds like that all that are records that have regcode=NULL should be updated to 1344, correct?

-mike

**Comment by thinkcollege** [comment]
@ultimike Yes, we should ignore the nulls or update them.  We have been running ES-Coach for several months with data that is not very good and making a lot of changes.  I think we are safe to say future users will all have registration codes and build the system accordingly.  **However, we still need the provider in the queries.**  @escoach wants to be able to change a registration code for a provider after they have completed a trial period and their data can begin to be included in the All data.  So, I take back my comment about the provider being redundant.  For purposes of the dashboard the regcode field is just going to determine whether the survey data gets included in the all data.

**Comment by escoach** [comment]
@ultimike I agree ignore NULL. I think that I misunderstood something when I wrote my earlier comment.

**Comment by escoach** [comment]
@ultimike Please ignore my comment about excluding 482 = 11760.  For some reason, I thought we included that in earlier queries. My mistake.

**Comment by ultimike** [comment]
@thinkcollege, @escoach Thanks for the clarifications. Summarizing:

### NULL stuff

I'm not a big fan of messing with the raw data - I'll let the two of you handle that, so I'm not going to modify my local `surveycampaign_results` table. Instead, I'm going to keep the `regcode <= 10000 OR regcode IS NULL` logic in the queries.

### Provider vs. regcode

What you're saying makes sense: we'll use the user's provider value to query for "My team" data (as we've been doing all along) but now exclude data via the value of the regcode (`regcode <= 10000 OR regcode IS NULL`).

### Sample data

@escoach Please see my question [above](https://github.com/communityinclusion/escoach/issues/80#issuecomment-986921933) about your "My data" vs. "My team" data discrepancy. Something still doesn't seem right there.

### Exclude 482=11760

Comment ignored 😄 No changes related to this.

### Relooking at [Dashboard examples 081921](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=93699484) ("Code 120321" tab)

@escoach As I'm still not able to reproduce the results of your first example (" WHAT = No selection; WHO = No selection; WHERE = No selection"), I though it might be helpful if I provided you with some quick info about the data I'm seeing in the dataset for this case:

- There are 46 rows in the table where email = 'alberto.migliore@umb.edu' and provider='Observer'. There are 0 rows where email = 'alberto.migliore@umb.edu' and provider!='Observer'.  
- There are 1376 rows in the table where answer483 IS NOT NULL.  
- There are 35 rows in the table where answer483 IS NOT NULL and email = 'alberto.migliore@umb.edu'.  
- There are 37 rows in the table where answer483 IS NOT NULL and provider = 'Observer'.  
- There are 151 rows in the table where answer483 IS NOT NULL and (regcode <= 10000 OR regcode IS NULL).  

Hopefully, this data will help us get to the bottom of the differences between your Google Sheet and my queries. Any insight?

thanks,
-mike

**Comment by escoach** [comment]
@ultimike my data now match your data. See the new [tab "Code120721"](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1023728622)

The discrepancies were due mostly to me forgetting to exclude id483=NULL and, instead, excluding id482 out office. 
There was also an issue with regcode = NULL. Anyway, it looks like now we are on the same page. 

Let me know if you have any questions or concerns. Thank you!

**Comment by ultimike** [comment]
@escoach Very good. I just tried comparing your "Table 2" data with results from my local, but it looks like you have some math errors. 

- All = regcode > 10,000 |  
- Team = "provider" = Best Buddies International |  
- My data = email= pammiller@bestbuddies.org

For example, the equation in cell C30 reads `=J30/C$17*8/24` when it should be (I believe) `=J30/C$36*8/24`. Most (all?) of the other cells in that table have the same issue. Here's a screenshot of the results from my local site:

<img width="665" alt="Screen Shot 2021-12-08 at 8 54 46 AM" src="https://user-images.githubusercontent.com/1727889/145170082-224e8a46-2ce4-48c8-a682-e1b4a2b646f0.png">

Would you mind updating your table (I'd do it for you, but I only have "View only" permissions) and confirm our results match. Once we do that, then I'll commit and push the code changes to the rp-escoach site.

-mike

**Comment by escoach** [comment]
@ultimike good catch! I [updated Table 2](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1023728622). Thank you!

**Comment by ultimike** [comment]
@escoach @thinkcollege I have pushed the changes implementing the new observer query logic utilizing the `regcode` field to the `devel` branch - it should be available for testing on the rp-escoach site.

-mike

**Comment by escoach** [comment]
@ultimike Thank you. The data tested fine and @thinkcollege pushed the code to the live site. I checked the live site data as well and I did not find any discrepancy between the live dashboard table and my computations. Everything looks good. Thank you!

**Comment by ultimike** [comment]
Sweet!!!

-mike
