### ISSUE TITLE
Trends chart labels

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#82]
Via email, from @thinkcollege:

` It would be better if the labels on the chart had labels like Jul.-Sept. 2021, Oct.-Dec. 2021, etc.` (instead of Q1, Q2, Q3, and Q4).

@mgcobblestone thoughts?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Seems do-able though I'll need to look into it.  Hopefully an hour or less.

**Comment by mgcobblestone** [comment]
@ultimike New fix is up for this.

**Comment by ultimike** [comment]
@mgcobblestone Looks good to me.

@thinkcollege This is working on my local, but doesn't appear on Dev (rp-escoach). Maybe the deployment process is having an issue?

-mike

**Comment by thinkcollege** [comment]
Yes, Jenkins quit on my devel server.  It is a memory hog.  I am trying to get the memory settings right.  You will probably have to do another commit to get the code to go through.

**Comment by ultimike** [comment]
@thinkcollege @escoach This is ready for testing on the dev site.

-mike

**Comment by escoach** [comment]
@ultimike @thinkcollege 
Looks good. Thank you!
I was curious, on Apr 1st, 2022, will the labels on the horizontal axis shift so users will see the following labels?
- Apr-Jun 2021
- Jul-Sep 2021
- Oct-Dec 2021
- Jan-Mar 2022

Or will the chart reset to 
- Jan-Mar 2022
[....]
- Oct-Dec 2022

Or do we need to wait and see?

**Comment by mgcobblestone** [comment]
@escoach The labels will shift as the year progresses, always showing the previous 4 quarters.

@ultimike We may want to adjust the query for this - currently it is from 1 year ago to today.  We might want to shift those dates back so they are from the first day of the quarter that the day 1 year ago falls into  through the last day of the most recently ended quarter.  Thoughts?

**Comment by ultimike** [comment]
As we are getting low on time, putting this task on hold until #81 is closed.

-mike

**Comment by escoach** [comment]
@ultimike After taking another closer look at the quarterly chart I noticed a couple of problems. I was chatting with @thinkcollege  and we agreed to ask what you think and if it is worth fixing the quarterly charts or whether we should hide them for now. We know we are low on time and do not want to push too close to the bottom. Moreover, the quarterly chart right now is not so useful until we have 3-4 quarters worth of data, next summer.
Here are the issues: 

- The providers started to submit data last September 24 at the earliest. Most started in October. Regardless, definitely they should NOT have data in the Jan-Mar quarter. But, as the screenshot below for one of the provider shows, for example, the quarterly chart shows that they reported data in Jan-Mar 2021. That is impossible.
- Also, shouldn’t the chart show a label for Apr-Jun 2021 as well? it's missing.

![image](https://user-images.githubusercontent.com/83360935/150392481-fecfb594-293f-4830-ba6f-d1e82c5b2514.png)

**Comment by ultimike** [comment]
@escoach We have 2.5 hours remaining - it would be very quick for us to display the quarterly charts.

The other option is that I can dig into the query to see where the issue is, but I cannot guarantee that we'll be able to make much headway in the time available. I am curious as to why/how data is showing for quarters where there shouldn't be...

Let me know how you'd like me to proceed. 

-mike

**Comment by thinkcollege** [comment]
@ultimike, @escoach and I agree it would be a good idea for you not to dive into the quarterly query, given how little time is left on the contract.  So, the remaining tasks would be to 1) hide Quarterly Trends in the Time Frame select list so users can't choose it. 2) fix the Submit button at the bottom of the dashboard, which currently is clearing the form instead of submitting as it is supposed to.

**Comment by ultimike** [comment]
@mgcobblestone ☝️ 

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Fix is up.  Did the submit button at the bottom of the form exist before?  I'm assuming it appeared after I moved it and the new Clear All button into an actions container.  So the new fix is to exclude that entire container from displaying.

**Comment by ultimike** [comment]
@mgcobblestone I'm still seeing the Quarterly Trends option in the dropdown - is this an oversight or does @thinkcollege need to kick the deployment server?

-mike

**Comment by mgcobblestone** [comment]
@ultimike Sorry, forgot to include that file in the commit.  Just pushed it.

**Comment by mgcobblestone** [comment]
@ultimike Debug has been removed.

**Comment by ultimike** [comment]
Sweet, thanks.

@escoach, @thinkcollege Are we all good with this task?

thanks,  
-mike

**Comment by thinkcollege** [comment]
Okay
