### ISSUE TITLE
Horizontal label

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#84]
From @thinkcollege via email:

```
Add the label "Percentage of time" and the 20, 40, 60, 80, and 100% marks on the horizontal axis of the "Up to date" chart. See image.
```

![Screenshot from 2022-01-10 15-29-02](https://user-images.githubusercontent.com/1727889/149006543-a0e09972-f492-436e-ba79-54de5f95fb94.png)

@mgcobblestone Easily doable?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Will need to look into this to see.  Should be doable, just not sure how easily.

**Comment by ultimike** [comment]
As we are getting low on time, putting this task on hold until #81 is closed.

-mike

**Comment by ultimike** [comment]
Ran out to time :(

**Comment by thinkcollege** [comment]
I will take care of it.
