### ISSUE TITLE
Chart tooltip text

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#85]
From @thinkcollege via email:

`In the tooltip that appears on the monthly and quarterly charts when you hover over the bar, the numbers that show up are confusing.  See picture:`

![Screenshot from 2022-01-10 15-32-08](https://user-images.githubusercontent.com/1727889/149006681-a72d6901-baa8-46d6-b699-162b8b2eca8a.png)

`The first number, with three decimal places just confuses the user.  It is not clear it is a percentage.  It would be better to just show the rounded number with the percent sign that is now in parentheses and not show the decimal.`

@mgcobblestone Thoughts?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike  Fix is up for this

**Comment by ultimike** [comment]
@escoach @thinkcollege Please review.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike I still see the two numbers on my screen instead of just the percentage.

**Comment by ultimike** [comment]
Ran out of time :(

**Comment by thinkcollege** [comment]
I will take care of it.
