### ISSUE TITLE
"Manager" role details

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#9]
Paul,

When someone is logged in as a "manager", other than the "Setup", does anything else about the interface change?

For the "Setup", does a manager user only see "My data" and "My Team data"?

thanks,  
-mike

![Screen Shot 2021-04-28 at 10 28 06 AM](https://user-images.githubusercontent.com/1727889/116421103-8cc92b00-a80c-11eb-8add-333ccd83b663.png)

**Comment by thinkcollege** [comment]
I have not yet created the Manager role on the site because I still have questions myself on just how that will work and would like to hear more from Alberto on that.  I am assuming the primary (or sole?) role of the manager is to look at his or her team on the dashboard.  I did create a survey participant role recently on the site.

**Comment by escoach** [comment]
Hi Mike, nice to meet you. I am Alberto. And thank you for your question.  
I should say that we have not really discussed this in detail, so feedback is welcome. But here is how I am envisioning it should work. Trying to keep it simple...

Nothing should change based on the role of the user. The changes are based on what data a user has entered. For example. 
1. I am an employment consultant and I entered data in the daily survey: I can select and see "My Data", "My Team Data", and "All data". 
2. I am a manager of a team and I entered data in the daily survey (I wear many hats). Same as #1.
3. I am a manager of a team but I did NOT enter data in the daily survey: I can see "My Team Data" and "All data". If I select "My data", I get a warning e.g. "You do not have data in the system to display"
4. I am someone who came across the home page as an external visitor (e.g. funding agency, job seeker, family member, potential future user). I can see "All data" only. If I select either "My data" or "My team" data I get the same warning as in #3.

 "All data" = aggregated data from all users.
Make sense?

**Comment by ultimike** [comment]
@escoach Heh - I think you have just created more questions :)

Maybe we should start from the beginning...

1. From your comment, "I am someone who came across the home page as an external visitor" it sounds like anonymous visitors to the site can access the Dashboard data? Is this correct?
2. How will user accounts be created (for employment consultants and managers)? I'm going to assume manually by a site administrator. 
3. If 2 is correct, then when an administrator creates a user account, at that time they should assign a role (or roles) the the user. For example, you wrote, "I am an employment consultant and I entered data in the daily survey" - so perhaps we need a "access team data" role. This would give users with this role access to "My data" and "My Team data".
4. As you wrote, if the logged in user doesn't have any "My data", then we can display some type of notice.

-mike

**Comment by thinkcollege** [comment]
Looks like we are not going to have a "manager" role.  Just survey participants who can see their individual data if they have entered any and non-reporting survey participants who can only see their aggregate team data based on the Provider they chose when they signed up.  We will have to query the data to see if they have responded and set a cut-off for amount of survey replies that qualify to be displayed as individual data.  Alberto should comment more on this and fill in details.

**Comment by escoach** [comment]
I agree with Paul's comment. However, to keep things simple, we do not need to query the data to see if they responded a minimum amount of surveys. I just chat with Paul to clarify this and we both agree.
The answer to your first question is: Yes, anonymous visitors can access the dashboard and browse the "All" aggregated data. We like to make the data public. Moreover, it's a way to engage the public and attract potential future users.
alberto

**Comment by ultimike** [comment]
@thinkcollege @escoach Thanks for the clarification. To summarize:

1. We don't need a "manager" role.
2. Anonymous users will be able to see "All data".
3. There is no minimum number of completed surveys for displaying "My data" or "My Team data". 

Let me know if I misunderstood anything.

thanks,  
-mike

**Comment by thinkcollege** [comment]
I am still concerned about not having a minimum amount of survey submissions before individual data shows up in the chart for individual or team data.  Since Alberto doesn't want to approve user registrations, we might not catch a spam user for a few days, so they could be pushing bad data into the system.

**Comment by escoach** [comment]
@ultimike your statement is correct: No "manager" role, Anonymous users can see "All data", and no minimum number of completed surveys for displaying "My data" or "My Team data".
Paul and I just talked on the phone. We both agree that at some point down the road we will need to find a solution to keep spammers out. But for now, we will be piloting the system with known entities. The risk of spam is negligible. We want to keep your work as simple as possible. Let us know if you have any concerns or recommendations.

**Comment by ultimike** [comment]
Understood. We'll proceed under the above assumptions.

thanks,  
-mike
