### ISSUE TITLE
Thoughts on new TA user role

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#90]
These are notes @ultimike and @mgcobblestone created while discussing how to potentially complete this task: 

- New profile type for TA (Technical Assistance) role that includes a multi-select field of providers. Only admin users will have access to editing this field. 
- When a user with the TA role logs in and visits their legacy Dashboard (this functionality is not for the new home page), the will see a new "Provider" select list that is populated from the selected providers in their profile. 
- When a TA user is on the legacy Dashboard page, we need modify the legacy Dashboard to allow data to be updated based on the provider selected in the new Provider select list.

**Comment by ultimike** [comment]
@thinkcollege A question about the TA user with regards to the initial tasks on this project (new Homepage view):

When a TA user is viewing either the new home page or a legacy Dashboard page, what should they see for the "Me" data? Should we just replace values with dashes for that column?

**Comment by thinkcollege** [comment]
See latest wireframes I sent on "Completion rate" thread.

**Comment by ultimike** [comment]
Completion rate thread: #91

**Comment by thinkcollege** [comment]
@ultimike @mgcobblestone I had Alberto do a tour of the development site at rp-escoach.communityinclusion.org  He said that we may need an easier way for an Administrator to add providers for a TA Admin.  Currently they are added on the Technical Assistant profile tab by adding one at a time from a repeating field.  A. said that some of the TA Admins will be administering dozens of providers.  In a few cases they will be administering ALL the providers in the system.  Can we come up with a practical way to add them in bulk?  A select or checkbox interface?  We may need the ability to sort or group the providers by state and/or another taxonomy field.  That may require adding those fields to the vocabulary.

**Comment by mgcobblestone** [comment]
@thinkcollege I have modified the field to use checkboxes instead of autocomplete.  This will require a config import.

cc: @ultimike

**Comment by thinkcollege** [comment]
Thanks @mgcobblestone It would be nice to have a check/uncheck all box.  Before we get too elaborate with this I will check in with Alberto, though and see if he has other requirements.

**Comment by thinkcollege** [comment]
@mgcobblestone I reviewed the new checkbox selection interface where site Admins can select providers for TA admins with Alberto. He says he is happy with that and agrees that a check/uncheck all selector would be useful.

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege , I'll look into adding that.

**Comment by thinkcollege** [comment]
@ultimike  When I add the TA admin role to users they then show up twice in the admin People listing.  I tried adding "Distinct" option to query settings on the View.  I also tried removing all the profile fields from the People view, stripping back to only the default columns of the People view.  But I still get the duplicate rows for TA users.

**Comment by ultimike** [comment]
@thinkcollege This isn't actually caused by the "TA admin" user role. This is actually a result of when we modified that view during phase 1 of the project last year to include a relationship with the "Profile"  module. 

> I also tried removing all the profile fields from the People view, stripping back to only the default columns of the People view. But I still get the duplicate rows for TA users.

You would also need to remove the 2 profile-related relationships to get the result you're looking for. Looking at things now, I don't actually know why the second relationship ("Profile (user)") is even there. I'm pretty sure it can be deleted without any harm.

-mike
