### ISSUE TITLE
"Completion rate" queries from Paul

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#91]
Via email from Paul on August 10, 2023.

For individual job coach (employment consultant):

```
select mailer.fullname, mailer.provider, count(*) 'total surveys sent to individual including out of office' , count(case when mailer.Complete =1 then 1 end) - count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values', (count(case when mailer.Complete =1 then 1 end) - count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id  where mailer.surveyid = 5420562 AND mailer.senddate >= '2023-07-01 00:00:00' AND mailer.senddate <= '2023-07-31 23:00:00' group by mailer.fullname order by fullname
```

For provider (team):

```
select mailer.provider, count(*) 'total surveys sent including out of office' ,count(case when mailer.Complete =1 then 1 end) 'total completed including out of office', count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end) 'net responses' ,count(case when results.answer482 = 11760 then 1 end) 'out of office' , ((count(case when mailer.Complete =1 then 1 end) -  count(case when results.answer482 = 11760 then 1 end)) / (count(*)  - count(case when results.answer482 = 11760 then 1 end) )) 'response rate with out of office subtracted from both values' , (count(case when mailer.Complete =1 then 1 end)- count(case when results.answer482 = 11760 then 1 end))/count(*) 'net responses/total surveys sent' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2022-11-01 00:00:00' AND mailer.senddate <= '2022-11-30 23:00:00' group by mailer.provider
```

From month to month, the dates will change in the query.

**Comment by ultimike** [comment]
@thinkcollege In our email thread on August 10, I asked:

> These are for the “75%+ Response Rate” row? If so, shouldn’t there be a “.75” or something similar in the query?
> 
> Or, does this just return a percentage that we report in the table?

You responded that you'd get with Alberto and get back to me on this...

**Comment by thinkcollege** [comment]
The response rate is just a response rate percentage of all the surveys sent/ surveys responded to.  The label for this row will be simply "Response rate"  But, if the response rate is 75% or more there will be a favorable marker (star or other), asterisk if under. 

  Likewise for "Number of participants" row.  If < 3 participants, it will get an asterisk (or other marker, still working on that) saying the results are not statistically valid.  I am attaching our latest design snapshots which should help with some of this.  Regrettably, these are not absolutely final but should help you along.  We have an internal ES-Coach meeting at 11:00 on Thurday.  Can you make that, or another time to discuss?
[wireframes_aug_23.zip](https://github.com/communityinclusion/escoach/files/12524413/wireframes_aug_23.zip)

**Comment by mgcobblestone** [comment]
@thinkcollege Should the response rate use the net rate or the rate that excludes the out-of-office responses?  Likewise for the respondent count?

**Comment by thinkcollege** [comment]
Here is Alberto's reply:
See below. Let me know if you have any questions.

Response Rate = Valid (Net) responses divided by surveys received  

 

I other words, take the number of responses, subtract the “out of office” responses and divide that number by the number of surveys that were sent.

 

For example, in the screenshot below Alexandra completed 19 of the 20 surveys received. But 2 surveys’ responses were “out of office”.

So the response rate is (19 total responses minus 2 “Out of office” responses) = 17 valid (net) responses divided by 20 surveys sent = 85%
![image001](https://github.com/communityinclusion/escoach/assets/1806420/81117dcc-bf55-4197-89f1-3700f64f2254)

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege !

**Comment by ultimike** [comment]
@mgcobblestone Any reason to keep this issue open? If not, please close.

thanks,
-mike
