### ISSUE TITLE
2023 Legacy Dashboard update - table rows questions

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#93]
1. On page 2 of "redesign_priorities_8_7_23.pdf", in the table below the chart, the rows appear to be renamed, top-level "What" values. For example, 

* "Leading to hire" = "Getting to know a job seeker" (or is it "Other supports BEFORE hire"?)
* "AFTER hire" = "Any supports AFTER hire"

Do we have this correct? If so, are the names changing as they are clearly not the same on the mockup as they are on the current site. 

2. On the current legacy dashboard, there are a total of 6 groups of activities, but the new home page design only shows "4 key activities". We are ignoring the other 2 on the home page, please confirm.

**Comment by thinkcollege** [comment]
I sent you this document, which explains the queries on the new home page.
[ES_Coach_query_explanations.pdf](https://github.com/communityinclusion/escoach/files/12524499/ES_Coach_query_explanations.pdf)

**Comment by ultimike** [comment]
From @thinkcollege in an email from August 10:

> The last two rows in the Key activities table (75%... and 3+ par...) should get different labels and be flipped in order.  The 3+ row will come first and should be labeled "Number of respondents"  The data in the row is simply the number of people in Team (or State) and All who responded during the month.  No number needed for Me, despite showing 1 in the design. If the number of respondents is 3 or less there should be a red exclamation mark.  In the key below we will explain that 3 or fewer respondents means the numbers above are statistically unreliable.  The 75+ Response rate column will be relabeled response rate.  You can use the query I sent you.  If the reponse rate is above 75% there will be a marker of some kind, let's say a different colored star saying the Me/Team/All had a good response rate.  That will be in our design too.

**Comment by mgcobblestone** [comment]
@thinkcollege I have added handling for displaying the icon for too few responses.  

I'm working on the 75%+ response rate handling but I don't see that in the design.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone The response rate icons appear to be working, for better than last month and better than all.
