### ISSUE TITLE
New home page - finalized designs

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#94]
@thinkcollege You mentioned a couple of weeks ago that there would be finalized designs for the new home page for us to utilize. Are they available yet?

thanks,
-mike

**Comment by thinkcollege** [comment]
See snapshots uploaded on "Completion rate" thread.  The labeling and other logic are in good shape.  Design and a few other issues are still in the works.  Our designer just got back from vacation.

**Comment by ultimike** [comment]
Completion rate thread: #91

**Comment by ultimike** [comment]
I think this issue can be closed based on the mockups we've been using in #99. @thinkcollege if you agree, please set this issue to closed.

thanks,
-mike
