### ISSUE TITLE
New home page - modes

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#95]
The new home page will have the following modes depending on the user viewing the page:

1. Anonymous user  
  *  No "Me" data.  
  *  No "My team" data. 
  * "State" can be selected from dropdown.  
2. Authenticated user with "Job type" (via Survey participants settings profile) value of "Employment consultant" or "Both manager and employment consultant"  (as well as "Survey participant" role).  
  * "Me", "My Team" data displayed.  
  * No "State" dropdown. Data pulled from their surveys. I have a note from August 10th about this, "Survey participation settings profile (for the "survey participant" role) includes a "Job type" select that includes things like "employment consultant" that can affect the home page and/or legacy dashboard."
3. Authenticated user without "Survey participant" role
  *  What does their home page look like?
4. Authenticated user with "Job type" (via Survey participants settings profile) value of "Manager of a team of employment consultants" or "Other"  (as well as "Survey participant" role).  
  *  What does their home page look like?
 5. Authenticated user with the Technical Assistance (TA) role
   *  No "Me"  data.  
   *  "My Team" data from provider selected.  
   * Provider dropdown.

**Comment by ultimike** [comment]
@thinkcollege Please review/clarify the above to ensure we're not missing anything.

What happens if an authenticated user has both the TA role and the Survey Participant role and a Job type of "Employment Consultant"? How do we handle the home page?

thanks,
-mike

**Comment by ultimike** [comment]
@thinkcollege Is this task still relevant? Can you review and let me know if there's anything we need to do with my previous questions?

thanks,
-mike

**Comment by thinkcollege** [comment]
Re: the question above from Sept. 5: if a user has TA user role that should override any other role assignment. So, the TA user would see the TA user home page

**Comment by mgcobblestone** [comment]
Thanks @thinkcollege , that is the current behavior
