### ISSUE TITLE
New home page - blue star logic

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#97]
For the home page blue star stuff, compare with the "All" column. It appears that for 'Administrative' and 'Non-employment', lower is better (the others are "higher is better").

@thinkcollege Please confirm this logic.

**Comment by thinkcollege** [comment]
Are you looking at the images I just sent?  That is explained in the notes at bottom.  I am attaching them again.
[wireframes_aug_23.zip](https://github.com/communityinclusion/escoach/files/12524721/wireframes_aug_23.zip)

**Comment by ultimike** [comment]
Via an email from @thinkcollege on August 10:

> Yes, less time spent (than All) on "Administrative" in the Key activities table earns a star.  Also, less time spent on Non-employment (than All) earns a star in the same table.  In the key below "Better than 'All'" should have a parenthetical comment "(less time is 'better' for Administrative and Non-employment)"  We will add that to the final design document.

**Comment by ultimike** [comment]
I think we're done here, appears to be working as expected. Closing.
