### ISSUE TITLE
New home page - best practices table

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#98]
For the "best practices" table, each row _should_ correspond to an existing query - @thinkcollege  will confirm and provide (or point to) where these queries are defined. (via discussion between Mike and Paul on August 10).

**Comment by ultimike** [comment]
@mgcobblestone See attached. 

[ES_Coach_query_explanations.pdf](https://github.com/communityinclusion/escoach/files/12524901/ES_Coach_query_explanations.pdf)

**Comment by ultimike** [comment]
For up-to-date definitions, see 
[es-coach_wireframe_Paul_edits_9_7-23.pdf](https://github.com/communityinclusion/escoach/files/12610555/es-coach_wireframe_Paul_edits_9_7-23.pdf)

**Comment by ultimike** [comment]
@thinkcollege On page 5 of es-coach_wireframe_Paul_edits_9_7-23.pdf, we think that the "Better" definitions are incorrect. If so, please provide us with the proper definitions. 

Specifically, the `"Better" means...` lines. 

(same issue on page 7 of the same pdf)

**Comment by thinkcollege** [comment]
Yes, we need to go over this text again.  I asked Alberto to do this.  We have finalized text and a final design coming in the next few days.

**Comment by ultimike** [comment]
@thinkcollege Are there any updates?

-mike

**Comment by thinkcollege** [comment]
Yes, see the attached Word document for a few text changes recommended by our copywriter.
[Dashboard text edits 110623.docx](https://github.com/communityinclusion/escoach/files/13271950/Dashboard.text.edits.110623.docx)

**Comment by thinkcollege** [comment]
Why is there a chart on the best practices page?  That was not in our wireframe or design layout.  We conceived of the two home page views, activities and best practices as one page with tabs to go back and forth.  And a third tab to jump to the legacy dashboard.  I don't see any of that navigation.

**Comment by mgcobblestone** [comment]
@thinkcollege Chart has been removed.  Cache rebuild will be required to see the change.

**Comment by thinkcollege** [comment]
Thanks @mgcobblestone Just a reminder, this was the final layout/design view (except for some small text changes which I posted here yesterday) https://jreposa.github.io/index.html

**Comment by mgcobblestone** [comment]
thanks @thinkcollege , I have pushed up a few updates with the copy changes and some styling.

**Comment by mgcobblestone** [comment]
Assigning to @thinkcollege for review

**Comment by thinkcollege** [comment]
@mgcobblestone I am seeing some differences from  https://jreposa.github.io/index.html  Like no table striping.  We also wanted the row of tabs at the top, Activities, Best Practices, More Metrics (the old dashboard).  Also some layout does not work well in handheld width, particularly the chart.

**Comment by mgcobblestone** [comment]
@ultimike I have pushed an update for this that adds striping and config for a new menu and it's block placement.
After importing config, you'll need to manually add the 3 menu items to the menu:

1. Activities -> /home/activities
2. Best Practices => /home/best_practices
3. More Metrics => /dashboard

I'm not sure if the block is placed in the correct region - feel free to update the config if nec'y.  Also, please review the layout issue on handhelds.
Thanks!

**Comment by ultimike** [comment]
@thinkcollege - I just pushed (to `es_home`) some theming tweaks (in addition to the tweaks @mgcobblestone pushed up as well yesterday).

1. Fixed the title theming - be sure to `drush cim` as well as create the menu items (as these are content, not config) as outlined by @mgcobblestone [here](https://github.com/communityinclusion/escoach/issues/98#issuecomment-1813243739). 
2. Updated the submenu block placement and theming.
3. You mentioned some issues with the mobile display, I didn't see anything super-broken. I did notice some extra space on the left-hand-side of the chart:

![Screenshot 2023-11-16 at 9 36 55 AM](https://github.com/communityinclusion/escoach/assets/1727889/669bac64-7f0f-4046-b749-738494c908a1)

Unfortunately, there's nothing we can reliably do about that as that is all controlled by the GChart. I'm not sure why they leave such a big margin on the left, my guess is that they are leaving room for the y-axis labels. I dug into their html/css pretty deep looking for a solution that would be consistent, but didn't find anything.

Take a look and let me know your thoughts.

-mike

P.S. To compile the b5subtheme's .scss into .css, I did the following (with some help from its README):

```
ddev ssh
cd web/themes/custom/b5subtheme
npm install -g sass
sass scss/style.scss css/style.css && sass scss/ck5style.scss css/ck5style.css
```

Note that doing thing this way will require the `npm install -g sass` step to be run each time the DDEV project is restarted, but that's not too big of a deal.

**Comment by thinkcollege** [comment]
I added the Hompage menu as a block on the rp-escoach.communityinclusion.org deployment of the devel branch, after merging new code and config from es_home.  It works tolerably well.  I placed the block in the main content region, above main page content.  It looks okay except it is not getting the active blue highlighting for the active page.  Also, we should remove the page title block from this page.  We are getting a redundant h1, page title, above the h1 for "Key Activities in..."  That is bad accessibility.  Sorry about your issues with DDEV.  Is there a better way to do this?  I run all my local sites on linux.

**Comment by ultimike** [comment]
@thinkcollege Did you do a config import? That will put the block in the proper place.

Also - be sure to do a cache rebuild, the redundant h1's should go away.

-mike

**Comment by thinkcollege** [comment]
The block had been placed way at the top, I forget which postion, above the page header and nav.  I removed it from there.

**Comment by ultimike** [comment]
Doh! I did a `git add` for the config changes on my local, but totally forgot to commit and push them until now. Sorry about that. I'm guessing at least some of the theming isn't working (like the "active" stuff because the block configuration IDs don't match up. Try removing the block placement (by un-placing the block on admin/structure/block) and then importing the config I just committed and see if it is any better. 

Looking at http://rp-escoach.communityinclusion.org/home/activities, I don't see the redundant h1s anymore, correct?

> Sorry about your issues with DDEV. Is there a better way to do this? I run all my local sites on linux.

Are you referring to the .scss stuff? That's not a DDEV issue at all - the method I used above is fine, not an issue.

-mike

**Comment by thinkcollege** [comment]
@ultimike  That's looking better.  Please note that I have uninstalled the google_tag module from devel and rack sites and uninstalled the mod in composer.  I don't want to get any errors when I import config from es_home, so please remove it on your end.

**Comment by ultimike** [comment]
@thinkcollege Understood. @mgcobblestone and I will disable the `google_tag` modules on our local so we don't commit any config for it to the repo.

Is there anything else that needs to be done with the "Best practices" table before we call it complete?

-mike

**Comment by thinkcollege** [comment]
@ultimike  A small thing, but the menu items in our design on the dashboard sub-menu (Activities, Best Practices, Dashboard) had rounded corners.

**Comment by ultimike** [comment]
@thinkcollege Ah - you are correct. Fixed pushed.

-mike

**Comment by thinkcollege** [comment]
@mgcobblestone @ultimike I am getting a js error when logged in as a TA user and trying to switch providers on the dashboard.  The provider does not change despite changing the select list.  I see that provider-select.js in the es_homepage module is still using the once library.

**Comment by mgcobblestone** [comment]
@thinkcollege I have pushed up a fix for this.

cc: @ultimike
